import {db,json,fail,sameOrigin,readJson,HttpError} from '@/lib/server';import {adminIdentity,audit} from '@/lib/admin';import {award} from '@/lib/leaderboard';import {referralEligibleSQL,eligibilityArgs} from '@/lib/referrals';import {z} from 'zod';
export async function GET(req:Request){try{await adminIdentity(req);const page=Math.max(0,Math.floor(Number(new URL(req.url).searchParams.get('page'))||0));const rows=await db().prepare(`SELECT f.*,r.username invited,v.username inviter,CAST((strftime('%s','now')*1000-f.created_at)/3600000 AS INTEGER) age_hours,(SELECT json_extract(state,'$.quest') FROM players WHERE user_id=f.user_id) starter_quest,(SELECT COUNT(DISTINCT day) FROM season_events e JOIN seasons s ON s.id=e.season_id WHERE e.user_id=f.user_id AND e.points>0 AND e.category IN ('daily','explore','dungeon') AND s.active_slot=1 AND s.status='active') scoring_days FROM referrals f JOIN registrations r ON r.user_id=f.user_id JOIN registrations v ON v.user_id=f.referrer_id ORDER BY CASE WHEN f.status='pending' THEN 0 ELSE 1 END,f.created_at DESC LIMIT 50 OFFSET ?`).bind(page*50).all();return json({rows:rows.results,page})}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const actor=await adminIdentity(req);const b=z.object({action:z.enum(['approve','reject','revoke']),id:z.string().max(100),note:z.string().trim().min(5).max(400)}).strict().parse(await readJson(req));const now=Date.now();const f=await db().prepare('SELECT * FROM referrals WHERE user_id=?').bind(b.id).first<{referrer_id:string;status:string;season_id:string|null}>();if(!f)throw new HttpError('Referral not found.',404);
 if(b.action==='approve'){
 if(!['pending','rejected'].includes(f.status))throw new HttpError('Referral already processed.',409);
 const eligible=await db().prepare(referralEligibleSQL).bind(...eligibilityArgs(b.id,now)).first();if(!eligible)throw new HttpError('Not qualified: check active referral rules, 72 hours, starter quest, three scoring days, exclusions and five-referral limit.',409);
 const source='referral:'+b.id;
 // Award first under the same transaction; mark approved only if points were actually issued.
 const result=await db().batch([
 award(f.referrer_id,'referral',source,now,`EXISTS(${referralEligibleSQL}) AND EXISTS(SELECT 1 FROM referrals WHERE user_id=? AND status IN ('pending','rejected'))`,[...eligibilityArgs(b.id,now),b.id]),
 db().prepare(`UPDATE referrals SET status='approved',note=?,reviewed_at=?,season_id=(SELECT id FROM seasons WHERE active_slot=1 AND status='active') WHERE user_id=? AND status IN ('pending','rejected') AND EXISTS(SELECT 1 FROM season_events e JOIN seasons s ON s.id=e.season_id WHERE s.active_slot=1 AND s.status='active' AND e.user_id=? AND e.source=? AND e.points>0)`).bind(b.note,now,b.id,f.referrer_id,source),
 audit(actor,'referral_review',b.id)
 ]);if(!result[1].meta.changes){throw new HttpError('Daily referral cap reached or referral changed. Retry on another scoring day.',409)}
 }else if(b.action==='reject'){
 const r=await db().prepare("UPDATE referrals SET status='rejected',note=?,reviewed_at=? WHERE user_id=? AND status IN ('pending','rejected')").bind(b.note,now,b.id).run();if(!r.meta.changes)throw new HttpError('Use revoke for an approved referral.',409);await audit(actor,'referral_reject',b.id).run();
 }else{
 const r=await db().batch([db().prepare("UPDATE referrals SET status='revoked',note=?,reviewed_at=? WHERE user_id=? AND status='approved' AND EXISTS(SELECT 1 FROM seasons WHERE id=referrals.season_id AND status='active')").bind(b.note,now,b.id),db().prepare("DELETE FROM season_events WHERE user_id=? AND source=? AND season_id=? AND EXISTS(SELECT 1 FROM referrals WHERE user_id=? AND status='revoked' AND reviewed_at=?) AND EXISTS(SELECT 1 FROM seasons WHERE id=? AND status='active')").bind(f.referrer_id,'referral:'+b.id,f.season_id,b.id,now,f.season_id),audit(actor,'referral_revoke',b.id)]);if(!r[0].meta.changes)throw new HttpError('Only approved referrals in an unfrozen season can be revoked.',409);
 }return json({ok:true})}catch(e){return fail(e)}}
