import {network} from 'hardhat';import {createPublicClient,createWalletClient,custom,parseEther,zeroAddress,keccak256,toHex} from 'viem';import assert from 'node:assert/strict';import fs from 'node:fs';
const connection=await network.create('local');const transport=custom(connection.provider);const rpc=createPublicClient({transport});const accounts=await connection.provider.request({method:'eth_accounts'});const [admin,A,B,treasury,attacker]=accounts;const wallet=a=>createWalletClient({transport,account:a});const artifacts=Object.fromEntries(['TrashPandaLand','TrashPandaAssets','TrashPandaPaymentRouter','TrashPandaMarketplace','MockToken'].map(n=>[n,JSON.parse(fs.readFileSync(`packages/contracts/artifacts/${n}.json`))]));
let passed=0;const ok=(name)=>{passed++;console.log('PASS '+name)};async function deploy(name,args=[]){const hash=await wallet(admin).deployContract({...artifacts[name],args,chain:null});const r=await rpc.waitForTransactionReceipt({hash});assert.equal(r.status,'success');return {address:r.contractAddress,abi:artifacts[name].abi};}async function write(c,fn,args=[],from=admin,value=0n){const hash=await wallet(from).writeContract({...c,functionName:fn,args,value,chain:null,gas:6000000n});const r=await rpc.waitForTransactionReceipt({hash});assert.equal(r.status,'success');return r;}async function reject(c,fn,args=[],from=admin,value=0n){await assert.rejects(()=>rpc.simulateContract({...c,functionName:fn,args,account:from,value}));}const read=(c,fn,args=[])=>rpc.readContract({...c,functionName:fn,args});
try{
 const land=await deploy('TrashPandaLand',[admin,100n,'https://example.invalid/land/']);const market=await deploy('TrashPandaMarketplace',[admin,treasury,250n]);const router=await deploy('TrashPandaPaymentRouter',[admin,land.address,treasury]);const token=await deploy('MockToken');const minter=keccak256(toHex('MINTER_ROLE'));await write(land,'grantRole',[minter,router.address]);await write(market,'setAsset',[land.address,true]);
 await reject(land,'mintLand',[attacker,15n],attacker);await reject(router,'configureSale',[15n,zeroAddress,1n,true],attacker);ok('unauthorized mint and sale configuration rejected');
 const price=parseEther('0.01');await write(router,'configureSale',[15n,zeroAddress,price,true]);await reject(router,'buyLand',[15n,zeroAddress,price],A,price-1n);await reject(router,'buyLand',[15n,zeroAddress,price+1n],A,price);ok('wrong value and changed price rejected');
 await write(router,'buyLand',[15n,zeroAddress,price],A,price);assert.equal((await read(land,'ownerOf',[15n])).toLowerCase(),A.toLowerCase());ok('wallet A buys parcel 15 and receives NFT');await reject(router,'buyLand',[15n,zeroAddress,price],B,price);ok('double purchase rejected');
 await reject(market,'list',[land.address,15n,zeroAddress,price],B);await reject(market,'list',[land.address,15n,zeroAddress,price],A);ok('wrong owner and missing NFT approval rejected');
 await write(land,'approve',[market.address,15n],A);await write(market,'list',[land.address,15n,zeroAddress,price],A);const beforeT=await rpc.getBalance({address:treasury}),beforeA=await rpc.getBalance({address:A});await write(market,'buy',[1n,zeroAddress,price],B,price);assert.equal((await read(land,'ownerOf',[15n])).toLowerCase(),B.toLowerCase());assert.equal((await rpc.getBalance({address:treasury}))-beforeT,price*250n/10000n);assert.equal((await rpc.getBalance({address:A}))-beforeA,price-price*250n/10000n);ok('A lists, B buys: exact seller payment, treasury fee, and NFT transfer');await reject(market,'buy',[1n,zeroAddress,price],A,price);ok('sold listing cannot be purchased twice');
 await write(land,'approve',[market.address,15n],B);await write(market,'list',[land.address,15n,zeroAddress,price],B);await reject(market,'cancel',[2n],A);await write(market,'cancel',[2n],B);await reject(market,'buy',[2n,zeroAddress,price],A,price);ok('seller cancellation and buyer rejection');
 await write(market,'list',[land.address,15n,zeroAddress,price],B);await write(land,'safeTransferFrom',[B,A,15n],B);await write(land,'safeTransferFrom',[A,B,15n],A);await write(land,'approve',[market.address,15n],B);await reject(market,'buy',[3n,zeroAddress,price],A,price);ok('stale listing stays invalid after transfer away and back');
 await write(router,'setCurrency',[token.address,true]);await write(market,'setCurrency',[token.address,true]);await write(token,'transfer',[A,parseEther('1000')]);await write(token,'transfer',[B,parseEther('1000')]);const tokens=parseEther('20');await write(router,'configureSale',[16n,token.address,tokens,true]);await reject(router,'buyLand',[16n,token.address,tokens],A);await write(token,'approve',[router.address,tokens],A);await write(router,'buyLand',[16n,token.address,tokens],A);assert.equal(await read(token,'allowance',[A,router.address]),0n);ok('ERC20 primary purchase and exact allowance consumption');
 await write(land,'approve',[market.address,16n],A);await write(market,'list',[land.address,16n,token.address,tokens],A);await write(token,'approve',[market.address,tokens],B);const t=await read(token,'balanceOf',[treasury]),s=await read(token,'balanceOf',[A]);await write(market,'buy',[4n,token.address,tokens],B);assert.equal(await read(token,'balanceOf',[treasury])-t,tokens*250n/10000n);assert.equal(await read(token,'balanceOf',[A])-s,tokens-tokens*250n/10000n);ok('ERC20 secondary purchase routes seller proceeds and fee');
 // Secondary-market lifecycle regression checks use a separate owned parcel.
 await write(router,'configureSale',[18n,zeroAddress,price,true]);await write(router,'buyLand',[18n,zeroAddress,price],A,price);
 await write(land,'approve',[market.address,18n],A);await write(market,'list',[land.address,18n,zeroAddress,price],A);
 const replaced=(await read(market,'nextListingId'))-1n;
 await write(market,'list',[land.address,18n,zeroAddress,price*2n],A);const latest=(await read(market,'nextListingId'))-1n;
 await reject(market,'buy',[replaced,zeroAddress,price],B,price);await reject(market,'buy',[latest,zeroAddress,price],B,price);
 assert.equal(await read(market,'activeListing',[land.address,18n]),latest);ok('replacement listing invalidates old offer and rejects old price');
 await write(land,'approve',[zeroAddress,18n],A);await reject(market,'buy',[latest,zeroAddress,price*2n],B,price*2n);
 await write(market,'cancel',[latest],A);assert.equal(await read(market,'activeListing',[land.address,18n]),0n);ok('revoked NFT approval blocks purchase but seller can still cancel');
 await write(land,'approve',[market.address,18n],A);await write(market,'list',[land.address,18n,zeroAddress,price],A);const frozen=(await read(market,'nextListingId'))-1n;
 await write(market,'configure',[attacker,500n]);const oldTreasury=await rpc.getBalance({address:treasury}),newTreasury=await rpc.getBalance({address:attacker});
 await write(market,'buy',[frozen,zeroAddress,price],B,price);assert.equal((await rpc.getBalance({address:treasury}))-oldTreasury,price*250n/10000n);assert.equal(await rpc.getBalance({address:attacker}),newTreasury);ok('existing listing retains agreed fee and treasury after admin configuration changes');
 await write(router,'setPaused',[true]);await write(router,'configureSale',[17n,zeroAddress,price,true]);await reject(router,'buyLand',[17n,zeroAddress,price],A,price);await write(land,'setPaused',[true]);await reject(land,'safeTransferFrom',[B,A,15n],B);await write(market,'setPaused',[true]);await reject(market,'list',[land.address,15n,zeroAddress,price],B);ok('paused sale, NFT transfer, and marketplace rejected');await reject(market,'configure',[zeroAddress,250n]);await reject(market,'configure',[treasury,1001n]);ok('zero treasury and excessive fee rejected');
 const assets=await deploy('TrashPandaAssets',[admin,'https://example.invalid/api/metadata/assets/']);await reject(assets,'mint',[A,1n],attacker);await reject(assets,'mint',[A,1n],admin);await write(assets,'grantRole',[minter,admin]);await write(assets,'mint',[A,1n]);assert.equal((await read(assets,'ownerOf',[1n])).toLowerCase(),A.toLowerCase());assert.equal(await read(assets,'tokenURI',[1n]),'https://example.invalid/api/metadata/assets/1');await reject(assets,'mint',[B,1n]);ok('item NFT mint permission, unique token and metadata URI');await write(assets,'safeTransferFrom',[A,B,1n],A);assert.equal((await read(assets,'ownerOf',[1n])).toLowerCase(),B.toLowerCase());ok('item NFT ownership changes after transfer');
 console.log(`\n${passed} contract scenarios passed on local EVM. This is not a Base Sepolia deployment.`);
}finally{await connection.close()}
