import {db,runtimeEnv} from '@/lib/server';
import {publicClient,landAbi,type Registry} from './config';
import {parseEventLogs} from 'viem';
export async function syncLand(c:Registry){if(!c.deployed)return {configured:false};const start=Number(runtimeEnv().DEPLOYMENT_BLOCK);if(!Number.isSafeInteger(start)||start<=0)return {configured:true,ready:false};const key=`${c.chainId}:${c.land}:${c.marketplace}`;const sql=db();await sql.prepare('INSERT INTO checkpoints(key,block,hash,locked_until) VALUES(?,?,?,0) ON CONFLICT(key) DO NOTHING').bind(key,start-1,'').run();const now=Date.now();const lease=await sql.prepare('UPDATE checkpoints SET locked_until=? WHERE key=? AND locked_until<? RETURNING block,hash').bind(now+60000,key,now).first<{block:number;hash:string}>();if(!lease)return {configured:true,busy:true};const rpc=publicClient(c);try{
 let from=lease.block+1;if(lease.hash){const block=await rpc.getBlock({blockNumber:BigInt(lease.block)});if(block.hash!==lease.hash){await sql.batch([sql.prepare('DELETE FROM chain_events WHERE chain_id=? AND contract IN (?,?)').bind(c.chainId,c.land!.toLowerCase(),c.marketplace!.toLowerCase()),sql.prepare('DELETE FROM land_projection WHERE chain_id=? AND contract=?').bind(c.chainId,c.land!.toLowerCase()),sql.prepare('UPDATE checkpoints SET block=?,hash=? WHERE key=?').bind(start-1,'',key)]);from=start;}}
 const safe=Number(await rpc.getBlockNumber())-12;if(from>safe)return {configured:true,ready:true};const to=Math.min(safe,from+1999);const logs=await rpc.getLogs({address:[c.land!,c.marketplace!],fromBlock:BigInt(from),toBlock:BigInt(to)});const statements:D1PreparedStatement[]=[];for(const log of logs){const id=`${c.chainId}:${log.address}:${log.transactionHash}:${log.logIndex}`;statements.push(sql.prepare('INSERT INTO chain_events(id,chain_id,contract,tx,log_index,block,block_hash) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,c.chainId,log.address.toLowerCase(),log.transactionHash,log.logIndex,Number(log.blockNumber),log.blockHash));if(log.address.toLowerCase()===c.land!.toLowerCase()){const event=parseEventLogs({abi:landAbi,eventName:'Transfer',logs:[log]})[0];if(event)statements.push(sql.prepare('INSERT INTO land_projection(id,chain_id,contract,owner,block,tx) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET chain_id=excluded.chain_id,contract=excluded.contract,owner=excluded.owner,block=excluded.block,tx=excluded.tx').bind(Number(event.args.tokenId),c.chainId,c.land!.toLowerCase(),event.args.to.toLowerCase(),Number(log.blockNumber),log.transactionHash));}}
 // Bounded chunks remain idempotent; advance the cursor only after all are committed.
 for(let i=0;i<statements.length;i+=40)await sql.batch(statements.slice(i,i+40));const block=await rpc.getBlock({blockNumber:BigInt(to)});await sql.prepare('UPDATE checkpoints SET block=?,hash=? WHERE key=?').bind(to,block.hash,key).run();return {configured:true,ready:to===safe,block:to};
 }finally{await sql.prepare('UPDATE checkpoints SET locked_until=0 WHERE key=?').bind(key).run()}}
