import {createWalletClient,custom,erc20Abi,zeroAddress,type Address,type Abi,formatEther} from 'viem';
import {base,baseSepolia} from 'viem/chains';
import {publicClient,type Registry} from './config';
import {requireWallet} from '@/lib/wallet-client';
export type TxRequest={address:Address;abi:Abi;functionName:string;args:readonly unknown[];value?:bigint;currency?:Address;amount?:bigint};
export async function clients(c:Registry){const {provider:activeProvider,account:activeAccount}=await requireWallet(c);return {wallet:createWalletClient({chain:c.chainId===8453?base:baseSepolia,transport:custom(activeProvider),account:activeAccount}),rpc:publicClient(c),account:activeAccount}}
export async function execute(c:Registry,tx:TxRequest,status:(value:string)=>void,hash:(value:string)=>void){const {wallet,rpc,account}=await clients(c);if(await wallet.getChainId()!==c.chainId)throw Error(`Switch your wallet to ${c.network}.`);if(tx.currency&&tx.currency!==zeroAddress&&tx.amount){const allowance=await rpc.readContract({address:tx.currency,abi:erc20Abi,functionName:'allowance',args:[account,tx.address]});if(allowance<tx.amount)throw Error('Approve the exact token amount before purchasing.');}status('Waiting for wallet');const {request}=await rpc.simulateContract({...tx,account});const checked=await requireWallet(c);if(checked.account.toLowerCase()!==account.toLowerCase())throw Error('Account changed. Review this transaction again.');const txHash=await wallet.writeContract(request);hash(txHash);status('Transaction submitted · Pending');const receipt=await rpc.waitForTransactionReceipt({hash:txHash,confirmations:2,timeout:120000});if(receipt.status!=='success')throw Error('Transaction reverted. No purchase was completed.');status('Confirmed');return receipt;}
export async function estimate(c:Registry,tx:TxRequest){const {rpc,account,wallet}=await clients(c);if(await wallet.getChainId()!==c.chainId)throw Error(`Switch your wallet to ${c.network}.`);const gas=await rpc.estimateContractGas({...tx,account});const price=await rpc.getGasPrice();return formatEther(gas*price);}
export function approval(tx:TxRequest):TxRequest{if(!tx.currency||!tx.amount)throw Error('No token approval required.');return {address:tx.currency,abi:erc20Abi,functionName:'approve',args:[tx.address,tx.amount]};}
