import {test,expect,type BrowserContext,type Page} from '@playwright/test';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {hexToString,type Hex} from 'viem';
// Test adapter implements only wallet I/O. Real nonce, signature verification, cookies,
// roles and player creation run through the application API and its isolated D1.
async function wallet(context:BrowserContext){const signer=privateKeyToAccount(generatePrivateKey());await context.exposeFunction('testWalletSign',async(message:Hex)=>signer.signMessage({message:hexToString(message)}));await context.addInitScript(({address})=>{let chain='0x14a34';let accounts:string[]=[address];const listeners:Record<string,Set<(v:unknown)=>void>>={};const emit=(event:string,value:unknown)=>listeners[event]?.forEach(fn=>fn(value));const state={reject:false,setAccount:(value:string)=>{accounts=[value];emit('accountsChanged',accounts)},setChain:(value:string)=>{chain=value;emit('chainChanged',value)}};Object.assign(window,{testWallet:state,ethereum:{on:(event:string,fn:(v:unknown)=>void)=>{(listeners[event]??=new Set()).add(fn)},removeListener:(event:string,fn:(v:unknown)=>void)=>listeners[event]?.delete(fn),request:async({method,params}:{method:string;params:unknown[]})=>{if(method==='eth_requestAccounts'||method==='eth_accounts')return accounts;if(method==='eth_chainId')return chain;if(method==='wallet_switchEthereumChain'){chain=(params[0] as {chainId:string}).chainId;emit('chainChanged',chain);return null}if(method==='personal_sign'){if(state.reject)throw Object.assign(Error('Signature declined'),{code:4001});return (window as unknown as {testWalletSign:(message:string)=>Promise<string>}).testWalletSign(params[0] as string)}throw Error('Unexpected test wallet request: '+method)}}})},{address:signer.address});return signer;}
async function terminal(page:Page){await page.getByRole('button',{name:/CONNECT WALLET|…|scav_/}).first().click();await expect(page.getByRole('dialog',{name:'WALLET TERMINAL'})).toBeVisible();}
async function signIn(page:Page){await terminal(page);const connect=page.getByRole('button',{name:'Browser wallet / MetaMask'});if(await connect.isVisible())await connect.click();await page.getByRole('button',{name:'SIGN IN WITH WALLET',exact:true}).click();}
async function create(context:BrowserContext,page:Page,start='/'){await wallet(context);const name='scav_'+crypto.randomUUID().replaceAll('-','').slice(0,12);await page.goto(start);await signIn(page);await page.getByRole('link',{name:'COMPLETE REGISTRATION',exact:true}).click();await page.getByLabel('GAME NAME',{exact:true}).fill(name);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'CREATE ACCOUNT & PLAYER',exact:true}).click();await expect(page.getByText('Account active · '+name,{exact:true})).toBeVisible();return name;}
test('Register → Game → landing and F5 preserve one user and player',async({context,page})=>{const name=await create(context,page);const before=await page.request.get('/api/auth/me').then(r=>r.json());await page.getByRole('link',{name:'ENTER TRASH TOWN',exact:true}).click();await expect(page.getByRole('button',{name,exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name,exact:true})).toBeVisible();await page.goto('/');await expect(page.getByRole('button',{name,exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name,exact:true})).toBeVisible();expect((await page.request.get('/api/auth/me').then(r=>r.json())).user.id).toBe(before.user.id);expect((await page.request.get('/api/game').then(r=>r.json())).character.username).toBe(name)});
test('Direct game login, shared tabs, logout and subsequent login',async({context,page})=>{const name=await create(context,page,'/game');const before=await page.request.get('/api/auth/me').then(r=>r.json());const game=await context.newPage();await game.goto('/game');await expect(game.getByRole('button',{name,exact:true})).toBeVisible();await page.getByRole('button',{name:'SIGN OUT',exact:true}).click();await expect(game.getByRole('heading',{name:'WELCOME SCAVENGER.'})).toBeVisible();await game.getByRole('button',{name:'CONNECT WALLET',exact:true}).click();await game.getByRole('button',{name:'SIGN IN WITH WALLET',exact:true}).click();await expect(game.getByRole('button',{name,exact:true})).toBeVisible();await expect(page.getByText('Account active · '+name,{exact:true})).toBeVisible();expect((await game.request.get('/api/auth/me').then(r=>r.json())).user.id).toBe(before.user.id)});
test('Session refresh retains identity; suspended/non-admin API remains protected',async({context,page})=>{await create(context,page);const before=await page.request.get('/api/auth/me').then(r=>r.json());const refresh=await page.request.post('/api/auth/refresh',{headers:{origin:new URL(page.url()).origin},data:{}});expect(refresh.status()).toBe(200);expect((await refresh.json()).user.id).toBe(before.user.id);expect((await page.request.get('/api/admin')).status()).toBe(403);await page.goto('/admin');await expect(page.getByRole('heading',{name:'RESTRICTED ACCESS',exact:true})).toBeVisible()});
test('Wallet/network switch and rejected signature are visible without fake login',async({context,page})=>{await wallet(context);await page.goto('/game');await terminal(page);await page.evaluate(()=>{(window as unknown as {testWallet:{reject:boolean}}).testWallet.reject=true});await page.getByRole('button',{name:'SIGN IN WITH WALLET',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('declined');expect((await page.request.get('/api/auth/me').then(r=>r.json())).authenticated).toBe(false);await page.evaluate(()=>{(window as unknown as {testWallet:{setChain:(c:string)=>void}}).testWallet.setChain('0x2105')});await expect(page.getByRole('button',{name:'SWITCH TO BASE SEPOLIA'})).toBeVisible()});
