import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import ts from 'typescript';
const require=createRequire(import.meta.url);let sql,cache,env,network,rpc,batchTail=Promise.resolve();
function stmt(text,args=[]){return {bind:(...a)=>stmt(text,a),first:async()=>sql.prepare(text).get(...args)??null,all:async()=>({results:sql.prepare(text).all(...args)}),run:async()=>({meta:{changes:Number(sql.prepare(text).run(...args).changes)}})}}
const db={prepare:stmt,batch:list=>{const task=batchTail.then(async()=>{sql.exec('BEGIN');try{const r=[];for(const s of list)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}});batchTail=task.catch(()=>{});return task;}};
const digest=async s=>createHash('sha256').update(s).digest('hex');
function mod(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
 const local=id=>{if(id==='cloudflare:workers')return {env};if(id==='./auth'||id==='@/lib/auth')return {requireUser:async req=>{if(!req.headers.get('x-user'))throw new (mod('lib/server.ts').HttpError)('Sign in',401);return {id:req.headers.get('x-user')}},session:async req=>({hash:req.headers.get('x-session')??'session-a'}),digest,randomToken:()=>crypto.randomUUID().replaceAll('-','').repeat(2)};if(id==='@/lib/admin')return {adminIdentity:async()=> 'admin',audit:(actor,action,target)=>stmt('INSERT INTO admin_audit VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,target,Date.now())};if(id==='@/packages/blockchain/config')return {registry:()=>({chainId:84532}),publicClient:()=>rpc};if(id.startsWith('@/')||id.startsWith('.'))return mod((id.startsWith('@/')?id.slice(2):path.resolve(path.dirname(file),id))+(path.extname(id)?'':'.ts'));return require(id);};
 vm.runInNewContext(`(function(require,module,exports){${js}\n})`,{console,crypto,Request,Response,URL,URLSearchParams,Date,Buffer,TextEncoder,TextDecoder,Uint8Array,AbortSignal,setTimeout,fetch:(...args)=>network(...args)})(local,module,module.exports);return module.exports;}
function reset(){sql?.close();sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));cache=new Map();env={DB:db,DISCORD_CLIENT_ID:'123',DISCORD_CLIENT_SECRET:'test-secret'};network=async()=>{throw Error('Unexpected fetch')};for(const u of ['a','b']){sql.prepare("INSERT INTO registrations(user_id,username,email,status,created_at) VALUES(?,?,'','active',1)").run(u,u);sql.prepare('INSERT INTO account_wallets VALUES(?,?,84532,1)').run('wallet-'+u,u);}
 const rules={social:{points:20,cap:40}};sql.prepare("INSERT INTO seasons VALUES('season','Season','active',1,?,?,?,NULL,1)").run(JSON.stringify(rules),Date.now()-10000,Date.now()+1000000);
}
function campaign(mode='game_level',threshold=2){const id=crypto.randomUUID();sql.prepare("INSERT INTO campaigns(id,kind,title,description,url,status,points,min_points,amount_wei,max_recipients,starts_at,ends_at,created_at,verification,target,role_id,threshold) VALUES(?,'social','Quest','Description','','active',100,0,'0',100,?,?,1,?,'12345678901234567','98765432109876543',?)").run(id,Date.now()-1000,Date.now()+100000,mode,threshold);return id;}
function request(body,user='a',session='session-a',method='POST',url='https://game.test/api/campaigns'){return new Request(url,{method,headers:{origin:'https://game.test','content-type':'application/json','x-user':user,'x-session':session},...(method==='POST'?{body:JSON.stringify(body)}:{})});}
test('automatic progress does not award early; repeated verification pays once with season cap',async()=>{reset();const id=campaign();sql.prepare("INSERT INTO players VALUES('a','a',?,0,1,1)").run(JSON.stringify({xp:0}));const route=mod('app/api/campaigns/route.ts');assert.equal((await (await route.POST(request({action:'verify',id}))).json()).verified,false);sql.prepare("UPDATE players SET state=? WHERE user_id='a'").run(JSON.stringify({xp:100}));sql.prepare('UPDATE quest_checks SET checked_at=0').run();for(let n=0;n<3;n++)assert.equal((await route.POST(request({action:'verify',id}))).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,1);assert.equal(sql.prepare('SELECT SUM(points) n FROM season_events').get().n,20);assert.equal(sql.prepare('SELECT points FROM submissions').get().points,100);});
test('manual evidence cannot bypass automatic verification; closed quests refuse checks',async()=>{reset();const id=campaign();const route=mod('app/api/campaigns/route.ts');assert.equal((await route.POST(request({action:'submit',id,evidence:'fake proof'}))).status,400);sql.prepare("UPDATE campaigns SET status='closed'").run();assert.equal((await route.POST(request({action:'verify',id}))).status,409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,0);});
test('Discord checks pending screening, required role and unique account ownership',async()=>{reset();const id=campaign('discord_role'),service=mod('lib/social-quests.ts'),c=await service.quest(id);let member={pending:true,roles:['98765432109876543']};network=async url=>Response.json(url.endsWith('/users/@me')?{id:'55555555555555555',username:'panda'}:member);await assert.rejects(service.verifyDiscord('a',c,'token'));member={roles:[]};await assert.rejects(service.verifyDiscord('a',c,'token'));member={roles:['98765432109876543']};await service.verifyDiscord('a',c,'token');await assert.rejects(service.verifyDiscord('b',c,'token'));assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,1);});
test('Discord outage and not-a-member responses never award points',async()=>{reset();const c=await mod('lib/social-quests.ts').quest(campaign('discord_member'));for(const status of [404,429,503]){network=async url=>url.endsWith('/users/@me')?Response.json({id:'55555555555555555'}):new Response('',{status});await assert.rejects(mod('lib/social-quests.ts').verifyDiscord('a',c,'token'));}assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,0);});
test('OAuth state is session-bound, expiring, single-use and token stays on server',async()=>{reset();const id=campaign('discord_member');const start=await mod('app/api/social/discord/route.ts').POST(request({id}));assert.equal(start.status,200);const auth=new URL((await start.json()).url),state=auth.searchParams.get('state');assert.equal(auth.searchParams.get('scope'),'identify guilds.members.read');const callback=mod('app/api/social/discord/callback/route.ts');const url='https://game.test/api/social/discord/callback?state='+state+'&code=code';let calls=0;network=async url=>{calls++;return Response.json(url.endsWith('/token')?{access_token:'private-token',scope:'identify guilds.members.read'}:url.endsWith('/users/@me')?{id:'55555555555555555'}:{roles:[],pending:false});};const wrong=await callback.GET(request(null,'a','wrong','GET',url));assert.match(wrong.headers.get('location'),/verification=error/);assert.equal(calls,0);const good=await callback.GET(request(null,'a','session-a','GET',url));assert.match(good.headers.get('location'),/verification=success/);assert.equal(calls,3);await callback.GET(request(null,'a','session-a','GET',url));assert.equal(calls,3);assert.equal(sql.prepare('SELECT COUNT(*) n FROM social_oauth_states').get().n,0);assert.ok(!good.headers.get('location').includes('private-token'));});
test('campaign admin saves validated automatic configuration and retains legacy manual defaults',async()=>{reset();const schema=mod('lib/community-config.ts').campaignSchema;const body={kind:'social',title:'Discord quest',description:'Join our community',url:'https://discord.com',points:100,minPoints:0,amountWei:'0',maxRecipients:100,startsAt:Date.now(),endsAt:Date.now()+100000};assert.equal(schema.parse(body).verification,'manual');assert.throws(()=>schema.parse({...body,verification:'discord_member',target:'bad'}));const admin=mod('app/api/admin/route.ts');const r=await admin.POST(request({...body,action:'campaign',verification:'discord_role',target:'12345678901234567',roleId:'98765432109876543',threshold:1}));assert.equal(r.status,200,JSON.stringify(await r.json()));const c=sql.prepare('SELECT * FROM campaigns').get();assert.equal(c.verification,'discord_role');assert.equal(c.role_id,'98765432109876543');});
test('quest checks are rate limited',async()=>{reset();const s=mod('lib/social-quests.ts');for(let i=0;i<12;i++)await s.questLimit('a');await assert.rejects(s.questLimit('a'),e=>e.status===429);});

test('tutorial requires a server claim and late approval cannot pay a closed campaign',async()=>{reset();const id=campaign('tutorial'),svc=mod('lib/social-quests.ts'),c=await svc.quest(id);assert.equal((await svc.verifyInternal('a',c)).verified,false);sql.prepare("INSERT INTO tutorial_rewards VALUES('a',1,1)").run();assert.equal((await svc.verifyInternal('a',c)).verified,true);const second=await svc.quest(campaign('tutorial'));sql.prepare("UPDATE campaigns SET status='closed' WHERE id=?").run(second.id);await assert.rejects(svc.approveQuest('a',second,'proof'));assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,1);});
test('season daily cap is enforced across multiple automatic quests',async()=>{reset();sql.prepare("INSERT INTO players VALUES('a','a',?,0,1,1)").run(JSON.stringify({xp:500}));const svc=mod('lib/social-quests.ts');for(let i=0;i<3;i++)await svc.verifyInternal('a',await svc.quest(campaign()));assert.equal(sql.prepare('SELECT SUM(points) n FROM season_events').get().n,40);assert.equal(sql.prepare('SELECT SUM(points) n FROM submissions').get().n,300);});
test('expired OAuth state is rejected without contacting Discord',async()=>{reset();const id=campaign('discord_member'),r=await mod('app/api/social/discord/route.ts').POST(request({id}));const state=new URL((await r.json()).url).searchParams.get('state');sql.prepare('UPDATE social_oauth_states SET expires_at=1').run();const res=await mod('app/api/social/discord/callback/route.ts').GET(request(null,'a','session-a','GET','https://game.test/api/social/discord/callback?code=test&state='+state));assert.match(res.headers.get('location'),/verification=error/);assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,0);});

test('bulk verification is bounded, idempotent, and rotates through pending quests',async()=>{
 reset();sql.prepare("INSERT INTO players VALUES('a','a',?,0,1,1)").run(JSON.stringify({xp:500}));for(let i=0;i<6;i++)campaign();
 const route=mod('app/api/campaigns/route.ts');const first=await (await route.POST(request({action:'verify_all'}))).json();assert.equal(first.checked,4);assert.equal(first.verified,4);
 const second=await (await route.POST(request({action:'verify_all'}))).json();assert.equal(second.checked,2);assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,6);assert.equal(sql.prepare('SELECT SUM(points) n FROM season_events').get().n,40);
 assert.equal((await route.POST(request({action:'verify_all',wallet:'spoof'}))).status,400);
});
test('server verifies ERC20 balances at finalized block using only the linked wallet',async()=>{
 reset();sql.prepare("UPDATE account_wallets SET address=? WHERE user_id='a'").run('0x'+'1'.repeat(40));const id=campaign('erc20_balance');sql.prepare('UPDATE campaigns SET target=?,requirement_amount=? WHERE id=?').run('0x'+'2'.repeat(40),'1.5',id);
 let balance=1499999n;rpc={getBlock:async args=>{assert.equal(args.blockTag,'finalized');return {number:100n}},readContract:async args=>{assert.equal(args.blockNumber,100n);if(args.functionName==='decimals')return 6;assert.equal(args.args[0],'0x'+'1'.repeat(40));return balance;}};
 const route=mod('app/api/campaigns/route.ts');assert.equal((await (await route.POST(request({action:'verify',id}))).json()).verified,false);balance=1500000n;sql.prepare('UPDATE quest_checks SET checked_at=0').run();assert.equal((await (await route.POST(request({action:'verify',id}))).json()).verified,true);assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,1);
});
test('RPC outages and wrong wallet network never award; native and NFT balances are supported',async()=>{
 reset();const service=mod('lib/quest-web3.ts'),base={verification:'native_balance',chain_id:8453,target:'',requirement_amount:'0.001',token_id:'0'};assert.equal((await service.web3Progress('a',base)).complete,false);
 sql.prepare("UPDATE account_wallets SET address=? WHERE user_id='a'").run('0x'+'1'.repeat(40));rpc={getBlock:async()=>({number:10n}),getBalance:async()=>1000000000000000n,readContract:async args=>{if(args.abi.some(a=>a.name==='balanceOf'&&a.inputs.length===2))assert.equal(args.args[1],42n);return 2n;}};
 assert.equal((await service.web3Progress('a',{...base,chain_id:84532})).complete,true);
 for(const verification of ['erc721_balance','erc1155_balance'])assert.equal((await service.web3Progress('a',{...base,chain_id:84532,verification,target:'0x'+'2'.repeat(40),requirement_amount:'2',token_id:'42'})).complete,true);
 rpc.getBlock=async()=>{throw Error('RPC down')};const id=campaign('native_balance');const result=await mod('lib/quest-verification.ts').verifyAutomatic('a',await mod('lib/social-quests.ts').quest(id));assert.equal(result.status,'error');assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,0);
});
test('linked Discord can be reverified with a bot; absent bot cannot fabricate membership',async()=>{
 reset();sql.prepare("INSERT INTO social_accounts VALUES('a','discord','55555555555555555','tester',1)").run();const id=campaign('discord_role'),c=await mod('lib/social-quests.ts').quest(id),svc=mod('lib/quest-verification.ts');assert.equal((await svc.verifyAutomatic('a',c)).verified,false);
 env.DISCORD_BOT_TOKEN='server-secret';sql.prepare('UPDATE quest_checks SET checked_at=0').run();network=async(url,options)=>{assert.ok(url.endsWith('/members/55555555555555555'));assert.equal(options.headers.Authorization,'Bot server-secret');return Response.json({roles:['98765432109876543'],pending:false});};assert.equal((await svc.verifyAutomatic('a',c)).verified,true);
});
test('scheduled checks award without a browser, exclude banned users, and replay safely',async()=>{
 reset();sql.prepare("INSERT INTO players VALUES('a','a',?,0,1,1)").run(JSON.stringify({xp:500}));sql.prepare("INSERT INTO players VALUES('b','b',?,0,1,1)").run(JSON.stringify({xp:500}));sql.prepare("UPDATE registrations SET status='banned' WHERE user_id='b'").run();campaign();const svc=mod('lib/quest-verification.ts');await svc.runScheduledQuests();await svc.runScheduledQuests();assert.equal(sql.prepare('SELECT COUNT(*) n FROM submissions').get().n,1);assert.equal(sql.prepare('SELECT user_id FROM submissions').get().user_id,'a');
});
