import test from 'node:test';import assert from 'node:assert/strict';import {advance as step,initialState,blocked,WORLD,BUILDINGS,NPCS} from './world.ts';
function advance(s,a,elapsed,now){const n=step(s,a,elapsed,now);return a.type==='attack'&&n.strike&&n.strike.at>now?step(n,{type:'tick'},0,n.strike.at):n}
test('movement normalizes diagonal input and clamps elapsed time',()=>{const s=initialState();const n=advance(s,{type:'move',dx:1,dy:1},90000,2000);assert.ok(Math.hypot(n.x-s.x,n.y-s.y)<=190.001);assert.equal(s.x,WORLD.spawn.x)});
test('world edges and building bases have collisions',()=>{assert.ok(blocked(-1,300));assert.ok(blocked(BUILDINGS[4].x+30,BUILDINGS[4].y+BUILDINGS[4].h-20));assert.ok(!blocked(1100,850))});
test('attacks require proximity and obey cooldown',()=>{const s=initialState();s.monsters[0].x=s.x+30;s.monsters[0].y=s.y;const first=advance(s,{type:'attack'},200,2000);assert.equal(first.monsters[0].hp,35);const second=advance(first,{type:'attack'},20,2020);assert.equal(second.monsters[0].hp,35);const far=advance(initialState(),{type:'attack'},200,2000);assert.equal(far.scrap,0)});
test('quest rewards once, only after kills and returning to NPC',()=>{let s=initialState();s.x=1100;s.y=760;s=advance(s,{type:'interact',target:'scrappy'},0,2000);assert.equal(s.quest,'active');s.questKills=3;s=advance(s,{type:'interact',target:'scrappy'},0,2200);assert.equal(s.scrap,100);s=advance(s,{type:'interact',target:'scrappy'},0,2400);assert.equal(s.scrap,100)});
test('crafting checks location and resources; healing consumes one kit',()=>{let s=initialState();s.scrap=20;s.circuits=2;s.x=NPCS[2].x;s.y=NPCS[2].y;s=advance(s,{type:'craft'},0,2000);assert.equal(s.medkits,3);assert.equal(s.scrap,0);assert.equal(s.circuits,0);s.hp=60;s=advance(s,{type:'heal'},0,2200);assert.equal(s.hp,60);s=advance(s,{type:'tick'},0,3700);assert.equal(s.hp,100);assert.equal(s.medkits,2)});
test('death returns to town and never creates a negative balance',()=>{let s=initialState();s.hp=0;s.scrap=5;s=advance(s,{type:'tick'},0,2000);assert.equal(s.hp,100);assert.equal(s.scrap,0);assert.equal(s.x,WORLD.spawn.x)});

