import {homeAccess} from '@/lib/homestead';
import {z} from 'zod';
import {db,json,fail,identity,sameOrigin,readJson,HttpError} from '@/lib/server';
import {parcels} from '@/packages/game-core/world';
import {footprint} from '@/packages/game-core/parcel-layout';
import {landSnapshot,wallet,validPlacements,decoration,snapshot} from '@/lib/decorations';
export async function GET(req:Request){try{const user=await identity(req),id=Number(new URL(req.url).searchParams.get('id')),parcel=parcels.find(p=>p.id===id);if(!parcel)throw new HttpError('Unknown parcel.',404);const {land,home,canEdit}=await homeAccess(user,id);const reward=await db().prepare('SELECT t.claimed_at FROM tutorial_rewards t JOIN account_wallets w ON w.user_id=t.user_id WHERE w.address=?').bind(land.owner).first<{claimed_at:number}>();const placements=await validPlacements(id,land);const buildings=await db().prepare('SELECT * FROM buildings WHERE parcel=?').bind(id).all();return json({parcel,placements,buildings:buildings.results,canEdit,owner:land?.owner??null,home:{workshop:home.workshop,warehouse:home.warehouse,garden:home.garden},welcomeDecoration:!!reward?.claimed_at});}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const user=await identity(req);const b=z.object({parcel:z.number().int(),itemId:z.number().int().positive(),action:z.enum(['place','remove']),x:z.number().int().default(0),y:z.number().int().default(0),rotation:z.number().int().default(0)}).strict().parse(await readJson(req));const parcel=parcels.find(p=>p.id===b.parcel);if(!parcel)throw new HttpError('Unknown parcel.');const land=await landSnapshot(parcel.id),address=await wallet(user);if(!land||land.owner!==address)throw new HttpError('Only the current land owner can edit.',403);await validPlacements(parcel.id,land);
 if(b.action==='remove'){await db().prepare('DELETE FROM parcel_decorations WHERE item_id=? AND parcel=?').bind(b.itemId,parcel.id).run();return json({ok:true})}
 const item=await decoration(b.itemId),token=await snapshot(item.contract,item.id);if(!token||token.owner!==address)throw new HttpError('Your wallet does not own this decoration.',403);
 let cells;try{cells=footprint(b.x,b.y,item.width,item.height,b.rotation,parcel.width,parcel.height)}catch(e){throw new HttpError((e as Error).message)}
 const old=await db().prepare('SELECT parcel FROM parcel_decorations WHERE item_id=?').bind(item.id).first<{parcel:number}>();if(old&&old.parcel!==parcel.id){await validPlacements(old.parcel,await landSnapshot(old.parcel));if(await db().prepare('SELECT item_id FROM parcel_decorations WHERE item_id=?').bind(item.id).first())throw new HttpError('Remove this NFT from its other parcel first.',409)}
 const buildings=await db().prepare('SELECT x,y FROM buildings WHERE parcel=?').bind(parcel.id).all<{x:number;y:number}>();if(cells.some(c=>buildings.results.some(v=>c.x>=v.x*4&&c.x<v.x*4+4&&c.y>=v.y*4&&c.y<v.y*4+4)))throw new HttpError('This space is occupied by a permanent building.',409);
 const total=await db().prepare('SELECT COUNT(*) n FROM parcel_decorations WHERE parcel=? AND item_id<>?').bind(parcel.id,item.id).first<{n:number}>();if((total?.n??0)>=40)throw new HttpError('Maximum 40 decorations per parcel.');
 try{await db().batch([db().prepare('DELETE FROM parcel_decorations WHERE item_id=?').bind(item.id),db().prepare('INSERT INTO parcel_decorations(item_id,parcel,x,y,rotation,owner,land_version,token_version) SELECT ?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM parcel_decorations WHERE parcel=?)<40 AND NOT EXISTS(SELECT 1 FROM buildings WHERE parcel=? AND x*4<? AND x*4+4>? AND y*4<? AND y*4+4>?)').bind(item.id,parcel.id,b.x,b.y,b.rotation,address,land.version,token.version,parcel.id,parcel.id,b.x+(b.rotation%180?item.height:item.width),b.x,b.y+(b.rotation%180?item.width:item.height),b.y),...cells.map(c=>db().prepare('INSERT INTO decoration_cells(parcel,x,y,item_id) VALUES(?,?,?,?)').bind(parcel.id,c.x,c.y,item.id))]);}catch(e){if(/UNIQUE|FOREIGN KEY/.test(String(e)))throw new HttpError('That space is occupied. Refresh and try again.',409);throw e}return json({ok:true});}catch(e){return fail(e)}}
