import {referralAtRegistration} from './referrals';
import {readJson,db,HttpError,json,runtimeEnv,sameOrigin} from './server';
import {registry,publicClient,networkForChainId} from '@/packages/blockchain/config';
import {createSiweMessage} from 'viem/siwe';
import {isAddress,type Address,type Hex} from 'viem';
import {z} from 'zod';
import {initialState} from '@/packages/game-core/world';
import {defaultGameSettings} from './community-config';

const DAY=86400000;
export const SESSION_IDLE=7*DAY,SESSION_MAX=30*DAY,PROOF_TTL=15*60000;
export type AuthUser={id:string;username:string;role:string;status:string;wallet:{address:Address;chainId:number}};
type Session={hash:string;user_id:string|null;wallet:Address;chain_id:number;expires_at:number;created_at:number};
export function randomToken(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('')}
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),v=>v.toString(16).padStart(2,'0')).join('')}
function sharedDomain(req:Request,kind:string){
 const env=runtimeEnv(),u=new URL(req.url),domain=env.AUTH_COOKIE_DOMAIN;
 const allowed=(env.AUTH_ORIGINS??'').split(',').map(v=>v.trim()).filter(Boolean);
 if(kind!=='session'||u.protocol!=='https:'||!domain||!allowed.includes(u.origin))return '';
 if(domain!=='tpunited.xyz'||!['tpunited.xyz','game.tpunited.xyz'].includes(u.hostname))return '';
 return domain;
}
function cookieName(req:Request,kind:string){return `${secureRequest(req)?sharedDomain(req,kind)?'__Secure-':'__Host-':''}tpu_${kind}`}
function readCookie(req:Request,kind:string){return (req.headers.get('cookie')??'').split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName(req,kind)+'='))?.split('=')[1]??''}
function secureRequest(req:Request){return new URL(req.url).protocol==='https:'}
function setCookie(res:Response,req:Request,kind:string,value:string,ms:number){const domain=sharedDomain(req,kind);res.headers.append('Set-Cookie',`${cookieName(req,kind)}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${Math.max(0,Math.floor(ms/1000))}${secureRequest(req)?'; Secure':''}${domain?`; Domain=${domain}`:''}`)}
function origin(req:Request){sameOrigin(req);const u=new URL(req.url),env=runtimeEnv(),allowed=(env.AUTH_ORIGINS??env.AUTH_ORIGIN??'').split(',').map(v=>v.trim()).filter(Boolean);if(allowed.length&&!allowed.includes(u.origin))throw new HttpError('Login is not available on this domain.',403);if(u.protocol!=='https:'&&!['localhost','127.0.0.1','terminal.local'].includes(u.hostname))throw new HttpError('HTTPS is required.',403);return u}
export async function session(req:Request):Promise<Session|null>{const token=readCookie(req,'session');if(!/^[a-f0-9]{64}$/.test(token))return null;return db().prepare('SELECT * FROM auth_sessions WHERE hash=? AND expires_at>? AND created_at>?').bind(await digest(token),Date.now(),Date.now()-SESSION_MAX).first<Session>()}
export async function currentUser(req:Request):Promise<AuthUser|null>{const s=await session(req);if(!s?.user_id)return null;const r=await db().prepare('SELECT r.user_id,r.username,r.role,r.status,w.address,w.chain_id FROM registrations r JOIN account_wallets w ON w.user_id=r.user_id WHERE r.user_id=? AND w.address=?').bind(s.user_id,s.wallet).first<{user_id:string;username:string;role:string;status:string;address:Address;chain_id:number}>();if(!r)return null;if(r.status==='banned')throw new HttpError('Your account is suspended.',403);if(r.status!=='active')return null;return {id:r.user_id,username:r.username,role:r.role,status:r.status,wallet:{address:r.address,chainId:r.chain_id}}}
export async function requireUser(req:Request){const u=await currentUser(req);if(!u)throw new HttpError('Sign in with your wallet to continue.',401);return u}
export async function me(req:Request){const u=await currentUser(req);if(u){const s=await session(req);return json({authenticated:true,user:u,pendingWallet:null,networkVerified:s?.chain_id===registry(runtimeEnv()).chainId});}const s=await session(req);return json({authenticated:false,user:null,pendingWallet:s&&!s.user_id?s.wallet:null,networkVerified:false});}
async function rateLimit(key:string,max:number){const now=Date.now();const row=await db().prepare('INSERT INTO auth_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<=? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<=? THEN excluded.expires_at ELSE expires_at END RETURNING count').bind(key,now+60000,now,now).first<{count:number}>();if((row?.count??max+1)>max)throw new HttpError('Too many sign-in attempts. Wait a minute and retry.',429)}
export async function nonce(req:Request){const u=origin(req),c=registry(runtimeEnv());const b=z.object({address:z.string().refine(isAddress),chainId:z.literal(c.chainId)}).strict().parse(await readJson(req));const address=b.address.toLowerCase() as Address;await rateLimit('wallet:'+address,10);const ip=req.headers.get('cf-connecting-ip');if(ip)await rateLimit('ip:'+await digest(ip),40);const previous=readCookie(req,'challenge'),browser=/^[a-f0-9]{64}$/.test(previous)?previous:randomToken(),browserHash=await digest(browser),id=randomToken(),now=Date.now(),expires=now+300000;
 const message=createSiweMessage({address,chainId:c.chainId,domain:u.host,scheme:u.protocol.slice(0,-1),uri:u.origin,version:'1',nonce:id,issuedAt:new Date(now),expirationTime:new Date(expires),statement:'Sign in to Trash Panda United. This signature does not authorize payments or token approvals.'});
 await db().batch([db().prepare('DELETE FROM auth_nonces WHERE browser_hash=? OR expires_at<=?').bind(browserHash,now),db().prepare('DELETE FROM auth_sessions WHERE expires_at<=?').bind(now),db().prepare('DELETE FROM auth_limits WHERE expires_at<=?').bind(now),db().prepare('INSERT INTO auth_nonces VALUES(?,?,?,?,?,?)').bind(id,browserHash,address,message,c.chainId,expires)]);const res=json({id,message,chainId:c.chainId});setCookie(res,req,'challenge',browser,300000);return res;
}
// Adopt only the oldest verified legacy wallet. Never grant a second wallet a new user.
async function adoptLegacy(address:Address,chainId:number){let w=await db().prepare('SELECT user_id FROM account_wallets WHERE address=?').bind(address).first<{user_id:string}>();if(w)return w.user_id;const legacy=await db().prepare('SELECT user_id FROM wallets WHERE address=?').bind(address).first<{user_id:string}>();if(!legacy)return null;const first=await db().prepare('SELECT address FROM wallets WHERE user_id=? ORDER BY created_at,address LIMIT 1').bind(legacy.user_id).first<{address:string}>();if(first?.address!==address)throw new HttpError('Use the primary wallet originally verified for this account. Contact support for recovery.',409);
 const existing=await db().prepare('SELECT user_id FROM registrations WHERE user_id=?').bind(legacy.user_id).first();if(!existing){const player=await db().prepare('SELECT username FROM players WHERE user_id=?').bind(legacy.user_id).first<{username:string}>();if(!player)throw new HttpError('Legacy account needs recovery. Contact support.',409);await db().prepare("INSERT INTO registrations(user_id,username,email,status,created_at) VALUES(?,?,'','active',?) ON CONFLICT(user_id) DO NOTHING").bind(legacy.user_id,player.username,Date.now()).run();}
 await db().batch([db().prepare('INSERT INTO account_wallets VALUES(?,?,?,?) ON CONFLICT DO NOTHING').bind(address,legacy.user_id,chainId,Date.now()),db().prepare("UPDATE registrations SET status='active' WHERE user_id=? AND status='pending'").bind(legacy.user_id)]);w=await db().prepare('SELECT user_id FROM account_wallets WHERE address=?').bind(address).first<{user_id:string}>();if(w?.user_id!==legacy.user_id)throw new HttpError('This account already has a primary wallet.',409);return w.user_id;
}
async function configuredRole(userId:string,address:string){const bootstrap=runtimeEnv().AUTH_ADMIN_WALLET?.toLowerCase();if(bootstrap&&isAddress(bootstrap)&&address===bootstrap){await db().batch([db().prepare("INSERT INTO admin_audit(id,actor,action,target,created_at) SELECT ?,?,'bootstrap_admin',?,? WHERE EXISTS(SELECT 1 FROM registrations WHERE user_id=? AND role='USER')").bind(crypto.randomUUID(),userId,userId,Date.now(),userId),db().prepare("UPDATE registrations SET role='ADMIN' WHERE user_id=? AND role='USER'").bind(userId)]);}}
export async function verifyWallet(req:Request){const u=origin(req),c=registry(runtimeEnv());const b=z.object({id:z.string().regex(/^[a-f0-9]{64}$/),address:z.string().refine(isAddress),signature:z.string().regex(/^0x[0-9a-fA-F]+$/).max(20000)}).strict().parse(await readJson(req));const browser=readCookie(req,'challenge');if(!browser)throw new HttpError('Sign-in request expired. Request a new signature.',401);await rateLimit('verify:'+await digest(browser),10);
 const row=await db().prepare('SELECT * FROM auth_nonces WHERE id=? AND browser_hash=? AND address=? AND expires_at>? AND chain_id=?').bind(b.id,await digest(browser),b.address.toLowerCase(),Date.now(),c.chainId).first<{message:string;address:Address}>();if(!row)throw new HttpError('Nonce expired or already used. Request a new signature.',401);
 const valid=await publicClient(c).verifySiweMessage({address:row.address,message:row.message,signature:b.signature as Hex,nonce:b.id,domain:u.host,scheme:u.protocol.slice(0,-1),time:new Date()});if(!valid)throw new HttpError('Invalid wallet signature.',401);
 const linked=await db().prepare('SELECT chain_id FROM account_wallets WHERE address=? UNION ALL SELECT chain_id FROM wallets WHERE address=? LIMIT 1').bind(row.address,row.address).first<{chain_id:number}>();
 // A contract wallet may have different owners on different networks. Require both chains to accept the proof during migration.
 if(linked&&linked.chain_id!==c.chainId){const old=registry({...runtimeEnv(),BLOCKCHAIN_NETWORK:networkForChainId(linked.chain_id),BASE_RPC_URL:undefined,BASE_RPC_FALLBACK:undefined});if(old.chainId!==linked.chain_id||!await publicClient(old).verifyMessage({address:row.address,message:row.message,signature:b.signature as Hex}))throw new HttpError('Wallet ownership differs across networks. Contact support before migrating this account.',403);}
 const consumed=await db().prepare('DELETE FROM auth_nonces WHERE id=? AND expires_at>? RETURNING id').bind(b.id,Date.now()).first();if(!consumed)throw new HttpError('Nonce expired or already used.',401);
 const userId=await adoptLegacy(row.address,c.chainId);if(userId){const status=await db().prepare('SELECT status FROM registrations WHERE user_id=?').bind(userId).first<{status:string}>();if(status?.status==='banned')throw new HttpError('Your account is suspended.',403);await configuredRole(userId,row.address);}
 const token=randomToken(),now=Date.now(),duration=userId?SESSION_IDLE:PROOF_TTL;
 await db().batch([db().prepare('UPDATE account_wallets SET chain_id=? WHERE user_id=? AND address=?').bind(c.chainId,userId,row.address),db().prepare('DELETE FROM auth_sessions WHERE wallet=? OR user_id=?').bind(row.address,userId),db().prepare('INSERT INTO auth_sessions VALUES(?,?,?,?,?,?)').bind(await digest(token),userId,row.address,c.chainId,now+duration,now)]);
 const res=json({authenticated:!!userId,registrationRequired:!userId});setCookie(res,req,'session',token,userId?SESSION_MAX:PROOF_TTL);setCookie(res,req,'challenge','',0);return res;
}
export async function register(req:Request){origin(req);const b=z.object({username:z.string().trim().regex(/^[a-zA-Z0-9_]{3,20}$/).transform(v=>v.toLowerCase()),consent:z.literal(true),referral:z.string().regex(/^[a-f0-9]{32}$/).optional()}).strict().parse(await readJson(req));const s=await session(req);if(!s)throw new HttpError('Sign a wallet message before registering.',401);if(s.user_id)return me(req);if(s.chain_id!==registry(runtimeEnv()).chainId)throw new HttpError('Network changed. Sign in again before registering.',409);const settings=await db().prepare("SELECT value FROM site_content WHERE key='game'").first<{value:string}>();if(!(settings?JSON.parse(settings.value):defaultGameSettings).registrationOpen)throw new HttpError('Registration is temporarily closed.',403);
 if(b.referral&&!await db().prepare("SELECT c.code FROM referral_codes c JOIN registrations r ON r.user_id=c.user_id WHERE c.code=? AND r.status='active'").bind(b.referral).first())throw new HttpError('Referral code is unavailable. Remove it or ask for a new invitation.');
 const now=Date.now(),id=crypto.randomUUID();const taken=await db().prepare('SELECT user_id FROM players WHERE username=? COLLATE NOCASE UNION SELECT user_id FROM registrations WHERE username=? COLLATE NOCASE').bind(b.username,b.username).first();if(taken)throw new HttpError('Username is already taken.',409);
 try{await db().batch([
 db().prepare("INSERT INTO registrations(user_id,username,email,status,role,consented_at,created_at) SELECT ?,?,'','active','USER',?,? WHERE EXISTS(SELECT 1 FROM auth_sessions WHERE hash=? AND user_id IS NULL AND expires_at>?)").bind(id,b.username,now,now,s.hash,now),
 db().prepare('INSERT INTO account_wallets SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM registrations WHERE user_id=?)').bind(s.wallet,id,s.chain_id,now,id),
 db().prepare('INSERT INTO players(user_id,username,state,revision,updated_at,created_at) SELECT ?,?,?,0,?,? WHERE EXISTS(SELECT 1 FROM registrations WHERE user_id=?)').bind(id,b.username,JSON.stringify(initialState()),now,now,id),
 db().prepare('UPDATE auth_sessions SET user_id=?,expires_at=? WHERE hash=? AND user_id IS NULL AND EXISTS(SELECT 1 FROM registrations WHERE user_id=?)').bind(id,now+SESSION_IDLE,s.hash,id)
 ,...(b.referral?[referralAtRegistration(id,b.referral,now)]:[])
 ]);}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError('Username or wallet is already registered.',409);throw e;}
 const saved=await session(req);if(!saved?.user_id)throw new HttpError('Registration expired. Sign in again.',401);await configuredRole(saved.user_id,s.wallet);const res=await me(req);setCookie(res,req,'session',readCookie(req,'session'),s.created_at+SESSION_MAX-Date.now());return res;
}
export async function refresh(req:Request){origin(req);const s=await session(req);if(!s?.user_id||!await currentUser(req))throw new HttpError('Session expired. Sign in again.',401);const expiry=Math.min(Date.now()+SESSION_IDLE,s.created_at+SESSION_MAX);const renewed=await db().prepare('UPDATE auth_sessions SET expires_at=? WHERE hash=? AND expires_at>? RETURNING hash').bind(expiry,s.hash,Date.now()).first();if(!renewed)throw new HttpError('Session expired. Sign in again.',401);return me(req);}
export async function logout(req:Request){origin(req);const token=readCookie(req,'session');if(token)await db().prepare('DELETE FROM auth_sessions WHERE hash=?').bind(await digest(token)).run();const browser=readCookie(req,'challenge');if(browser)await db().prepare('DELETE FROM auth_nonces WHERE browser_hash=?').bind(await digest(browser)).run();const res=json({authenticated:false,user:null});setCookie(res,req,'session','',0);setCookie(res,req,'challenge','',0);return res;}
