import {isEquipmentArt} from '@/packages/game-core/equipment-art';
import {z} from 'zod';
import {BaseError,ContractFunctionRevertedError,parseAbi,isAddress,type Address} from 'viem';
import {db,runtimeEnv,HttpError} from './server';
import {registry,publicRegistry,publicClient} from '@/packages/blockchain/config';
import type {GameState,NftGear} from '@/packages/game-core/world';
export const nftAbi=parseAbi(['function ownerOf(uint256 id) view returns(address)','function mint(address to,uint256 id)','function hasRole(bytes32 role,address account) view returns(bool)','function grantRole(bytes32 role,address account)','function name() view returns(string)','function tokenURI(uint256 id) view returns(string)','function supportsInterface(bytes4 interfaceId) view returns(bool)']);
export const itemSchema=z.object({name:z.string().trim().min(3).max(80),description:z.string().trim().min(5).max(1000),image:z.string().max(500).refine(v=>isEquipmentArt(v)||/^\/api\/item-art\/[a-f0-9-]{36}$/.test(v)||(/^https:\/\//.test(v)&&!!URL.canParse(v))),slot:z.enum(['weapon','armor']),rarity:z.enum(['common','uncommon','rare','epic','legendary','mythic']),damage:z.number().int().min(0).max(100),armor:z.number().int().min(0).max(20),minLevel:z.number().int().min(1).max(100)}).refine(v=>v.slot==='weapon'?v.damage>0&&v.armor===0:v.armor>0&&v.damage===0,{message:'Weapons need damage; armor needs defense.'});
export type NftItem={id:number;name:string;description:string;image:string;slot:'weapon'|'armor';rarity:NftGear['rarity'];damage:number;armor:number;min_level:number;status:string;chain_id:number;contract:Address};
export async function collection(isPublic=false){const c=(isPublic?publicRegistry:registry)(runtimeEnv());const row=await db().prepare('SELECT value FROM site_content WHERE key=?').bind('nft_collection_'+c.chainId).first<{value:string}>();if(row){const address=JSON.parse(row.value).address;if(isAddress(address))c.assets=address;}return c}
export async function owned(item:NftItem,address:string){const c=await collection();if(c.chainId!==item.chain_id||c.assets?.toLowerCase()!==item.contract.toLowerCase())return false;try{return (await publicClient(c).readContract({address:item.contract,abi:nftAbi,functionName:'ownerOf',args:[BigInt(item.id)]})).toLowerCase()===address.toLowerCase()}catch(e){if(e instanceof BaseError&&e.walk(x=>x instanceof ContractFunctionRevertedError) instanceof ContractFunctionRevertedError)return false;throw e}}
export async function walletFor(user:string){const w=await db().prepare('SELECT address,chain_id FROM account_wallets WHERE user_id=?').bind(user).first<{address:string;chain_id:number}>();if(!w)throw new HttpError('Connect your registered wallet.',403);return w}
export async function syncItem(user:string,id:number){const item=await db().prepare("SELECT * FROM nft_items WHERE id=? AND status='published'").bind(id).first<NftItem>();if(!item)throw new HttpError('Published item not found.',404);const w=await walletFor(user);if(w.chain_id!==item.chain_id||!await owned(item,w.address))throw new HttpError('This wallet does not own this NFT on the selected network.',403);const count=await db().prepare('SELECT COUNT(*) n FROM nft_holdings WHERE user_id=? AND item_id<>?').bind(user,id).first<{n:number}>();if(count!.n>=40)throw new HttpError('NFT stash is full. Remove an imported item first.',409);await db().prepare('INSERT INTO nft_holdings(item_id,user_id,checked_at) VALUES(?,?,?) ON CONFLICT(item_id) DO UPDATE SET user_id=excluded.user_id,checked_at=excluded.checked_at').bind(id,user,Date.now()).run();}
export function toGear(i:NftItem):NftGear{return {id:'nft-'+i.id,tokenId:i.id,name:i.name,image:i.image,slot:i.slot,rarity:i.rarity,damage:i.damage,armor:i.armor,minLevel:i.min_level}}
// Never trust saved NFT stats. Rebuild them from published definitions and live ownership.
export async function hydrateNfts(user:string,state:GameState,target?:string){state.nftGear=[];const ids=[...Object.values(state.equipment??{}),target].filter((id):id is string=>!!id?.startsWith('nft-'));if(!ids.length)return state;const w=await walletFor(user);const rows=await db().prepare("SELECT i.* FROM nft_items i JOIN nft_holdings h ON h.item_id=i.id WHERE h.user_id=? AND i.status='published' LIMIT 40").bind(user).all<NftItem>();for(const item of rows.results){if(ids.includes('nft-'+item.id)&&w.chain_id===item.chain_id&&await owned(item,w.address))state.nftGear.push(toGear(item));}for(const slot of ['weapon','armor'] as const){const id=state.equipment?.[slot];if(id?.startsWith('nft-')&&!state.nftGear.some(i=>i.id===id))delete state.equipment?.[slot];}return state}
