import {db,HttpError,runtimeEnv} from './server';
import {award} from './leaderboard';
import {internalProgress,discordMemberMatches,type QuestRule} from './social-rules';
export type Quest=QuestRule&{id:string;kind:string;points:number;starts_at:number;ends_at:number;status:string};
export function discordReady(){const e=runtimeEnv();return !!(e.DISCORD_CLIENT_ID&&e.DISCORD_CLIENT_SECRET);}
export async function quest(id:string){const c=await db().prepare("SELECT * FROM campaigns WHERE id=? AND kind='social' AND status='active' AND starts_at<=? AND ends_at>?").bind(id,Date.now(),Date.now()).first<Quest>();if(!c)throw new HttpError('This quest is not open.',409);return c;}
export async function questLimit(user:string){const now=Date.now();const r=await db().prepare('INSERT INTO auth_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<=? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<=? THEN excluded.expires_at ELSE expires_at END RETURNING count').bind('social:'+user,now+60000,now,now).first<{count:number}>();if(!r||r.count>12)throw new HttpError('Too many checks. Wait one minute before retrying.',429);}
export async function approveQuest(user:string,c:Quest,evidence:string){
 const old=await db().prepare('SELECT id FROM submissions WHERE campaign_id=? AND user_id=?').bind(c.id,user).first<{id:string}>();const id=old?.id??crypto.randomUUID(),now=Date.now();
 const result=await db().batch([
 db().prepare("INSERT INTO submissions(id,campaign_id,user_id,evidence,status,points,note,created_at) SELECT ?,?,?,?,'approved',?,'Automatically verified',? WHERE EXISTS(SELECT 1 FROM campaigns WHERE id=? AND status='active' AND starts_at<=? AND ends_at>?) AND EXISTS(SELECT 1 FROM registrations WHERE user_id=? AND status='active') ON CONFLICT(campaign_id,user_id) DO UPDATE SET evidence=excluded.evidence,status='approved',points=excluded.points,note=excluded.note WHERE submissions.status IN ('pending','rejected')").bind(id,c.id,user,evidence,c.points,now,c.id,now,now,user),
 award(user,'social','social:'+id,now,'changes()>0'),
 db().prepare("INSERT OR IGNORE INTO admin_audit(id,actor,action,target,created_at) SELECT ?,?,'auto_verify_social',?,? WHERE EXISTS(SELECT 1 FROM submissions WHERE id=? AND status='approved')").bind('auto-social:'+id,user,id,now,id)
 ]);
 if(!result[0].meta.changes){const done=await db().prepare("SELECT id FROM submissions WHERE campaign_id=? AND user_id=? AND status='approved'").bind(c.id,user).first();if(!done)throw new HttpError('Quest closed during verification. No points were awarded.',409);}
}
export async function progressFor(user:string,c:Quest){const p=await db().prepare('SELECT state FROM players WHERE user_id=?').bind(user).first<{state:string}>();const t=await db().prepare('SELECT claimed_at FROM tutorial_rewards WHERE user_id=?').bind(user).first<{claimed_at:number}>();return internalProgress(c,p?JSON.parse(p.state):null,!!t?.claimed_at);}
export async function verifyInternal(user:string,c:Quest){const progress=await progressFor(user,c);if(!progress)throw new HttpError('Use the configured verification method.');if(!progress.complete)return {verified:false,progress,message:'Keep playing to meet this requirement.'};await approveQuest(user,c,JSON.stringify({method:c.verification,...progress}));return {verified:true,progress,message:'Quest verified. Community points awarded.'};}
export async function discordFetch(path:string,token:string){let r:Response;try{r=await fetch('https://discord.com/api/v10'+path,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000)});}catch{throw new HttpError('Discord is temporarily unavailable. Retry verification.',503);}if(r.status===404)return null;if(r.status===429)throw new HttpError('Discord is busy. Wait a minute and retry.',429);if(!r.ok)throw new HttpError('Discord verification failed. Reconnect and retry.',503);return r.json() as Promise<{id?:string;username?:string;pending?:boolean;roles?:string[]}>;}
export async function verifyDiscord(user:string,c:Quest,token:string){
 const profile=await discordFetch('/users/@me',token);if(!profile?.id||!/^\d{17,20}$/.test(profile.id))throw new HttpError('Discord did not confirm your identity.',503);
 const linked=await db().prepare("SELECT external_id FROM social_accounts WHERE user_id=? AND provider='discord'").bind(user).first<{external_id:string}>();if(linked&&linked.external_id!==profile.id)throw new HttpError('Use the Discord account already linked to this player.',409);
 try{await db().prepare("INSERT INTO social_accounts(user_id,provider,external_id,display_name,verified_at) VALUES(?,'discord',?,?,?) ON CONFLICT(user_id,provider) DO UPDATE SET display_name=excluded.display_name,verified_at=excluded.verified_at WHERE social_accounts.external_id=excluded.external_id").bind(user,profile.id,(profile.username??'Discord user').slice(0,80),Date.now()).run();}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError('This Discord account is linked to another player.',409);throw e;}
 const confirmed=await db().prepare("SELECT external_id FROM social_accounts WHERE user_id=? AND provider='discord'").bind(user).first<{external_id:string}>();if(confirmed?.external_id!==profile.id)throw new HttpError('Discord account changed during verification. Retry with your linked account.',409);
 const member=await discordFetch('/users/@me/guilds/'+c.target+'/member',token);if(!member||!discordMemberMatches(c,member))throw new HttpError('Join the server, finish its membership screening and obtain the required role, then verify again.',409);
 await approveQuest(user,c,JSON.stringify({method:c.verification,discord:profile.id,guild:c.target,role:c.role_id,verifiedAt:Date.now()}));
}
