import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,uniqueIndex,primaryKey,check} from 'drizzle-orm/sqlite-core';
export const players=sqliteTable('players',{userId:text('user_id').primaryKey().references(()=>registrations.userId),username:text('username').notNull().unique(),state:text('state').notNull(),revision:integer('revision').notNull().default(0),updatedAt:integer('updated_at').notNull(),createdAt:integer('created_at').notNull()},t=>[index('players_updated_idx').on(t.updatedAt)]);
export const wallets=sqliteTable('wallets',{address:text('address').primaryKey(),userId:text('user_id').notNull(),chainId:integer('chain_id').notNull(),createdAt:integer('created_at').notNull()},t=>[index('wallet_user_idx').on(t.userId)]);
export const nonces=sqliteTable('nonces',{id:text('id').primaryKey(),userId:text('user_id').notNull(),address:text('address').notNull(),message:text('message').notNull(),expiresAt:integer('expires_at').notNull()});
export const chat=sqliteTable('chat',{id:text('id').primaryKey(),userId:text('user_id').notNull(),username:text('username').notNull(),message:text('message').notNull(),createdAt:integer('created_at').notNull()},t=>[index('chat_time_idx').on(t.createdAt),index('chat_user_time').on(t.userId,t.createdAt)]);
export const economy=sqliteTable('economy',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),amount:integer('amount').notNull(),createdAt:integer('created_at').notNull()},t=>[index('economy_time_idx').on(t.createdAt),index('economy_user_idx').on(t.userId)]);
export const landProjection=sqliteTable('land_projection',{id:integer('id').primaryKey(),chainId:integer('chain_id').notNull(),contract:text('contract').notNull(),owner:text('owner').notNull(),block:integer('block').notNull(),tx:text('tx').notNull()});
export const chainEvents=sqliteTable('chain_events',{id:text('id').primaryKey(),chainId:integer('chain_id').notNull(),contract:text('contract').notNull(),tx:text('tx').notNull(),logIndex:integer('log_index').notNull(),block:integer('block').notNull(),blockHash:text('block_hash').notNull()},t=>[uniqueIndex('event_unique_idx').on(t.chainId,t.contract,t.tx,t.logIndex)]);
export const buildings=sqliteTable('buildings',{id:text('id').primaryKey(),parcel:integer('parcel').notNull(),x:integer('x').notNull(),y:integer('y').notNull(),rotation:integer('rotation').notNull(),type:text('type').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('building_cell_idx').on(t.parcel,t.x,t.y)]);
export const syncState=sqliteTable('sync_state',{key:text('key').primaryKey(),block:integer('block').notNull(),blockHash:text('block_hash').notNull(),lease:integer('lease').notNull().default(0)});
export const checkpoints=sqliteTable('checkpoints',{key:text('key').primaryKey(),block:integer('block').notNull(),hash:text('hash').notNull(),lockedUntil:integer('locked_until').notNull().default(0)});
export const registrations=sqliteTable('registrations',{userId:text('user_id').primaryKey(),username:text('username').notNull().unique(),email:text('email').notNull(),status:text('status').notNull().default('pending'),role:text('role').notNull().default('USER'),consentedAt:integer('consented_at'),createdAt:integer('created_at').notNull()});
export const siteContent=sqliteTable('site_content',{key:text('key').primaryKey(),value:text('value').notNull(),revision:integer('revision').notNull().default(1),updatedAt:integer('updated_at').notNull()});
export const announcements=sqliteTable('announcements',{id:text('id').primaryKey(),title:text('title').notNull(),body:text('body').notNull(),active:integer('active').notNull().default(0),createdAt:integer('created_at').notNull()});
export const campaigns=sqliteTable('campaigns',{id:text('id').primaryKey(),kind:text('kind').notNull(),title:text('title').notNull(),description:text('description').notNull(),url:text('url').notNull().default(''),status:text('status').notNull().default('draft'),points:integer('points').notNull().default(0),minPoints:integer('min_points').notNull().default(0),amountWei:text('amount_wei').notNull().default('0'),maxRecipients:integer('max_recipients').notNull().default(100),startsAt:integer('starts_at').notNull(),endsAt:integer('ends_at').notNull(),createdAt:integer('created_at').notNull()});
export const submissions=sqliteTable('submissions',{id:text('id').primaryKey(),campaignId:text('campaign_id').notNull(),userId:text('user_id').notNull(),evidence:text('evidence').notNull(),status:text('status').notNull().default('pending'),points:integer('points').notNull(),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('submission_once').on(t.campaignId,t.userId)]);
export const allocations=sqliteTable('allocations',{id:text('id').primaryKey(),campaignId:text('campaign_id').notNull(),userId:text('user_id').notNull(),wallet:text('wallet').notNull(),amountWei:text('amount_wei').notNull(),status:text('status').notNull().default('eligible'),txHash:text('tx_hash'),payer:text('payer'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('allocation_once').on(t.campaignId,t.userId),uniqueIndex('allocation_tx_once').on(t.txHash)]);
export const adminAudit=sqliteTable('admin_audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),createdAt:integer('created_at').notNull()});

// Canonical one-to-one wallet. The old wallets table is read-only migration history.
export const accountWallets=sqliteTable('account_wallets',{address:text('address').primaryKey(),userId:text('user_id').notNull().references(()=>registrations.userId),chainId:integer('chain_id').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('account_wallet_user_once').on(t.userId)]);
export const authSessions=sqliteTable('auth_sessions',{hash:text('hash').primaryKey(),userId:text('user_id').references(()=>registrations.userId),wallet:text('wallet').notNull(),chainId:integer('chain_id').notNull(),expiresAt:integer('expires_at').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('session_user_once').on(t.userId),uniqueIndex('session_wallet_once').on(t.wallet),index('session_expiry').on(t.expiresAt)]);
export const authNonces=sqliteTable('auth_nonces',{id:text('id').primaryKey(),browserHash:text('browser_hash').notNull(),address:text('address').notNull(),message:text('message').notNull(),chainId:integer('chain_id').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('nonce_browser').on(t.browserHash),index('nonce_expiry').on(t.expiresAt)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('auth_limit_expiry').on(t.expiresAt)]);

export const seasons=sqliteTable('seasons',{id:text('id').primaryKey(),title:text('title').notNull(),status:text('status').notNull().default('draft'),activeSlot:integer('active_slot'),rules:text('rules').notNull(),startsAt:integer('starts_at').notNull(),endsAt:integer('ends_at').notNull(),frozenAt:integer('frozen_at'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('season_active_once').on(t.activeSlot)]);
export const seasonEvents=sqliteTable('season_events',{id:text('id').primaryKey(),seasonId:text('season_id').notNull().references(()=>seasons.id),userId:text('user_id').notNull().references(()=>registrations.userId),source:text('source').notNull(),category:text('category').notNull(),day:text('day').notNull(),points:integer('points').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('season_event_once').on(t.seasonId,t.userId,t.source),index('season_score_lookup').on(t.seasonId,t.userId,t.day,t.category)]);
export const seasonExclusions=sqliteTable('season_exclusions',{id:text('id').primaryKey(),seasonId:text('season_id').notNull().references(()=>seasons.id),userId:text('user_id').notNull().references(()=>registrations.userId),reason:text('reason').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('season_exclude_once').on(t.seasonId,t.userId)]);
export const seasonFinal=sqliteTable('season_final',{id:text('id').primaryKey(),seasonId:text('season_id').notNull().references(()=>seasons.id),userId:text('user_id').notNull().references(()=>registrations.userId),username:text('username').notNull(),wallet:text('wallet').notNull(),rank:integer('rank').notNull(),points:integer('points').notNull(),activeDays:integer('active_days').notNull(),eligible:integer('eligible').notNull(),share:text('share').notNull()},t=>[uniqueIndex('season_final_once').on(t.seasonId,t.userId)]);

export const nftItems=sqliteTable('nft_items',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull(),description:text('description').notNull(),image:text('image').notNull(),slot:text('slot').notNull(),rarity:text('rarity').notNull(),damage:integer('damage').notNull(),armor:integer('armor').notNull(),minLevel:integer('min_level').notNull(),status:text('status').notNull().default('draft'),chainId:integer('chain_id').notNull(),contract:text('contract').notNull(),createdAt:integer('created_at').notNull()});
export const nftHoldings=sqliteTable('nft_holdings',{itemId:integer('item_id').primaryKey().references(()=>nftItems.id),userId:text('user_id').notNull().references(()=>registrations.userId),checkedAt:integer('checked_at').notNull()},t=>[index('nft_holder').on(t.userId)]);

export const supportTickets=sqliteTable('support_tickets',{id:integer('id').primaryKey({autoIncrement:true}),userId:text('user_id').notNull().references(()=>registrations.userId),kind:text('kind').notNull(),category:text('category').notNull(),title:text('title').notNull(),description:text('description').notNull(),steps:text('steps').notNull().default(''),expected:text('expected').notNull().default(''),actual:text('actual').notNull().default(''),context:text('context').notNull().default('{}'),status:text('status').notNull().default('open'),priority:text('priority').notNull().default('normal'),assignedTo:text('assigned_to').references(()=>registrations.userId),revision:integer('revision').notNull().default(0),lastWrite:text('last_write').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('support_owner_updated').on(t.userId,t.updatedAt),index('support_status_updated').on(t.status,t.updatedAt)]);
export const supportMessages=sqliteTable('support_messages',{id:integer('id').primaryKey({autoIncrement:true}),ticketId:integer('ticket_id').notNull().references(()=>supportTickets.id),authorId:text('author_id').notNull().references(()=>registrations.userId),staff:integer('staff').notNull(),internal:integer('internal').notNull().default(0),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('support_thread').on(t.ticketId,t.id)]);
export const supportFiles=sqliteTable('support_files',{id:text('id').primaryKey(),ticketId:integer('ticket_id').notNull().references(()=>supportTickets.id),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()},t=>[index('support_files_ticket').on(t.ticketId)]);

export const founderInterest=sqliteTable('founder_interest',{userId:text('user_id').primaryKey().references(()=>registrations.userId),preference:text('preference').notNull(),createdAt:integer('created_at').notNull()});
export const referralCodes=sqliteTable('referral_codes',{userId:text('user_id').primaryKey().references(()=>registrations.userId),code:text('code').notNull()},t=>[uniqueIndex('referral_code_once').on(t.code)]);
export const referrals=sqliteTable('referrals',{userId:text('user_id').primaryKey().references(()=>registrations.userId),referrerId:text('referrer_id').notNull().references(()=>registrations.userId),status:text('status').notNull().default('pending'),seasonId:text('season_id').references(()=>seasons.id),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull(),reviewedAt:integer('reviewed_at')},t=>[index('referral_referrer').on(t.referrerId,t.status,t.seasonId)]);

export const decorationItems=sqliteTable('decoration_items',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull(),description:text('description').notNull(),image:text('image').notNull(),rarity:text('rarity').notNull(),width:integer('width').notNull(),height:integer('height').notNull(),status:text('status').notNull().default('draft'),chainId:integer('chain_id').notNull(),contract:text('contract').notNull(),createdAt:integer('created_at').notNull()});
export const parcelDecorations=sqliteTable('parcel_decorations',{itemId:integer('item_id').primaryKey().references(()=>decorationItems.id),parcel:integer('parcel').notNull(),x:integer('x').notNull(),y:integer('y').notNull(),rotation:integer('rotation').notNull(),owner:text('owner').notNull(),landVersion:text('land_version').notNull(),tokenVersion:text('token_version').notNull()},t=>[index('decor_parcel_idx').on(t.parcel)]);
export const decorationCells=sqliteTable('decoration_cells',{parcel:integer('parcel').notNull(),x:integer('x').notNull(),y:integer('y').notNull(),itemId:integer('item_id').notNull().references(()=>parcelDecorations.itemId,{onDelete:'cascade'})},t=>[uniqueIndex('decor_cell_once').on(t.parcel,t.x,t.y),index('decor_cell_item').on(t.itemId)]);

export const parcelHomes=sqliteTable('parcel_homes',{parcel:integer('parcel').primaryKey(),owner:text('owner').notNull(),version:text('version').notNull(),visibility:text('visibility').notNull().default('private'),guests:text('guests').notNull().default('[]'),workshop:integer('workshop').notNull().default(0),warehouse:integer('warehouse').notNull().default(0),garden:integer('garden').notNull().default(0),harvestAt:integer('harvest_at').notNull().default(0),revision:integer('revision').notNull().default(0)});
export const homesteadVaults=sqliteTable('homestead_vaults',{userId:text('user_id').primaryKey().references(()=>registrations.userId),scrap:integer('scrap').notNull().default(0)});
export const tutorialRewards=sqliteTable('tutorial_rewards',{userId:text('user_id').primaryKey().references(()=>registrations.userId),visitedAt:integer('visited_at').notNull().default(0),claimedAt:integer('claimed_at').notNull().default(0)});

export const parcelPresence=sqliteTable('parcel_presence',{userId:text('user_id').primaryKey().references(()=>registrations.userId),parcel:integer('parcel').notNull(),version:text('version').notNull(),x:integer('x').notNull(),y:integer('y').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('parcel_presence_recent').on(t.parcel,t.updatedAt)]);
export const parcelMessages=sqliteTable('parcel_messages',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>registrations.userId),parcel:integer('parcel').notNull(),version:text('version').notNull(),message:text('message').notNull(),createdAt:integer('created_at').notNull()},t=>[index('parcel_messages_recent').on(t.parcel,t.createdAt),index('parcel_messages_sender').on(t.userId,t.createdAt)]);


export const legacyVisits=sqliteTable('legacy_visits',{visitor:text('visitor').notNull(),owner:text('owner').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.visitor,t.owner]}),index('legacy_visits_owner').on(t.owner),check('legacy_no_self',sql`${t.visitor} <> ${t.owner}`)]);
