import fs from 'node:fs';import {createPublicClient,createWalletClient,http,keccak256,toHex,parseEther,isAddress} from 'viem';import {privateKeyToAccount} from 'viem/accounts';import {base,baseSepolia} from 'viem/chains';
const main=process.env.BLOCKCHAIN_NETWORK==='base-mainnet';if(main&&process.env.CONFIRM_MAINNET_DEPLOY!=='I_HAVE_REVIEWED_THE_CONTRACTS')throw Error('Mainnet guard: explicit reviewed deployment confirmation required.');const chain=main?base:baseSepolia;
if(!process.env.DEPLOYER_PRIVATE_KEY)throw Error('Missing DEPLOYER_PRIVATE_KEY. Set it privately in your local environment. Never send a private key in chat.');const account=privateKeyToAccount(process.env.DEPLOYER_PRIVATE_KEY);const treasury=process.env.TREASURY_ADDRESS;if(!treasury||!isAddress(treasury))throw Error('Set TREASURY_ADDRESS to your treasury wallet.');const rpcUrl=process.env.BASE_RPC_URL||chain.rpcUrls.default.http[0];const rpc=createPublicClient({chain,transport:http(rpcUrl)});if(await rpc.getChainId()!==chain.id)throw Error('RPC chain mismatch.');const wallet=createWalletClient({account,chain,transport:http(rpcUrl)});const filename=`deployments/${main?'base-mainnet':'base-sepolia'}.json`;let result={network:chain.name,chainId:chain.id,deployedAt:null,deployer:account.address,version:'0.1.0',contracts:{},configured:false};if(fs.existsSync(filename)){const old=JSON.parse(fs.readFileSync(filename));if(Object.keys(old.contracts??{}).length){if(old.deployer?.toLowerCase()!==account.address.toLowerCase()||old.chainId!==chain.id)throw Error('Existing deployment identity mismatch.');result=old;}}
const persist=()=>{fs.writeFileSync(filename+'.tmp',JSON.stringify(result,null,2));fs.renameSync(filename+'.tmp',filename)};
async function deploy(name,args){const artifact=JSON.parse(fs.readFileSync(`packages/contracts/artifacts/${name}.json`));if(result.contracts[name]){const code=await rpc.getCode({address:result.contracts[name].address});if(!code||code==='0x')throw Error('Recorded contract has no code. Inspect deployment before proceeding.');return {address:result.contracts[name].address,abi:artifact.abi}}const tx=await wallet.deployContract({...artifact,args});console.log(`Submitted ${name}: ${tx}`);const receipt=await rpc.waitForTransactionReceipt({hash:tx,confirmations:2});if(receipt.status!=='success'||!receipt.contractAddress)throw Error(`Deployment failed: ${name}`);result.contracts[name]={address:receipt.contractAddress,deploymentTx:tx,blockNumber:Number(receipt.blockNumber),version:'0.1.0'};persist();return {address:receipt.contractAddress,abi:artifact.abi}}
async function write(c,functionName,args){const {request}=await rpc.simulateContract({...c,functionName,args,account});const hash=await wallet.writeContract(request);const receipt=await rpc.waitForTransactionReceipt({hash,confirmations:2});if(receipt.status!=='success')throw Error(`${functionName} failed`)}
const metadata=process.env.METADATA_BASE_URL;if(!metadata?.startsWith('https://'))throw Error('Set a trusted HTTPS METADATA_BASE_URL before deployment.');const land=await deploy('TrashPandaLand',[account.address,100n,metadata+'/land/']);const assets=await deploy('TrashPandaAssets',[account.address,metadata+'/assets/']);const router=await deploy('TrashPandaPaymentRouter',[account.address,land.address,treasury]);const market=await deploy('TrashPandaMarketplace',[account.address,treasury,BigInt(process.env.MARKETPLACE_FEE_BPS||250)]);
if(!result.configured){await write(land,'grantRole',[keccak256(toHex('MINTER_ROLE')),router.address]);await write(market,'setAsset',[land.address,true]);await write(market,'setAsset',[assets.address,true]);if(process.env.PAYMENT_TOKEN){if(!isAddress(process.env.PAYMENT_TOKEN))throw Error('Invalid PAYMENT_TOKEN');await write(router,'setCurrency',[process.env.PAYMENT_TOKEN,true]);await write(market,'setCurrency',[process.env.PAYMENT_TOKEN,true]);}result.configured=true;persist();}
if(!main&&process.env.SEED_TESTNET==='true'){for(let id=1;id<=60;id++){try{await rpc.readContract({...land,functionName:'ownerOf',args:[BigInt(id)]});continue}catch{}await write(router,'configureSale',[BigInt(id),'0x0000000000000000000000000000000000000000',parseEther(process.env.INITIAL_LAND_PRICE_ETH||'0.001'),true]);}result.seededAt=new Date().toISOString();}
result.deployedAt=new Date().toISOString();persist();console.log(`Deployment saved: ${filename}`);console.log(JSON.stringify({LAND_CONTRACT:land.address,NFT_CONTRACT:assets.address,PAYMENT_ROUTER:router.address,MARKETPLACE_CONTRACT:market.address,DEPLOYMENT_BLOCK:Math.min(...Object.values(result.contracts).map(c=>c.blockNumber)),BLOCKCHAIN_NETWORK:main?'base-mainnet':'base-sepolia'},null,2));
