import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
import {Browser,chain,fixture,moduleAt,reset,sqlite} from './api-harness.mjs';
let user,adminBrowser;const owner={userId:'owner-platform-id'};const wallet='0x1111111111111111111111111111111111111111',adminWallet='0x2222222222222222222222222222222222222222';const browsers=new Map();
const admin=moduleAt('app/api/admin/route.ts'),campaigns=moduleAt('app/api/campaigns/route.ts'),content=moduleAt('app/api/content/route.ts');
function register(id='player',address=wallet){if(!browsers.has(id))browsers.set(id,fixture(id,address,id===owner.userId?'ADMIN':'USER'));}
const post=async(route,body)=>{const r=await (browsers.get(user?.userId)??new Browser()).call(route===admin?'admin':'campaigns',body);return r;};
beforeEach(()=>{reset();browsers.clear();register(owner.userId,adminWallet);adminBrowser=browsers.get(owner.userId);user=owner;chain.receipt={status:'success',blockNumber:10n};chain.transaction={to:wallet,value:1000n,input:'0x',from:adminWallet};});
async function makeCampaign(kind='social',extra={}){const r=await post(admin,{action:'campaign',kind,title:'Test campaign',description:'Perform task and provide evidence',url:'https://example.com/task',points:100,minPoints:100,amountWei:'1000',maxRecipients:10,startsAt:Date.now()-1000,endsAt:Date.now()+100000,...extra});assert.equal(r.status,200,JSON.stringify(r.body));return sqlite.prepare('SELECT id FROM campaigns ORDER BY rowid DESC').get().id}
test('anonymous and normal players cannot administer; persisted admin role is required',async()=>{assert.equal((await new Browser().call('admin')).status,401);register();user={userId:'player'};assert.equal((await post(admin,{action:'ban',userId:'other',banned:true})).status,403);assert.equal((await adminBrowser.call('admin')).status,200)});
test('draft content is private and stale publisher cannot overwrite a newer revision',async()=>{const config=moduleAt('lib/community-config.ts').defaultLanding;assert.equal((await post(admin,{action:'content',key:'landing_draft',value:{...config,title:'Secret draft'},revision:0})).status,200);const pub=await (await content.GET()).json();assert.equal(pub.landing.title,config.title);assert.equal(pub.landing_draft,undefined);assert.equal((await post(admin,{action:'content',key:'landing',value:config,revision:0})).status,200);assert.equal((await post(admin,{action:'content',key:'landing',value:config,revision:0})).status,409)});
test('social review awards points once, rejects duplicate submissions and freezes published terms',async()=>{register();const id=await makeCampaign();assert.equal((await post(admin,{action:'launch',id})).status,200);user={userId:'player',email:'player@example.com'};assert.equal((await post(campaigns,{action:'submit',id,evidence:'https://example.com/proof'})).status,200);assert.equal((await post(campaigns,{action:'submit',id,evidence:'different proof'})).status,409);user=owner;const sub=sqlite.prepare('SELECT id FROM submissions').get().id;assert.equal((await post(admin,{action:'review',id:sub,status:'approved'})).status,200);assert.equal((await post(admin,{action:'review',id:sub,status:'approved'})).status,409);user={userId:'player',email:'player@example.com'};assert.equal((await browsers.get(user.userId).call('campaigns')).body.points.total,100)});
test('airdrop launch snapshots eligible wallets once; later points or accounts do not join',async()=>{register();register('low','0x3333333333333333333333333333333333333333');const social=await makeCampaign();sqlite.prepare("INSERT INTO submissions VALUES(?,?,?,?,'approved',100,'',1)").run(crypto.randomUUID(),social,'player','verified evidence');const id=await makeCampaign('airdrop');assert.equal((await post(admin,{action:'launch',id})).status,200);assert.equal((await post(admin,{action:'launch',id})).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM allocations').get().n,1);user={userId:'low',email:'low@example.com'};assert.equal((await post(campaigns,{action:'claim',id})).status,409);user={userId:'player',email:'player@example.com'};assert.equal((await post(campaigns,{action:'claim',id})).status,200);assert.equal((await post(campaigns,{action:'claim',id})).status,409)});
test('payout reservation prevents duplicate sends and receipt must match exact recipient and value',async()=>{register();register(owner.userId,adminWallet);const id=await makeCampaign('airdrop',{minPoints:0,maxRecipients:2});await post(admin,{action:'launch',id});user={userId:'player',email:'player@example.com'};await post(campaigns,{action:'claim',id});user=owner;const a=sqlite.prepare('SELECT id FROM allocations WHERE user_id=\'player\'').get().id;assert.equal((await post(admin,{action:'reserve_payout',id:a,wallet:adminWallet})).status,200);assert.equal((await post(admin,{action:'reserve_payout',id:a,wallet:adminWallet})).status,409);chain.transaction.value=999n;assert.equal((await post(admin,{action:'payout',id:a,txHash:'0x'+'a'.repeat(64)})).status,400);chain.transaction.value=1000n;assert.equal((await post(admin,{action:'payout',id:a,txHash:'0x'+'a'.repeat(64)})).status,200);assert.equal((await post(admin,{action:'payout',id:a,txHash:'0x'+'a'.repeat(64)})).status,400);assert.equal(sqlite.prepare('SELECT status FROM allocations WHERE user_id=\'player\'').get().status,'paid')});
