import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {createRequire} from 'node:module';import ts from 'typescript';import {createHash} from 'node:crypto';import {createPublicClient,custom} from 'viem';import {baseSepolia} from 'viem/chains';
const require=createRequire(import.meta.url),root=process.cwd(),cache=new Map();export let sqlite;export const env={};export const chain={receipt:{status:'success',blockNumber:10n},transaction:{},nftOwner:null,nftFailure:false};
const verifier=createPublicClient({chain:baseSepolia,transport:custom({request:async()=> '0x00'},{retryCount:0})});
export function moduleAt(file){file=path.resolve(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const localRequire=id=>{if(id==='cloudflare:workers')return {env};if(id==='@/packages/blockchain/config')return {...moduleAt('packages/blockchain/config.ts'),publicClient:()=>({...verifier,readContract:async args=>{if(chain.nftFailure)throw Error('RPC unavailable');if(chain.read)return chain.read(args);if(args.functionName==='ownerOf')return chain.nftOwner??'0x0000000000000000000000000000000000000000';if(args.functionName==='supportsInterface')return true;return verifier.readContract(args)},getTransactionReceipt:async()=>chain.receipt,getTransaction:async()=>chain.transaction,getBlockNumber:async()=>11n,getBlock:async()=>({timestamp:BigInt(Math.ceil(Date.now()/1000))})})};if(id.startsWith('@/')||id.startsWith('.')){let target=id.startsWith('@/')?path.join(root,id.slice(2)):path.resolve(path.dirname(file),id);if(!path.extname(target))target+='.ts';return moduleAt(target)}return require(id)};vm.runInNewContext(`(function(require,module,exports){${js}\n})`,{console,crypto,Request,Response,URL,Date,Buffer,TextEncoder,TextDecoder,Uint8Array,structuredClone,setTimeout})(localRequire,module,module.exports);return module.exports}
function stmt(sql,args=[]){return {bind:(...a)=>stmt(sql,a),first:async()=>sqlite.prepare(sql).get(...args)??null,all:async()=>({results:sqlite.prepare(sql).all(...args)}),run:async()=>{const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}},sql,args}}
env.DB={prepare:sql=>stmt(sql),batch:async statements=>{sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
export function reset(){sqlite?.close();sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));sqlite.exec('PRAGMA foreign_keys=ON');delete env.AUTH_ADMIN_WALLET;delete env.AUTH_ORIGIN;delete env.BLOCKCHAIN_NETWORK;delete env.NFT_CONTRACT;chain.nftOwner=null;chain.nftFailure=false;delete chain.read;delete env.DECORATION_CONTRACT;delete env.LAND_CONTRACT;}
export const hash=v=>createHash('sha256').update(v).digest('hex');
export function request(path='/api/auth/me',body, cookie='',origin='https://game.test'){return new Request(origin+path,{method:body===undefined?'GET':'POST',headers:{origin,cookie,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})})}
export class Browser {cookie='';async call(path,body){const req=request('/api/'+path,body,this.cookie);const route=moduleAt('app/api/'+path+'/route.ts');const response=await route[body===undefined?'GET':'POST'](req);const jar=Object.fromEntries(this.cookie.split('; ').filter(Boolean).map(v=>v.split('=')));for(const c of response.headers.getSetCookie()){const [key,value]=c.split(';')[0].split('=');if(value)jar[key]=value;else delete jar[key]}this.cookie=Object.entries(jar).map(([k,v])=>k+'='+v).join('; ');return {status:response.status,body:await response.json(),headers:response.headers}}}
export function fixture(id,address,role='USER'){sqlite.prepare("INSERT INTO registrations(user_id,username,email,status,role,created_at) VALUES(?,?,'','active',?,1)").run(id,id,role);sqlite.prepare('INSERT INTO account_wallets VALUES(?,?,84532,1)').run(address,id);const token=crypto.randomUUID().replaceAll('-','').repeat(2);sqlite.prepare('INSERT INTO auth_sessions VALUES(?,?,?,84532,?,?)').run(hash(token),id,address,Date.now()+600000,Date.now());const browser=new Browser();browser.cookie='__Host-tpu_session='+token;return browser;}
