import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';import {createSiweMessage,parseSiweMessage} from 'viem/siwe';import {Browser,env,fixture,hash,moduleAt,request,reset,sqlite} from './api-harness.mjs';
beforeEach(reset);const owner=privateKeyToAccount(generatePrivateKey()),other=privateKeyToAccount(generatePrivateKey());
async function challenge(b=new Browser(),wallet=owner){const c=await b.call('auth/nonce',{address:wallet.address,chainId:84532});assert.equal(c.status,200,JSON.stringify(c.body));return {b,c,signature:await wallet.signMessage({message:c.body.message})}}
async function sign(b=new Browser(),wallet=owner){const {c,signature}=await challenge(b,wallet);const r=await b.call('auth/wallet',{id:c.body.id,address:wallet.address,signature});assert.equal(r.status,200,JSON.stringify(r.body));return b}
async function registered(wallet=owner,name='scavenger'){const b=await sign(new Browser(),wallet);const r=await b.call('auth/register',{username:name,consent:true});assert.equal(r.status,200,JSON.stringify(r.body));return b}
test('real ECDSA SIWE: new wallet registers one user, wallet and player, same ID in game/profile',async()=>{const b=await sign();assert.equal((await b.call('game')).status,401);const r=await b.call('auth/register',{username:'scavenger',consent:true});assert.equal(r.status,200);const id=r.body.user.id;assert.equal(r.body.user.role,'USER');assert.equal(sqlite.prepare('SELECT user_id FROM players').get().user_id,id);assert.equal(sqlite.prepare('SELECT user_id FROM account_wallets').get().user_id,id);assert.equal((await b.call('game')).body.character.username,'scavenger');assert.equal((await b.call('profile')).body.player.username,'scavenger');assert.equal((await b.call('auth/me')).body.user.id,id)});
test('refresh/reopen and repeated login do not create another user/player',async()=>{const b=await registered();const id=(await b.call('auth/me')).body.user.id;const reopened=new Browser();reopened.cookie=b.cookie;assert.equal((await reopened.call('auth/me')).body.user.id,id);await sign(b);assert.equal((await b.call('auth/me')).body.user.id,id);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM players').get().n,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM registrations').get().n,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM auth_sessions').get().n,1);assert.equal((await reopened.call('auth/me')).body.authenticated,false)});
test('cookie is persistent host-only Secure HttpOnly SameSite Lax; server stores only hash',async()=>{const b=await sign();const response=await b.call('auth/register',{username:'scavenger',consent:true});const cookie=response.headers.get('set-cookie');for(const item of ['__Host-tpu_session=','HttpOnly','Secure','SameSite=Lax','Path=/','Max-Age='])assert.ok(cookie.includes(item));assert.ok(!cookie.includes('Domain='));const token=b.cookie.split('=')[1];assert.equal(sqlite.prepare('SELECT hash FROM auth_sessions').get().hash,hash(token));assert.notEqual(sqlite.prepare('SELECT hash FROM auth_sessions').get().hash,token)});
test('invalid signature, spoofed address and cross-browser nonce are rejected',async()=>{const {b,c}=await challenge();const forged=await other.signMessage({message:c.body.message});assert.equal((await b.call('auth/wallet',{id:c.body.id,address:owner.address,signature:forged})).status,401);const signature=await owner.signMessage({message:c.body.message});assert.equal((await b.call('auth/wallet',{id:c.body.id,address:other.address,signature})).status,401);assert.equal((await new Browser().call('auth/wallet',{id:c.body.id,address:owner.address,signature})).status,401);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM auth_sessions').get().n,0)});
test('nonce is single-use even in parallel verification requests',async()=>{const {b,c,signature}=await challenge();const clone=new Browser();clone.cookie=b.cookie;const body={id:c.body.id,address:owner.address,signature};const replies=await Promise.all([b.call('auth/wallet',body),clone.call('auth/wallet',body)]);assert.deepEqual(replies.map(r=>r.status).sort(),[200,401]);assert.equal((await clone.call('auth/wallet',body)).status,401);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM auth_sessions').get().n,1)});
test('expired nonce and expired SIWE message both fail',async()=>{const {b,c,signature}=await challenge();sqlite.prepare('UPDATE auth_nonces SET expires_at=0').run();assert.equal((await b.call('auth/wallet',{id:c.body.id,address:owner.address,signature})).status,401);const next=await challenge();const expired=createSiweMessage({...parseSiweMessage(next.c.body.message),issuedAt:new Date(Date.now()-600000),expirationTime:new Date(Date.now()-1000)});sqlite.prepare('UPDATE auth_nonces SET message=? WHERE id=?').run(expired,next.c.body.id);assert.equal((await next.b.call('auth/wallet',{id:next.c.body.id,address:owner.address,signature:await owner.signMessage({message:expired})})).status,401)});
test('SIWE binds domain, address, chain, action, issued time and expiry',async()=>{const {c}=await challenge();const p=parseSiweMessage(c.body.message);assert.equal(p.domain,'game.test');assert.equal(p.uri,'https://game.test');assert.equal(p.chainId,84532);assert.equal(p.address.toLowerCase(),owner.address.toLowerCase());assert.match(p.statement,/Sign in/);assert.equal(p.expirationTime-p.issuedAt,300000);const b=new Browser();assert.equal((await b.call('auth/nonce',{address:owner.address,chainId:8453})).status,400);env.AUTH_ORIGIN='https://correct.test';assert.equal((await b.call('auth/nonce',{address:owner.address,chainId:84532})).status,403)});
test('session renewal extends idle window but cannot exceed 30-day absolute lifetime',async()=>{const b=await registered();const created=Date.now()-29*86400000;sqlite.prepare('UPDATE auth_sessions SET created_at=?,expires_at=?').run(created,Date.now()+100000);const r=await b.call('auth/refresh',{});assert.equal(r.status,200);assert.equal(r.headers.get('set-cookie'),null);assert.equal(sqlite.prepare('SELECT expires_at FROM auth_sessions').get().expires_at,created+30*86400000)});
test('expired sessions cannot be refreshed, and expired registration proof cannot create account',async()=>{const b=await registered();sqlite.prepare('UPDATE auth_sessions SET expires_at=0').run();assert.equal((await b.call('auth/refresh',{})).status,401);assert.equal((await b.call('game')).status,401);const pending=await sign(new Browser(),other);sqlite.prepare('UPDATE auth_sessions SET expires_at=0').run();assert.equal((await pending.call('auth/register',{username:'other',consent:true})).status,401)});
test('global logout revokes the shared session in another tab and stale refresh cannot resurrect it',async()=>{const b=await registered(),tab=new Browser();tab.cookie=b.cookie;assert.equal((await b.call('auth/logout',{})).status,200);assert.equal((await tab.call('auth/me')).body.authenticated,false);assert.equal((await tab.call('auth/refresh',{})).status,401);assert.equal((await tab.call('game')).status,401);assert.equal((await b.call('auth/logout',{})).status,200)});
test('5 parallel registrations create at most one account/player/wallet/session',async()=>{const b=await sign();const cookie=b.cookie;const replies=await Promise.all(Array.from({length:5},()=>{const tab=new Browser();tab.cookie=cookie;return tab.call('auth/register',{username:'parallel',consent:true})}));assert.ok(replies.some(r=>r.status===200));for(const table of ['registrations','players','account_wallets','auth_sessions'])assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM '+table).get().n,1)});
test('front-end role/userId/wallet spoofing is rejected at registration; default USER cannot administer',async()=>{const b=await sign();for(const extra of [{role:'ADMIN'},{userId:'owner'},{wallet:other.address}])assert.equal((await b.call('auth/register',{username:'scavenger',consent:true,...extra})).status,400);await b.call('auth/register',{username:'scavenger',consent:true});assert.equal((await b.call('admin')).status,403);assert.equal((await b.call('admin',{action:'ban',userId:'owner',banned:true})).status,403)});
test('explicit bootstrap wallet receives persisted role after signature; all other wallets remain USER',async()=>{env.AUTH_ADMIN_WALLET=owner.address;const b=await registered();assert.equal((await b.call('auth/me')).body.user.role,'ADMIN');assert.equal((await b.call('admin')).status,200);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM admin_audit').get().n,1);const stranger=await registered(other,'stranger');assert.equal((await stranger.call('admin')).status,403);delete env.AUTH_ADMIN_WALLET;assert.equal((await b.call('admin')).status,200)});
test('ban immediately revokes access and unbanning does not resurrect old cookie',async()=>{const admin=fixture('admin',owner.address.toLowerCase(),'ADMIN');const user=fixture('stranger',other.address.toLowerCase());assert.equal((await admin.call('admin',{action:'ban',userId:'stranger',banned:true})).status,200);assert.equal((await user.call('game')).status,401);await admin.call('admin',{action:'ban',userId:'stranger',banned:false});assert.equal((await user.call('auth/me')).body.authenticated,false)});
test('CSRF rejects missing/cross origin; insecure cookie cannot authenticate over HTTPS',async()=>{const b=await registered();const route=moduleAt('app/api/auth/logout/route.ts');for(const origin of ['', 'https://attacker.test']){const req=new Request('https://game.test/api/auth/logout',{method:'POST',headers:{cookie:b.cookie,origin}});assert.equal((await route.POST(req)).status,403)}const insecure=new Browser();insecure.cookie=b.cookie.replace('__Host-','');assert.equal((await insecure.call('game')).status,401)});
test('verified legacy primary wallet preserves user ID, username and progress; secondary wallet cannot split account',async()=>{sqlite.prepare("INSERT INTO registrations(user_id,username,email,status,created_at) VALUES('old','original','','active',1)").run();sqlite.prepare('INSERT INTO wallets VALUES(?,?,84532,?)').run(owner.address.toLowerCase(),'old',1);sqlite.prepare('INSERT INTO wallets VALUES(?,?,84532,?)').run(other.address.toLowerCase(),'old',2);const initial=moduleAt('packages/game-core/world.ts').initialState();initial.scrap=999;sqlite.prepare("INSERT INTO players VALUES('old','original',?,0,1,1)").run(JSON.stringify(initial));const b=await sign();assert.equal((await b.call('auth/me')).body.user.id,'old');assert.equal((await b.call('game')).body.character.state.scrap,999);const {b:second,c,signature}=await challenge(new Browser(),other);assert.equal((await second.call('auth/wallet',{id:c.body.id,address:other.address,signature})).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM registrations').get().n,1)});
test('database rejects duplicate primary wallets, orphan players and orphan wallet owners',()=>{fixture('one',owner.address.toLowerCase());assert.throws(()=>sqlite.prepare('INSERT INTO account_wallets VALUES(?,?,84532,1)').run(other.address.toLowerCase(),'one'),/UNIQUE/);assert.throws(()=>sqlite.prepare('INSERT INTO account_wallets VALUES(?,?,84532,1)').run(other.address.toLowerCase(),'missing'),/FOREIGN KEY/);assert.throws(()=>sqlite.prepare("INSERT INTO players VALUES('missing','missing','{}',0,1,1)").run(),/FOREIGN KEY/)});
test('game/profile cannot select another user via URL or payload',async()=>{const b=await registered();const second=await registered(other,'other');const id=(await second.call('auth/me')).body.user.id;const route=moduleAt('app/api/profile/route.ts');const r=await route.GET(request('/api/profile?userId='+id,undefined,b.cookie));assert.equal((await r.json()).player.username,'scavenger');const g=await b.call('game',{type:'create',userId:id,username:'other'});assert.equal(g.status,403);assert.equal((await b.call('game')).body.character.username,'scavenger')});
test('auth challenges are rate-limited',async()=>{const b=new Browser();for(let i=0;i<10;i++)assert.equal((await b.call('auth/nonce',{address:owner.address,chainId:84532})).status,200);assert.equal((await b.call('auth/nonce',{address:owner.address,chainId:84532})).status,429)});
test('network migration requires a new signed session before Web3 is authorized',async()=>{const b=await registered();env.BLOCKCHAIN_NETWORK='base-mainnet';assert.equal((await b.call('auth/me')).body.networkVerified,false);const c=await b.call('auth/nonce',{address:owner.address,chainId:8453});assert.equal(c.status,200);const signature=await owner.signMessage({message:c.body.message});assert.equal((await b.call('auth/wallet',{id:c.body.id,address:owner.address,signature})).status,200);const me=await b.call('auth/me');assert.equal(me.body.networkVerified,true);assert.equal(me.body.user.wallet.chainId,8453);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM registrations').get().n,1)});
test('public configuration does not leak private RPC credentials or bootstrap wallet',async()=>{env.BASE_RPC_URL='https://rpc.test/private-key';env.AUTH_ADMIN_WALLET=owner.address;const b=new Browser();const r=await b.call('config');assert.ok(!JSON.stringify(r.body).includes('private-key'));assert.ok(!JSON.stringify(r.body).includes(owner.address));delete env.BASE_RPC_URL});
test('bounded JSON parser rejects oversized and malformed bodies without parsing unbounded input',async()=>{const route=moduleAt('app/api/auth/nonce/route.ts');for(const [body,status] of [['x'.repeat(33000),413],['{broken',400]]){const req=new Request('https://game.test/api/auth/nonce',{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body});assert.equal((await route.POST(req)).status,status)}});
test('sessions with only a supplied wallet address or platform identity headers cannot authenticate',async()=>{const route=moduleAt('app/api/game/route.ts');const req=new Request('https://game.test/api/game',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.test','x-wallet-address':owner.address,authorization:'Bearer '+owner.address}});assert.equal((await route.GET(req)).status,401)});

test('populated v12 database migration preserves exact player state and enables FK',async()=>{const {DatabaseSync}=await import('node:sqlite');const {readFileSync,readdirSync}=await import('node:fs');const db=new DatabaseSync(':memory:');const files=readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort();for(const f of files.slice(0,4))db.exec(readFileSync('drizzle/'+f,'utf8'));db.prepare("INSERT INTO registrations VALUES('existing','original','','active',1)").run();const state=JSON.stringify({scrap:1234,xp:900,quest:'completed'});db.prepare("INSERT INTO players VALUES('existing','original',?,17,2,1)").run(state);db.exec('PRAGMA foreign_keys=ON');for(const f of files.slice(4)){db.exec('BEGIN');db.exec(readFileSync('drizzle/'+f,'utf8'));db.exec('COMMIT')}const player=db.prepare('SELECT * FROM players').get();assert.equal(player.state,state);assert.equal(player.revision,17);assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);assert.equal(db.prepare('PRAGMA foreign_key_list(players)').get().table,'registrations');db.close()});
