import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
import {Browser,fixture,moduleAt,reset,sqlite,env} from './api-harness.mjs';
const {award,defaultRules,board,gameAchievements}=moduleAt('lib/leaderboard.ts');let admin,player;
beforeEach(()=>{reset();admin=fixture('admin','0x'+'1'.repeat(40),'ADMIN');player=fixture('player','0x'+'2'.repeat(40))});
async function start(rules=defaultRules){const r=await admin.call('admin/leaderboard',{action:'create',title:'Test season',days:30,rules});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal((await admin.call('admin/leaderboard',{action:'start',id:r.body.id})).status,200);return r.body.id}
const season=id=>sqlite.prepare('SELECT * FROM seasons WHERE id=?').get(id);
test('permissions, private drafts, one active season and locked rules',async()=>{assert.equal((await new Browser().call('admin/leaderboard')).status,401);assert.equal((await player.call('admin/leaderboard')).status,403);const r=await admin.call('admin/leaderboard',{action:'create',title:'Draft season',days:30,rules:defaultRules});assert.equal((await player.call('leaderboard')).body.season,null);await start();assert.equal((await admin.call('admin/leaderboard',{action:'start',id:r.body.id})).status,409);const active=sqlite.prepare("SELECT id FROM seasons WHERE status='active'").get().id;assert.equal((await admin.call('admin/leaderboard',{action:'edit',id:active,title:'Changed rules',days:30,rules:defaultRules})).status,409)});
test('atomic awards enforce daily caps, replay protection, UTC reset and end time',async()=>{const id=await start(),now=Date.now();for(let n=0;n<6;n++)await award('player','daily','claim'+n,now).run();await award('player','daily','claim0',now).run();assert.equal(sqlite.prepare('SELECT SUM(points) n FROM season_events').get().n,60);await award('player','daily','tomorrow',now+86400000).run();assert.equal(sqlite.prepare('SELECT SUM(points) n FROM season_events').get().n,80);await award('player','daily','late',season(id).ends_at).run();assert.equal(sqlite.prepare('SELECT SUM(points) n FROM season_events').get().n,80);await award('player','social','lost-update',now,'0').run();assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM season_events WHERE source='lost-update'").get().n,0)});
test('qualification, shares, exclusion, own row and public identity privacy',async()=>{const id=await start({...defaultRules,minDays:1,minPoints:10});fixture('other','0x'+'3'.repeat(40));await award('player','daily','a',Date.now()).run();await award('other','explore','b',Date.now()).run();let b=await board(season(id),0,'player');assert.equal(b.mine.rank,1);assert.equal(b.stats.eligible,2);assert.ok(Math.abs(b.rows.reduce((n,r)=>n+r.share,0)-100)<0.00001);assert.ok(!JSON.stringify(b).includes('0x'));assert.equal(b.rows[0].user_id,undefined);assert.equal((await admin.call('admin/leaderboard',{action:'exclude',id,username:'player',reason:'Confirmed exploit'})).status,200);b=await board(season(id),0,'player');assert.equal(b.mine,null);assert.equal(b.excluded,true);await award('player','social','excluded',Date.now()).run();assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM season_events WHERE source='excluded'").get().n,0);await admin.call('admin/leaderboard',{action:'restore',id,username:'player'});assert.equal((await board(season(id),0,'player')).mine.points,20)});
test('frozen snapshot stays unchanged and cannot score, refreeze or edit exclusions',async()=>{const id=await start({...defaultRules,minDays:1,minPoints:10});await award('player','daily','a',Date.now()).run();const frozen=await admin.call('admin/leaderboard',{action:'freeze',id});assert.equal(frozen.status,200,JSON.stringify(frozen.body));await award('player','social','after',Date.now()).run();sqlite.prepare("UPDATE registrations SET status='banned' WHERE user_id='player'").run();assert.equal((await board(season(id),0)).rows[0].points,20);assert.equal((await admin.call('admin/leaderboard',{action:'freeze',id})).status,409);assert.equal((await admin.call('admin/leaderboard',{action:'exclude',id,username:'player',reason:'Too late now'})).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM season_final').get().n,1)});
test('achievement derivation requires a new authoritative transition',()=>{const {initialState}=moduleAt('packages/game-core/world.ts');const before=initialState(),now=Date.now(),after=structuredClone(before);after.daily={day:new Date(now).toISOString().slice(0,10),kills:0,crafted:0,caches:['cache1'],claimed:['hunt']};assert.equal(gameAchievements(before,after,now).length,2);assert.equal(gameAchievements(after,after,now).length,0)});
test('social approval awards season points only once',async()=>{await start();const campaign=crypto.randomUUID(),sub=crypto.randomUUID();sqlite.prepare("INSERT INTO campaigns VALUES(?,'social','Task','Do task','https://example.com',100,0,'0',10,'active',0,9999999999999,0)").run(campaign);sqlite.prepare("INSERT INTO submissions VALUES(?,?,?,'proof','pending',100,'',0)").run(sub,campaign,'player');const r=await admin.call('admin',{action:'review',id:sub,status:'approved'});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal((await admin.call('admin',{action:'review',id:sub,status:'approved'})).status,409);assert.equal(sqlite.prepare('SELECT SUM(points) n FROM season_events').get().n,20)});
test('game write marker prevents a losing revision from receiving points',async()=>{await start();const {initialState}=moduleAt('packages/game-core/world.ts');sqlite.prepare('INSERT INTO players VALUES(?,?,?,1,1,1)').run('player','player',JSON.stringify({...initialState(),writeId:'winner'}));const guard="EXISTS(SELECT 1 FROM players WHERE user_id=? AND revision=? AND json_extract(state,'$.writeId')=?)";await env.DB.batch([award('player','daily','loser',Date.now(),guard,['player',1,'loser']),award('player','daily','winner',Date.now(),guard,['player',1,'winner'])]);assert.equal(sqlite.prepare('SELECT SUM(points) n FROM season_events').get().n,20);assert.equal(sqlite.prepare('SELECT source FROM season_events').get().source,'winner')});
