import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
import {fixture,moduleAt,reset,sqlite,env,chain,request} from './api-harness.mjs';
const route=moduleAt('app/api/parcel/route.ts'),{footprint}=moduleAt('packages/game-core/parcel-layout.ts');
const A='0x'+'1'.repeat(40),B='0x'+'2'.repeat(40),LAND='0x'+'3'.repeat(40),DECOR='0x'+'4'.repeat(40);let user,other,versions,owners;
beforeEach(()=>{reset();user=fixture('alice',A);other=fixture('bob',B);env.LAND_CONTRACT=LAND;env.DECORATION_CONTRACT=DECOR;owners={};versions={};chain.read=({address,args,functionName})=>functionName==='ownerOf'?(owners[address+args[0]]??A):functionName==='transferVersion'?BigInt(versions[address+args[0]]??1):null;for(let id=1;id<=3;id++)sqlite.prepare("INSERT INTO decoration_items VALUES(?,?,?,?,?,?,?,'published',84532,?,1)").run(id,'Bench','A nice bench','/assets/decorations/bench.png','rare',2,1,DECOR)});
async function place(id,x=1,y=1,browser=user,parcel=1,rotation=0){const r=await route.POST(request('/api/parcel',{action:'place',itemId:id,parcel,x,y,rotation},browser.cookie));return {status:r.status,body:await r.json()}}
async function view(){const r=await route.GET(request('/api/parcel?id=1',undefined,user.cookie));return {status:r.status,body:await r.json()}}
test('rotated footprints respect actual parcel bounds',()=>{assert.equal(footprint(30,31,2,1,0,32,32).length,2);assert.throws(()=>footprint(31,31,2,1,0,32,32));assert.throws(()=>footprint(1,1,2,1,45,32,32));assert.equal(footprint(31,30,2,1,90,32,32).length,2)});
test('only land and NFT owner may place; guests cannot edit',async()=>{assert.equal((await place(1,1,1,other)).status,403);owners[DECOR+'1']=B;assert.equal((await place(1)).status,403);owners[DECOR+'1']=A;assert.equal((await place(1)).status,200);assert.equal((await view()).body.placements.length,1)});
test('overlap fails atomically; move and remove persist; one NFT cannot occupy two maps',async()=>{assert.equal((await place(1)).status,200);assert.equal((await place(2,2,1)).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM decoration_cells').get().n,2);assert.equal((await place(1,4,4)).status,200);assert.equal((await place(1,1,1,user,2)).status,409);const r=await route.POST(request('/api/parcel',{action:'remove',itemId:1,parcel:1},user.cookie));assert.equal(r.status,200);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM decoration_cells').get().n,0)});
test('land transfer away and back invalidates placements using transfer version',async()=>{await place(1);versions[LAND+'1']=3;assert.equal((await view()).body.placements.length,0);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM decoration_cells').get().n,0)});
test('decoration transfer invalidates placement; RPC outage does not destroy saved placement',async()=>{await place(1);chain.nftFailure=true;assert.equal((await view()).status,503);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM parcel_decorations').get().n,1);chain.nftFailure=false;owners[DECOR+'1']=B;assert.equal((await view()).body.placements.length,0)});
test('outside bounds and permanent building collisions are rejected',async()=>{assert.equal((await place(1,32,0)).status,400);sqlite.prepare("INSERT INTO buildings VALUES('b',1,1,1,0,'shack',1)").run();assert.equal((await place(1,4,4)).status,409)});
test('admin definition validation and publication require a configured sale; users cannot create',async()=>{const admin=fixture('owner','0x'+'5'.repeat(40),'ADMIN');const definition={action:'create',name:'Neon bench',description:'A bench for the parcel.',image:'/assets/decorations/bench.png',rarity:'rare',width:2,height:1};assert.equal((await user.call('admin/decorations',definition)).status,403);assert.equal((await admin.call('admin/decorations',{...definition,width:99})).status,400);assert.equal((await admin.call('admin/decorations',definition)).status,200);const id=sqlite.prepare('SELECT MAX(id) id FROM decoration_items').get().id;const prior=chain.read;chain.read=args=>args.functionName==='sales'?['0x'+'6'.repeat(40),100n,true]:prior(args);assert.equal((await admin.call('admin/decorations',{action:'publish',id})).status,409);env.PAYMENT_TOKEN='0x'+'6'.repeat(40);env.PAYMENT_TOKEN_SYMBOL='tTPU';env.PAYMENT_TOKEN_DECIMALS='18';assert.equal((await admin.call('admin/decorations',{action:'publish',id})).status,200);assert.equal((await admin.call('admin/decorations',{action:'publish',id})).status,404)});
