import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';
import {Browser,fixture,reset,sqlite,hash,moduleAt} from './api-harness.mjs';
const {initialState}=moduleAt('packages/game-core/world.ts');const {defaultRules}=moduleAt('lib/leaderboard.ts');let admin,inviter;const season='8a6fd22b-dd4a-413c-8f57-7f112b911541';
beforeEach(()=>{reset();admin=fixture('admin','0x'+'1'.repeat(40),'ADMIN');inviter=fixture('inviter','0x'+'2'.repeat(40));sqlite.prepare("INSERT INTO seasons(id,title,status,rules,starts_at,ends_at,created_at,active_slot) VALUES(?,'Referral test','active',?,?,?,0,1)").run(season,JSON.stringify(defaultRules),Date.now()-10*86400000,Date.now()+86400000)});
function invitee(id='newbie',age=4){const b=fixture(id,'0x'+(10+id.length+Number(id.match(/\d+/)?.[0]??0)).toString(16).padStart(40,'0'));sqlite.prepare('INSERT INTO players VALUES(?,?,?,0,0,0)').run(id,id,JSON.stringify({...initialState(),quest:'complete'}));sqlite.prepare("INSERT INTO referrals(user_id,referrer_id,created_at) VALUES(?,'inviter',?)").run(id,Date.now()-age*86400000);for(let d=1;d<=3;d++){const at=Date.now()-d*86400000;sqlite.prepare('INSERT INTO season_events VALUES(?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),season,id,'day:'+d,'daily',new Date(at).toISOString().slice(0,10),20,at)}return b}
const approve=id=>admin.call('admin/referrals',{action:'approve',id,note:'Verified real player participation'});
test('invitation code is private, stable and requires authenticated creation',async()=>{assert.equal((await new Browser().call('referrals',{action:'create'})).status,401);const first=await inviter.call('referrals',{action:'create'});assert.match(first.body.code.code,/^[a-f0-9]{32}$/);assert.equal((await inviter.call('referrals',{action:'create'})).body.code.code,first.body.code.code);assert.equal((await admin.call('referrals')).body.code,null)});
test('new registration attaches once; existing users cannot change attribution',async()=>{const code=(await inviter.call('referrals',{action:'create'})).body.code.code;const pending=new Browser(),token='a'.repeat(64);pending.cookie='__Host-tpu_session='+token;sqlite.prepare('INSERT INTO auth_sessions VALUES(?,NULL,?,84532,?,?)').run(hash(token),'0x'+'7'.repeat(40),Date.now()+60000,Date.now());const r=await pending.call('auth/register',{username:'newplayer',consent:true,referral:code});assert.equal(r.status,200,JSON.stringify(r.body));const id=r.body.user.id;assert.equal(sqlite.prepare('SELECT referrer_id FROM referrals WHERE user_id=?').get(id).referrer_id,'inviter');const other=(await admin.call('referrals',{action:'create'})).body.code.code;await pending.call('auth/register',{username:'newplayer',consent:true,referral:other});assert.equal(sqlite.prepare('SELECT referrer_id FROM referrals WHERE user_id=?').get(id).referrer_id,'inviter')});
test('qualified approval awards once, unauthorised and premature approval fail',async()=>{invitee('one',0);assert.equal((await approve('one')).status,409);sqlite.prepare('UPDATE referrals SET created_at=0').run();assert.equal((await inviter.call('admin/referrals',{action:'approve',id:'one',note:'Trying approval'})).status,403);assert.equal((await approve('one')).status,200);assert.equal((await approve('one')).status,409);assert.equal(sqlite.prepare("SELECT SUM(points) n FROM season_events WHERE user_id='inviter'").get().n,30)});
test('daily cap does not burn a future referral award',async()=>{for(const id of ['p1','p2','p3'])invitee(id);assert.equal((await approve('p1')).status,200);assert.equal((await approve('p2')).status,200);assert.equal((await approve('p3')).status,409);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM season_events WHERE source='referral:p3'").get().n,0);sqlite.prepare("UPDATE season_events SET day='2000-01-01' WHERE category='referral'").run();assert.equal((await approve('p3')).status,200)});
test('referral reversal removes points and cannot modify a frozen season',async()=>{invitee();await approve('newbie');assert.equal((await admin.call('admin/referrals',{action:'revoke',id:'newbie',note:'Confirmed duplicate-account activity'})).status,200);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM season_events WHERE user_id='inviter'").get().n,0);invitee('person2');await approve('person2');sqlite.prepare("UPDATE seasons SET status='frozen',active_slot=NULL").run();assert.equal((await admin.call('admin/referrals',{action:'revoke',id:'person2',note:'Late correction attempt'})).status,409);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM season_events WHERE source='referral:person2'").get().n,1)});
test('legacy season without referral rules cannot award, social-only days do not qualify',async()=>{invitee();sqlite.prepare("UPDATE season_events SET category='social'").run();assert.equal((await approve('newbie')).status,409);sqlite.prepare("UPDATE season_events SET category='daily'").run();const {referral,...legacy}=defaultRules;sqlite.prepare('UPDATE seasons SET rules=?').run(JSON.stringify(legacy));assert.equal((await approve('newbie')).status,409)});
test('excluded invitee cannot generate a referral award',async()=>{invitee();sqlite.prepare('INSERT INTO season_exclusions VALUES(?,?,?,?,?)').run('exclusion',season,'newbie','Under review',Date.now());assert.equal((await approve('newbie')).status,409)});
test('five-referral season cap is enforced independently of daily limits',async()=>{sqlite.prepare("UPDATE seasons SET rules=json_set(rules,'$.referral.cap',1000)").run();for(let i=1;i<=6;i++)invitee('member'+i);for(let i=1;i<=5;i++)assert.equal((await approve('member'+i)).status,200);assert.equal((await approve('member6')).status,409);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM referrals WHERE status='approved'").get().n,5)});
