import {test} from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),A='0x1111111111111111111111111111111111111111',B='0x2222222222222222222222222222222222222222',config={chainId:84532,network:'Base Sepolia'};
function setup(){let me={networkVerified:true,authenticated:true,user:{wallet:{address:A}}},ok=true;const events=new EventTarget(),module={exports:{}};const js=ts.transpileModule(fs.readFileSync('lib/wallet-client.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(`(function(require,module,exports){${js}})`,{window:events,Event,fetch:async()=>({ok,json:async()=>me})})(require,module,module.exports);class Provider extends EventEmitter{account=A;chain=84532;async request({method}){if(method==='eth_accounts')return this.account?[this.account]:[];if(method==='eth_chainId')return '0x'+this.chain.toString(16);throw Error('Unexpected request')}}return {api:module.exports,provider:new Provider(),events,setMe:value=>{me=value},offline:()=>{ok=false}}}
test('repeated provider attachment installs exactly one accounts/chain listener and detaches on cleanup',()=>{const {api,provider}=setup();for(let i=0;i<5;i++)api.attachProvider(provider);assert.equal(provider.listenerCount('accountsChanged'),1);assert.equal(provider.listenerCount('chainChanged'),1);api.detachProvider();assert.equal(provider.listenerCount('accountsChanged'),0);assert.equal(provider.listenerCount('chainChanged'),0)});
test('wallet connection without a server session cannot authorize Web3',async()=>{const {api,provider,setMe}=setup();api.attachProvider(provider);await api.readProvider();setMe({authenticated:false,user:null});await assert.rejects(api.requireWallet(config),/Sign in/)});
test('accountsChanged updates every subscriber and blocks wrong-wallet transaction',async()=>{const {api,provider,events}=setup();api.attachProvider(provider);await api.readProvider();let changes=0;events.addEventListener('tpu-wallet',()=>changes++);provider.account=B;provider.emit('accountsChanged',[B]);assert.equal(api.activeAccount,B);await assert.rejects(api.requireWallet(config),/Wallet changed/);assert.ok(changes>=1)});
test('chainChanged blocks wrong-network transaction, returning to correct chain restores it',async()=>{const {api,provider}=setup();api.attachProvider(provider);provider.chain=8453;provider.emit('chainChanged','0x2105');await assert.rejects(api.requireWallet(config),/Switch your wallet/);provider.chain=84532;provider.emit('chainChanged','0x14a34');assert.equal((await api.requireWallet(config)).account,A)});
test('provider account is reread before transaction even if wallet emits no change event',async()=>{const {api,provider}=setup();api.attachProvider(provider);await api.readProvider();provider.account=B;await assert.rejects(api.requireWallet(config),/Wallet changed/)});
test('disconnect clears provider state and denied signature has a readable message',async()=>{const {api,provider}=setup();api.attachProvider(provider);await api.readProvider();api.detachProvider();assert.equal(api.activeAccount,null);await assert.rejects(api.requireWallet(config),/Connect/);assert.match(api.walletError({code:4001}),/declined/)});
