import {createPublicClient,fallback,http,isAddress,parseAbi,type Address} from 'viem';
import {base,baseSepolia} from 'viem/chains';
export const AIRDROP_CHAIN_ID=baseSepolia.id;
export type Registry={testToken?:Address|null;walletConnectProjectId?:string;network:string;chainId:number;rpcUrls:string[];explorer:string;land:Address|null;marketplace:Address|null;router:Address|null;assets:Address|null;deployed:boolean;tokens:{address:Address;symbol:string;decimals:number}[];tokenEnabled:boolean};
export function registry(env:Record<string,string|undefined>):Registry{const main=env.BLOCKCHAIN_NETWORK==='base-mainnet';const chain=main?base:baseSepolia;const addr=(v:string|undefined):Address|null=>v&&isAddress(v)&&v!=='0x0000000000000000000000000000000000000000'?v:null;const land=addr(env.LAND_CONTRACT),marketplace=addr(env.MARKETPLACE_CONTRACT),router=addr(env.PAYMENT_ROUTER),assets=addr(env.NFT_CONTRACT);const tokens:Registry['tokens']=[];if(env.PAYMENT_TOKEN&&isAddress(env.PAYMENT_TOKEN)&&env.PAYMENT_TOKEN_SYMBOL&&env.PAYMENT_TOKEN_DECIMALS){const decimals=Number(env.PAYMENT_TOKEN_DECIMALS);if(Number.isInteger(decimals)&&decimals>=0&&decimals<=18)tokens.push({address:env.PAYMENT_TOKEN,symbol:env.PAYMENT_TOKEN_SYMBOL,decimals})}return {testToken:main?null:addr(env.TEST_TOKEN_CONTRACT),walletConnectProjectId:env.WALLETCONNECT_PROJECT_ID||undefined,network:chain.name,chainId:chain.id,rpcUrls:[env.BASE_RPC_URL||chain.rpcUrls.default.http[0],env.BASE_RPC_FALLBACK].filter(Boolean) as string[],explorer:chain.blockExplorers.default.url,land,marketplace,router,assets,deployed:!!(land&&marketplace&&router),tokens,tokenEnabled:env.TOKEN_ENABLED==='true'};}
export function publicClient(c:Registry){return createPublicClient({chain:c.chainId===8453?base:baseSepolia,transport:fallback(c.rpcUrls.map(url=>http(url,{timeout:10000,retryCount:1})))})}
export const landAbi=parseAbi(['function ownerOf(uint256 id) view returns (address)','function approve(address to,uint256 tokenId)','function getApproved(uint256 id) view returns(address)','function transferVersion(uint256 id) view returns(uint256)','function safeTransferFrom(address from,address to,uint256 id)','event Transfer(address indexed from,address indexed to,uint256 indexed tokenId)']);
export const routerAbi=parseAbi(['function sales(uint256) view returns(address currency,uint256 price,bool open)','function buyLand(uint256 id,address currency,uint256 expectedPrice) payable','event LandPurchased(uint256 indexed landId,address indexed buyer,address currency,uint256 price)']);
export const marketAbi=parseAbi(['function nextListingId() view returns(uint256)','function listings(uint256) view returns(address seller,address asset,uint256 tokenId,address currency,uint256 price,uint256 version,uint256 feeBps,address treasury,bool active)','function list(address asset,uint256 tokenId,address currency,uint256 price) returns(uint256)','function cancel(uint256 id)','function buy(uint256 id,address currency,uint256 expectedPrice) payable','event ListingCreated(uint256 indexed listingId,address indexed seller,address indexed asset,uint256 tokenId,address currency,uint256 price)','event ListingCancelled(uint256 indexed listingId)','event ItemPurchased(uint256 indexed listingId,address indexed buyer,uint256 price,uint256 fee)']);

// RPC credentials used on the server must never be serialized to /api/config.
export function publicRegistry(env:Record<string,string|undefined>){return registry({...env,BASE_RPC_URL:env.PUBLIC_BASE_RPC_URL,BASE_RPC_FALLBACK:env.PUBLIC_BASE_RPC_FALLBACK})}

export function networkForChainId(id:number){if(id===base.id)return 'base-mainnet';if(id===baseSepolia.id)return 'base-sepolia';throw Error('Unsupported account network.');}
