import {db,identity,HttpError,runtimeEnv} from '@/lib/server';
import {session,digest} from '@/lib/auth';
import {quest,verifyDiscord} from '@/lib/social-quests';
export async function GET(req:Request){const origin=new URL(req.url).origin;let message='Discord verification could not be completed. Please retry.',ok=false;try{
 const user=await identity(req),s=await session(req),u=new URL(req.url),state=u.searchParams.get('state')??'';if(!/^[a-f0-9]{64}$/.test(state)||!s)throw new HttpError('Verification expired. Start again.');
 const saved=await db().prepare('DELETE FROM social_oauth_states WHERE hash=? AND user_id=? AND session_hash=? AND origin=? AND expires_at>? RETURNING campaign_id').bind(await digest(state),user,s.hash,origin,Date.now()).first<{campaign_id:string}>();if(!saved)throw new HttpError('Verification expired or was already used. Start again.');if(u.searchParams.has('error'))throw new HttpError('Discord connection cancelled. No points awarded.');const code=u.searchParams.get('code');if(!code||code.length>2000)throw new HttpError('Missing Discord authorization code.');const c=await quest(saved.campaign_id);const e=runtimeEnv();const r=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:e.DISCORD_CLIENT_ID??'',client_secret:e.DISCORD_CLIENT_SECRET??'',grant_type:'authorization_code',code,redirect_uri:origin+'/api/social/discord/callback'}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new HttpError('Discord connection expired. Please retry.');const token=await r.json() as {access_token?:string;scope?:string};if(!token.access_token||!token.scope?.split(' ').includes('guilds.members.read'))throw new HttpError('Discord permissions were not granted.');await verifyDiscord(user,c,token.access_token);ok=true;message='Discord quest verified. Your points are ready.';
 }catch(e){if(e instanceof HttpError)message=e.message;}
 const dest=new URL('/campaigns',origin);dest.searchParams.set('verification',ok?'success':'error');dest.searchParams.set('message',message);return new Response(null,{status:303,headers:{Location:dest.toString(),'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
}
