import {env} from 'cloudflare:workers';
import {hydrateLegacy} from '@/lib/legacy';
import {hydrateNfts} from '@/lib/nft';
import {award,gameAchievements} from '@/lib/leaderboard';
import {readJson,db,identity,json,fail,sameOrigin,HttpError,type PlayerRow} from '@/lib/server';
import {advance,applyMotion,initialState,migrateTown,legacyTitle,type GameState,type Intent} from '@/packages/game-core/world';
import {z} from 'zod';
const action=z.object({type:z.enum(['move','attack','interact','heal','craft','tick','buy_medkit','sell_circuit','upgrade','salvage_quest','bounty_quest','daily_claim','cache','enter','exit','dungeon_enter','equip','unequip','salvage','legacy_claim','legacy_pin','legacy_title','dodge']),dx:z.number().finite().min(-1).max(1).optional(),dy:z.number().finite().min(-1).max(1).optional(),target:z.string().max(30).optional(),scene:z.number().int().min(-1).max(11).optional(),batch:z.string().uuid().optional(),motion:z.array(z.object({dx:z.number().finite().min(-1).max(1),dy:z.number().finite().min(-1).max(1),ms:z.number().finite().min(0).max(40)})).max(150).optional()});
export async function GET(req:Request){try{const id=await identity(req);const p=await db().prepare('SELECT * FROM players WHERE user_id=?').bind(id).first<PlayerRow>();if(!p)return json({character:null});const others=await db().prepare('SELECT username,state FROM players WHERE user_id<>? AND updated_at>? LIMIT 30').bind(id,Date.now()-12000).all<{username:string;state:string}>();const built=await db().prepare('SELECT id,parcel,x,y,rotation,type FROM buildings').all();return json({character:{username:p.username,state:{...await hydrateNfts(id,migrateTown(JSON.parse(p.state))),buildings:built.results},revision:p.revision},players:others.results.map(r=>({username:r.username,title:legacyTitle(JSON.parse(r.state)),x:JSON.parse(r.state).x,y:JSON.parse(r.state).y,interior:JSON.parse(r.state).interior}))});}catch(e){return fail(e)}}
export async function POST(req:Request){try{sameOrigin(req);const id=await identity(req);const settings=await db().prepare("SELECT value FROM site_content WHERE key='game'").first<{value:string}>();if(settings&&JSON.parse(settings.value).maintenance)throw new HttpError(JSON.parse(settings.value).message||'Maintenance in progress.',503);const body=await readJson(req) as Record<string,unknown>;if('userId' in body||'walletAddress' in body||'role' in body)throw new HttpError('Account identity must come from your session.',403);if(body.type==='create'){const registration=await db().prepare('SELECT username FROM registrations WHERE user_id=?').bind(id).first<{username:string}>();const username=registration!.username;const now=Date.now();const existing=await db().prepare('SELECT user_id FROM players WHERE username=? COLLATE NOCASE AND user_id<>?').bind(username,id).first();if(existing)throw new HttpError('That name is already in use.',409);await db().prepare('INSERT INTO players(user_id,username,state,revision,updated_at,created_at) VALUES(?,?,?,0,?,?) ON CONFLICT(user_id) DO NOTHING').bind(id,username,JSON.stringify(initialState()),now,now).run();return GET(req);}
 if(env.REALTIME)throw new HttpError('Connect to the multiplayer server to play.',426);
 const parsed=action.parse(body);const intent=parsed as Intent;const p=await db().prepare('SELECT * FROM players WHERE user_id=?').bind(id).first<PlayerRow>();if(!p)throw new HttpError('Create a character first.',404);const now=Date.now();const previous=await hydrateLegacy(id,await hydrateNfts(id,JSON.parse(p.state) as GameState,parsed.target));if(parsed.batch&&previous.motionBatch===parsed.batch)return json({character:{username:p.username,state:previous,revision:p.revision}});if(now-p.updated_at<80)throw new HttpError('Actions are arriving too quickly.',429);if(parsed.scene!==undefined&&parsed.scene!==(previous.interior??-1))throw new HttpError('Location changed. Reload the game to synchronize.',409);const moved=parsed.motion&&parsed.batch?applyMotion(previous,parsed.motion,now-p.updated_at,parsed.batch):previous;const next=advance(moved,parsed.motion&&intent.type==='move'?{type:'tick'}:intent,now-p.updated_at,now);const writeId=crypto.randomUUID();Object.assign(next,{writeId});const change=next.scrap-previous.scrap;const statements=[db().prepare('UPDATE players SET state=?,revision=revision+1,updated_at=? WHERE user_id=? AND revision=? RETURNING revision').bind(JSON.stringify(next),now,id,p.revision)];if(change)statements.push(db().prepare('INSERT INTO economy(id,user_id,kind,amount,created_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM players WHERE user_id=? AND revision=? AND json_extract(state,\'$.writeId\')=?)').bind(crypto.randomUUID(),id,intent.type,change,now,id,p.revision+1,writeId));for(const a of gameAchievements(previous,next,now))statements.push(award(id,a.category,a.source,now,"EXISTS(SELECT 1 FROM players WHERE user_id=? AND revision=? AND json_extract(state,'$.writeId')=?)",[id,p.revision+1,writeId]));const results=await db().batch(statements);if(!results[0].meta.changes)throw new HttpError('Progress changed in another tab. Please retry.',409);return json({character:{username:p.username,state:next,revision:p.revision+1}});
 }catch(e){if(e instanceof z.ZodError)return json({error:'Check your character name or action.'},400);return fail(e)}}

