'use client';
import {useCallback,useEffect,useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {DAY,type AnalyticsReport} from '@/lib/analytics';
const iso=(n:number)=>new Date(n).toISOString().slice(0,10);
const names:Record<string,string>={path:'Pages',host:'Sites / hosts',referrer:'Referring sites',source:'UTM sources',medium:'UTM mediums',campaign:'Campaigns',country:'Countries',device:'Devices',browser:'Browsers',os:'Operating systems'};
const cell=(v:unknown)=>'"'+String(v??'').replace(/^(?:\s*[=+@-]|[\t\r\n])/,"'$&").replaceAll('"','""')+'"';
export default function AnalyticsAdmin(){
 const [range,setRange]=useState({from:iso(Date.now()-6*DAY),to:iso(Date.now())}),[data,setData]=useState<AnalyticsReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();let active=true,pending=false;
  const load=async()=>{if(pending)return;pending=true;setLoading(true);try{const r=await fetch(`/api/admin/analytics?from=${range.from}&to=${range.to}`,{signal:controller.signal,cache:'no-store'});const body=await r.json() as AnalyticsReport&{error?:string};if(!r.ok)throw Error(body.error??'Could not load analytics.');if(active){setData(body);setError('')}}catch(e){if(active){setError((e as Error).message);setData(null)}}finally{pending=false;if(active)setLoading(false)}};
  setData(null);void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},30000);return()=>{active=false;controller.abort();clearInterval(timer)};
 },[range,refresh]);
 const exportCSV=useCallback(()=>{if(!data)return;const rows:unknown[][]=[['Anonymous page counts',data.traffic.views],['Day','Anonymous views'],...data.traffic.daily.map(d=>[d.day,d.views]),['Host','Page','Anonymous views'],...data.traffic.pages.map(p=>[p.host,p.path,p.views]),[],['Consented analytics'],['Report',data.from,data.to,'UTC'],['Metric','Value'],...Object.entries(data.summary),['Active visitors (last 60s)',data.online],[],['Day','Page views','Unique visitors']];for(const d of data.daily)rows.push([d.day,d.views,d.visitors]);for(const [key,values] of Object.entries(data.breakdowns)){rows.push([],[names[key],'Views','Visitors']);for(const v of values)rows.push([v.label,v.views,v.visitors])}rows.push([],['Latest visits (maximum 100)','Account / visitor','Host','Page','Country','Device','Browser','Referrer','Started UTC','Last seen UTC','Active seconds']);for(const v of data.recent)rows.push([v.id,v.username??`Guest ${v.visitor}`,v.host,v.path,v.country,v.device,v.browser,v.referrer,new Date(v.started_at).toISOString(),new Date(v.last_seen).toISOString(),v.active_seconds]);const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`tpu-analytics-${data.from}-${data.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},[data]);
 const days:AnalyticsReport['daily']=[];if(data)for(let d=Date.parse(data.from);d<=Date.parse(data.to);d+=DAY)days.push(data.daily.find(v=>v.day===iso(d))??{day:iso(d),views:0,visitors:0});
 return <section className="analytics-dashboard"><div className="analytics-toolbar"><div><h2>VISITOR ANALYTICS</h2><p>Traffic and engagement · UTC · updates every 30 seconds</p></div><button className="btn outline" disabled={loading} onClick={()=>setRefresh(v=>v+1)}>REFRESH</button><button className="btn outline" disabled={!data} onClick={exportCSV}>EXPORT CSV</button></div><div className="analytics-toolbar">{[1,7,30,90].map(n=><button className="btn outline" key={n} onClick={()=>setRange({from:iso(Date.now()-(n-1)*DAY),to:iso(Date.now())})}>{n===1?'TODAY':`${n} DAYS`}</button>)}<label>From<input aria-label="Analytics from date" type="date" min={iso(Date.now()-89*DAY)} max={range.to} value={range.from} onChange={e=>setRange(v=>({...v,from:e.target.value}))}/></label><label>To<input aria-label="Analytics to date" type="date" min={range.from} max={iso(Date.now())} value={range.to} onChange={e=>setRange(v=>({...v,to:e.target.value}))}/></label></div>
 {error&&<p role="alert" className="error">{error}</p>}{loading&&!data&&<p role="status">Loading visit statistics…</p>}
 {data&&<> <article className="profile-card"><h3>ANONYMOUS PAGE VIEWS · {data.traffic.views}</h3><p>Daily page counts without cookies or visitor identifiers. These are views, not unique people. Counts include consenting visits; do not add them to the consented totals below.</p><div className="analytics-table"><table><thead><tr><th>Site</th><th>Page</th><th>Views</th></tr></thead><tbody>{data.traffic.pages.map(p=><tr key={p.host+p.path}><td>{p.host}</td><td>{p.path}</td><td>{p.views}</td></tr>)}</tbody></table></div><details><summary>Daily anonymous counts</summary>{data.traffic.daily.map(d=><p key={d.day}>{d.day}: {d.views}</p>)}</details></article><h3>CONSENTED VISITOR ANALYTICS</h3>
<div className="admin-stats">{Object.entries({'Active now (60s)':data.online,'Page views':data.summary.views,'Unique browsers':data.summary.visitors,'Sessions':data.summary.sessions,'Signed-in visitors':data.summary.authenticated,'Visited /game':data.summary.gameVisitors,'Avg active seconds / view':data.summary.views?Math.round(data.summary.activeSeconds/data.summary.views):0,'Single-page sessions':data.summary.sessions?`${Math.round(data.summary.singlePageSessions/data.summary.sessions*100)}%`:'0%'}).map(([label,value])=><article className="profile-card" key={label}><span className="eyebrow muted">{label}</span><strong>{value}</strong></article>)}</div>

 {!data.summary.views&&<p className="admin-notice">No consented visits in this period. Statistics start after deployment and database migration. Administrator visits are excluded.</p>}
 <article className="profile-card"><h3>DAILY TRAFFIC</h3><div style={{height:280,width:'100%',minWidth:0}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={days}><CartesianGrid stroke="#30444c" strokeDasharray="3 3"/><XAxis dataKey="day" tick={{fontSize:11,fill:'#bed1d3'}}/><YAxis allowDecimals={false} tick={{fill:'#bed1d3'}}/><Tooltip contentStyle={{background:'#101d25',borderColor:'#527077'}}/><Legend/><Area type="monotone" dataKey="views" name="Page views" stroke="#c8f76b" fill="#c8f76b" fillOpacity={.15}/><Area type="monotone" dataKey="visitors" name="Unique browsers" stroke="#65e4ee" fill="#65e4ee" fillOpacity={.1}/></AreaChart></ResponsiveContainer></div><details><summary>View daily numbers</summary><div className="analytics-table"><table><thead><tr><th>Day (UTC)</th><th>Views</th><th>Visitors</th></tr></thead><tbody>{days.map(d=><tr key={d.day}><td>{d.day}</td><td>{d.views}</td><td>{d.visitors}</td></tr>)}</tbody></table></div></details></article>
 <div className="analytics-breakdowns">{Object.entries(names).map(([key,title])=><article className="profile-card" key={key}><h3>{title.toUpperCase()} · TOP 20</h3><div className="analytics-table"><table><thead><tr><th>{title}</th><th>Views</th><th>Visitors</th></tr></thead><tbody>{data.breakdowns[key]?.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.views}</td><td>{r.visitors}</td></tr>)}</tbody></table>{!data.breakdowns[key]?.length&&<p>No data yet.</p>}</div></article>)}</div>
 <article className="profile-card"><h3>LATEST VISITS · LAST 100</h3><div className="analytics-table"><table><thead><tr>{['Visitor / account','Page','Country','Device / browser','Source','Started (UTC)','Last seen (UTC)','Active time'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.recent.map(v=><tr key={v.id}><td>{v.username??`Guest ${v.visitor}`}</td><td>{v.host}{v.path}</td><td>{v.country}</td><td>{v.device} / {v.browser}</td><td>{v.referrer}</td><td>{new Date(v.started_at).toISOString().replace('T',' ').slice(0,19)}</td><td>{new Date(v.last_seen).toISOString().replace('T',' ').slice(0,19)}</td><td>{v.active_seconds}s</td></tr>)}</tbody></table></div></article>
 <p className="small-note">Consented traffic only; known bots, administrators and privacy signals are excluded. Unique browsers are counted separately per site origin and device. Sessions are per tab, renewed on the next page visit after 30 minutes without a recorded event. Active time is sampled while visible and recently used; /game visits do not prove gameplay. Single-page sessions are calculated within the selected period. Country comes from Cloudflare and may reflect a VPN. Raw IP addresses, full user agents, URL queries and wallet addresses are not stored in visit records. Retention: 90 days. Last updated: {new Date(data.generatedAt).toISOString()}.</p></>}
 </section>;
}
