'use client';
import {createContext,useCallback,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {toHex,type Address,type EIP1193Provider} from 'viem';
import type {Registry} from '@/packages/blockchain/config';
import {activeAccount,activeChain,activeProvider,browserProvider,connectProvider,attachProvider,detachProvider,readProvider,switchNetwork,walletError} from '@/lib/wallet-client';
type User={id:string;username:string;role:string;status:string;wallet:{address:Address;chainId:number}};
type AuthData={networkVerified:boolean;authenticated:boolean;user:User|null;pendingWallet:Address|null};
type Phase='INITIALIZING'|'UNAUTHENTICATED'|'WALLET_CONNECTED'|'SIGNING'|'AUTHENTICATING'|'AUTHENTICATED'|'ERROR';
type Context=AuthData&{phase:Phase;initializing:boolean;busy:boolean;error:string;config:Registry|null;account:Address|null;chain:number|null;mismatch:boolean;connect:(kind:'injected'|'base'|'walletconnect')=>Promise<void>;signIn:()=>Promise<void>;register:(username:string,consent:boolean,referral?:string)=>Promise<void>;logout:()=>Promise<void>;reload:()=>Promise<void>;disconnect:()=>void;switchChain:()=>Promise<void>};
const empty:AuthData={networkVerified:false,authenticated:false,user:null,pendingWallet:null};
const AuthContext=createContext<Context|null>(null);
export function useAuth(){const value=useContext(AuthContext);if(!value)throw Error('AuthProvider is required.');return value;}
async function api<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/auth/'+path,{cache:'no-store',credentials:'same-origin',...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json() as T & {error?:string};if(!r.ok)throw Object.assign(Error(d.error||'Authentication service unavailable.'),{status:r.status});return d;}
export function AuthProvider({children}:{children:ReactNode}){const [data,setData]=useState<AuthData>(empty),[initializing,setInitializing]=useState(true),[phase,setPhase]=useState<Phase>('INITIALIZING'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[config,setConfig]=useState<Registry|null>(null),[account,setAccount]=useState<Address|null>(null),[chain,setChain]=useState<number|null>(null);const lock=useRef(false),generation=useRef(0),channel=useRef<BroadcastChannel|null>(null),current=useRef(data);current.current=data;
 const apply=useCallback((d:AuthData)=>{setData(d);setPhase(d.authenticated?'AUTHENTICATED':activeAccount?'WALLET_CONNECTED':'UNAUTHENTICATED');setInitializing(false)},[]);
 const reload=useCallback(async()=>{const n=++generation.current;try{const d=await api<AuthData>('me');if(n===generation.current){apply(d);setError('')}}catch(e){if(n!==generation.current)return;apply(empty);setError(walletError(e));setPhase('ERROR')}},[apply]);
 const announce=()=>{channel.current?.postMessage('changed');try{localStorage.setItem('tpu-auth-event',crypto.randomUUID())}catch{}};
 useEffect(()=>{let alive=true;void reload();fetch('/api/config').then(r=>{if(!r.ok)throw Error('Network configuration unavailable.');return r.json() as Promise<Registry>}).then(c=>{if(alive)setConfig(c)}).catch(e=>{if(alive)setError(walletError(e))});const wallet=()=>{setAccount(activeAccount);setChain(activeChain)};window.addEventListener('tpu-wallet',wallet);void browserProvider().then(provider=>{if(alive&&!lock.current&&!activeProvider){attachProvider(provider);void readProvider().catch(()=>{})}}).catch(()=>{});const resync=()=>{void reload()};if(typeof BroadcastChannel!=='undefined'){channel.current=new BroadcastChannel('tpu-auth');channel.current.onmessage=resync}const storage=(e:StorageEvent)=>{if(e.key==='tpu-auth-event')resync()};window.addEventListener('storage',storage);window.addEventListener('focus',resync);window.addEventListener('tpu-auth-expired',resync);const timer=setInterval(()=>{if(document.visibilityState==='visible')resync()},30000);const renewal=setInterval(()=>{if(current.current.authenticated&&document.visibilityState==='visible')void api<AuthData>('refresh',{}).then(resync).catch(resync)},300000);return()=>{alive=false;++generation.current;window.removeEventListener('tpu-wallet',wallet);window.removeEventListener('storage',storage);window.removeEventListener('focus',resync);window.removeEventListener('tpu-auth-expired',resync);channel.current?.close();clearInterval(timer);clearInterval(renewal);detachProvider()}},[reload,apply]);
 async function operation(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError(walletError(e));setPhase('ERROR')}finally{lock.current=false;setBusy(false)}}
 async function connect(kind:'injected'|'base'|'walletconnect'){await operation(async()=>{if(!config)throw Error('Network configuration unavailable.');let provider:EIP1193Provider;if(kind==='base'){const {createBaseAccountSDK}=await import('@base-org/account');provider=createBaseAccountSDK({appName:'Trash Panda United',appChainIds:[config.chainId]}).getProvider() as EIP1193Provider}else if(kind==='walletconnect'){if(!config.walletConnectProjectId)throw Error('WalletConnect is not configured. Use a browser wallet or Base Account.');const {EthereumProvider}=await import('@walletconnect/ethereum-provider');const wc=await EthereumProvider.init({projectId:config.walletConnectProjectId,chains:[config.chainId],showQrModal:true,rpcMap:{[config.chainId]:config.rpcUrls[0]},metadata:{name:'Trash Panda United',description:'Sign in to Trash Town',url:window.location.origin,icons:[window.location.origin+'/favicon.svg']}});provider=wc as unknown as EIP1193Provider}else{provider=await browserProvider()}await connectProvider(provider,config);setPhase(current.current.authenticated?'AUTHENTICATED':'WALLET_CONNECTED')})}
 async function signIn(){await operation(async()=>{if(!config||!activeProvider||!activeAccount)throw Error('Connect your wallet first.');await switchNetwork(config);const provider=activeProvider,address=activeAccount;const challenge=await api<{id:string;message:string}>('nonce',{address,chainId:config.chainId});setPhase('SIGNING');const signature=await provider.request({method:'personal_sign',params:[toHex(challenge.message),address]});await readProvider();if(provider!==activeProvider||address.toLowerCase()!==activeAccount?.toLowerCase()||activeChain!==config.chainId)throw Error('Wallet or network changed during signing. Try again.');setPhase('AUTHENTICATING');await api('wallet',{id:challenge.id,address,signature});await reload();announce()})}
 async function register(username:string,consent:boolean,referral?:string){await operation(async()=>{setPhase('AUTHENTICATING');await api('register',{username,consent,...(referral?{referral}:{})});await reload();announce()})}
 async function logout(){await operation(async()=>{++generation.current;await api('logout',{});++generation.current;apply(empty);announce()})}
 const mismatch=!!(data.user&&account&&data.user.wallet.address.toLowerCase()!==account.toLowerCase());
 return <AuthContext.Provider value={{...data,phase,initializing,busy,error,config,account,chain,mismatch,connect,signIn,register,logout,reload,disconnect:detachProvider,switchChain:()=>operation(async()=>{if(config)await switchNetwork(config)})}}>{children}</AuthContext.Provider>;
}
