'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Header from './header';
import {formatEther} from 'viem';
import styles from './campaigns.module.css';
import {QUEST_METHODS} from './quest-config-fields';
type Campaign={id:string;kind:string;title:string;description:string;url:string;status:string;starts_at:number;ends_at:number;points:number;min_points:number;amount_wei:string;verification:string;threshold:number;chain_id:number;target:string;requirement_amount:string;token_id:string};
type Submission={campaign_id:string;status:string;note:string};
type Allocation={campaign_id:string;status:string;wallet:string;amount_wei:string;tx_hash?:string};
type Data={campaigns:Campaign[];submissions:Submission[];allocations:Allocation[];points:{total:number};accounts:{provider:string;display_name:string}[];discordReady:boolean;discordAutoReady:boolean;checks:{campaign_id:string;status:string;message:string;progress:string|null;checked_at:number}[]};
const modes:Record<string,string>=QUEST_METHODS;
function progressLabel(raw:string|null|undefined){
 if(!raw)return '';try{const p=JSON.parse(raw);if(p&&['string','number'].includes(typeof p.current)&&['string','number'].includes(typeof p.required))return `${p.current} / ${p.required}`;}catch{}return '';
}
export default function Campaigns(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[feedback,setFeedback]=useState<Record<string,string>>({}),[clock,setClock]=useState(Date.now());const automatic=useRef(false),requestLock=useRef(false),lastCheck=useRef(0);
 const load=useCallback(async()=>{const r=await fetch('/api/campaigns');const d=await r.json() as Data&{error:string};if(!r.ok)throw Error(d.error);setData(d);setFeedback({});return d;},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));const q=new URLSearchParams(location.search);if(q.has('verification')){setNotice((q.get('message')??'Verification finished.').slice(0,250));history.replaceState(null,'','/campaigns');}const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer);},[load]);
 const act=useCallback(async(action:string,id:string,evidence?:string)=>{if(requestLock.current)return;requestLock.current=true;setBusy(id);setError('');try{const r=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,evidence})});const d=await r.json() as Data&{error:string;message?:string;progress?:{current:number;required:number}};if(!r.ok)throw Error(d.error);setFeedback(f=>({...f,[id]:d.message?d.message+(d.progress?` (${d.progress.current}/${d.progress.required})`:''):action==='claim'?'Allocation claim recorded.':'Saved. Your submission is awaiting review.'}));await load();}catch(e){setError((e as Error).message);}finally{requestLock.current=false;setBusy('');}},[load]);
 const checkAll=useCallback(async()=>{
  if(requestLock.current||document.hidden)return;
  requestLock.current=true;lastCheck.current=Date.now();setBusy('all');setError('');
  try{const r=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify_all'})});const d=await r.json() as {error?:string;checked:number;verified:number;results:{id:string;message:string}[]};if(!r.ok)throw Error(d.error||'Verification unavailable.');setNotice(d.checked?`Checked ${d.checked} missions · ${d.verified} completed. Remaining missions are checked in following passes.`:'All eligible missions are up to date.');setFeedback(f=>({...f,...Object.fromEntries(d.results.map(r=>[r.id,r.message]))}));await load();}
  catch(e){setError((e as Error).message);}finally{requestLock.current=false;setBusy('');}
 },[load]);
 // Bounded server batches resume while the board is visible and on return.
 useEffect(()=>{if(!data)return;const run=()=>{if(!document.hidden&&Date.now()-lastCheck.current>=60000)void checkAll();};if(!automatic.current){automatic.current=true;run();}const timer=setInterval(run,60000);window.addEventListener('focus',run);document.addEventListener('visibilitychange',run);return()=>{clearInterval(timer);window.removeEventListener('focus',run);document.removeEventListener('visibilitychange',run);};},[!!data,checkAll]);
 async function discord(id:string){if(requestLock.current)return;requestLock.current=true;setBusy(id);setError('');try{const r=await fetch('/api/social/discord',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json() as {url:string;error:string};if(!r.ok)throw Error(d.error);location.assign(d.url);}catch(e){setError((e as Error).message);requestLock.current=false;setBusy('');}}
 const approved=data?.submissions.filter(s=>s.status==='approved').length??0,pending=data?.submissions.filter(s=>s.status==='pending').length??0;
 return <><Header/><main className={`subpage ${styles.board}`}><div className="eyebrow lime-text">COMMUNITY MISSIONS / TRASH PANDA UNITED</div><h1>MAKE YOUR <em>MARK.</em></h1><p>Build your reputation through verified missions. Community points are separate from capped season points and do not guarantee tokens or payments.</p><a href="/program" className="text-link">SEASON RULES & FOUNDER PROGRAM →</a>
 <div className={styles.stats}><div><strong>{data?.points.total??'—'}</strong><span>COMMUNITY POINTS</span></div><div><strong>{approved}</strong><span>COMPLETED</span></div><div><strong>{pending}</strong><span>IN REVIEW</span></div></div>
 {notice&&<p className={styles.notice} role="status">{notice}</p>}{error&&<div className="error" role="alert">{error}<button disabled={!!busy} onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>RETRY</button><a href="/register">MY ACCOUNT</a></div>}
 <div className={styles.connection}><span>DISCORD</span><strong>{data?.accounts.find(a=>a.provider==='discord')?.display_name??'Not connected'}</strong><small>{data?.discordAutoReady?'Connect once through a Discord mission. Membership and roles are rechecked automatically.':'Connect through a Discord mission. The team can enable automatic rechecks by configuring its bot.'} One Discord account per player.</small></div>
 <section className={styles.connection} aria-label="Automatic verification"><strong>AUTOMATIC MISSION CHECKS</strong><button className="btn lime" disabled={!data||!!busy} onClick={()=>void checkAll()}>{busy==='all'?'CHECKING…':'CHECK ALL MISSIONS'}</button><small>The server checks missions in batches even when this page is closed. Opening the board checks up to four missions every minute. Busy periods can delay checks. Points are credited once; verification never requests a wallet transaction.</small></section>
 <div className={styles.toolbar}><label>SEARCH MISSIONS<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find your next mission…"/></label><label>SHOW<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All missions</option><option value="open">Available</option><option value="approved">Completed</option><option value="pending">In review</option><option value="automatic">Automatic missions</option><option value="web3">Web3 missions</option><option value="airdrop">Test ETH allocations</option></select></label></div>
 {!data&&!error&&<p role="status">Loading missions…</p>}
 <div className={styles.grid}>{data?.campaigns.filter(c=>{const s=data.submissions.find(s=>s.campaign_id===c.id),open=c.status==='active'&&clock>=c.starts_at&&clock<c.ends_at;return (c.title+' '+c.description).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='automatic'&&c.kind==='social'&&c.verification!=='manual'||filter==='web3'&&['wallet_verified','native_balance','erc20_balance','erc721_balance','erc1155_balance'].includes(c.verification)||filter==='open'&&open&&s?.status!=='approved'||filter===s?.status||filter==='airdrop'&&c.kind==='airdrop');}).map(c=>{const s=data.submissions.find(s=>s.campaign_id===c.id),a=data.allocations.find(a=>a.campaign_id===c.id),open=c.status==='active'&&clock>=c.starts_at&&clock<c.ends_at,done=s?.status==='approved',isDiscord=c.verification.startsWith('discord_'),check=data.checks?.find(q=>q.campaign_id===c.id),web3=['wallet_verified','native_balance','erc20_balance','erc721_balance','erc1155_balance'].includes(c.verification);return <article className={styles.card} key={c.id}>
 <div className={styles.cardTop}><span className="tag">{c.kind==='social'?modes[c.verification]??'PROOF REVIEW':'BASE SEPOLIA'}</span><strong>{c.kind==='social'?`+${c.points} PTS`:`${formatEther(BigInt(c.amount_wei))} test ETH`}</strong></div>
 <h2>{c.title}</h2><p>{c.description}</p>{web3&&<p className={styles.note}>{c.chain_id===8453?'Base mainnet':'Base Sepolia testnet'}{c.verification!=='wallet_verified'&&` · Minimum: ${c.requirement_amount}`}{c.target&&<> · <a className="text-link" href={`https://${c.chain_id===8453?'':'sepolia.'}basescan.org/address/${c.target}`} target="_blank" rel="noopener noreferrer">VIEW CONTRACT ↗</a></>}{c.verification==='erc1155_balance'&&` · Item #${c.token_id}`}</p>}<span className={styles.status}>{done?'✓ COMPLETED':s?.status==='pending'?'◷ IN REVIEW':!open?(clock<c.starts_at&&c.status==='active'?'UPCOMING':'CLOSED'):s?.status==='rejected'?'CHANGES REQUESTED':'AVAILABLE'}</span>
 <small>{new Date(c.starts_at).toLocaleString()} — {new Date(c.ends_at).toLocaleString()}</small>
 {c.url&&<a className="btn outline" href={c.url} target="_blank" rel="noopener noreferrer">OPEN TASK ↗</a>}
 {check&&!done&&!feedback[c.id]&&<p className={styles.note} role="status">{check.message}{progressLabel(check.progress)&&<> · {progressLabel(check.progress)}</>}</p>}{s?.note&&<p className={styles.note}>{s.note}</p>}{feedback[c.id]&&!done&&<p className={styles.note} role="status">{feedback[c.id]}</p>}
 {c.kind==='social'&&open&&!done&&(c.verification==='manual'?s?.status!=='pending'&&<form onSubmit={e=>{e.preventDefault();act('submit',c.id,String(new FormData(e.currentTarget).get('evidence')));}}><label>PROOF LINK OR DESCRIPTION<textarea name="evidence" required minLength={8} maxLength={1000} placeholder="Include a public link and explain how it meets the mission requirements."/></label><button disabled={!!busy} className="btn lime">{busy===c.id?'SUBMITTING…':'SUBMIT PROOF'}</button><small>A moderator checks this task. Rejected proof can be corrected and resubmitted.</small></form>:isDiscord?<>{data.discordAutoReady&&data.accounts.some(a=>a.provider==='discord')&&<button className="btn outline" disabled={!!busy} onClick={()=>act('verify',c.id)}>VERIFY LINKED DISCORD</button>}<button className="btn lime" disabled={!!busy||!data.discordReady} onClick={()=>discord(c.id)}>{busy===c.id?'CONNECTING…':'CONNECT & VERIFY DISCORD'}</button><small>{data.discordReady?'Join the server first. Discord will ask permission to confirm your membership and role.':'Discord verification is awaiting activation by the team.'}</small></>:<button className="btn lime" disabled={!!busy} onClick={()=>act('verify',c.id)}>{busy===c.id?'CHECKING…':'VERIFY MISSION'}</button>)}
 {c.kind==='airdrop'&&<><p className="small-note">Snapshot eligibility: {c.min_points} community points. Claiming requests the reserved payment; an administrator signs it separately.</p>{!a?<p>No allocation in this snapshot.</p>:<><p>{a.status.toUpperCase()} · {a.wallet.slice(0,8)}…{a.wallet.slice(-6)}</p>{a.status==='eligible'&&open&&<button disabled={!!busy} className="btn lime" onClick={()=>act('claim',c.id)}>CLAIM ALLOCATION</button>}{a.tx_hash&&<a href={`https://sepolia.basescan.org/tx/${a.tx_hash}`} target="_blank" rel="noopener noreferrer">VIEW TRANSACTION ↗</a>}</>}</>}
 </article>;})}</div>{data&&!data.campaigns.length&&<p className="empty-state">Your next mission is on its way. Check back soon.</p>}
 </main></>;
}
