'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Header from './header';
import {formatEther} from 'viem';
import styles from './campaigns.module.css';
type Campaign={id:string;kind:string;title:string;description:string;url:string;status:string;starts_at:number;ends_at:number;points:number;min_points:number;amount_wei:string;verification:string;threshold:number};
type Submission={campaign_id:string;status:string;note:string};
type Allocation={campaign_id:string;status:string;wallet:string;amount_wei:string;tx_hash?:string};
type Data={campaigns:Campaign[];submissions:Submission[];allocations:Allocation[];points:{total:number};accounts:{provider:string;display_name:string}[];discordReady:boolean};
const modes:Record<string,string>={manual:'PROOF REVIEW',discord_member:'DISCORD MEMBERSHIP',discord_role:'DISCORD ROLE',game_level:'PLAYER LEVEL',tutorial:'GETTING STARTED'};
export default function Campaigns(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[feedback,setFeedback]=useState<Record<string,string>>({}),[clock,setClock]=useState(Date.now());const automatic=useRef(false);
 const load=useCallback(async()=>{const r=await fetch('/api/campaigns');const d=await r.json() as Data&{error:string};if(!r.ok)throw Error(d.error);setData(d);return d;},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));const q=new URLSearchParams(location.search);if(q.has('verification')){setNotice((q.get('message')??'Verification finished.').slice(0,250));history.replaceState(null,'','/campaigns');}const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer);},[load]);
 const act=useCallback(async(action:string,id:string,evidence?:string)=>{setBusy(id);setError('');try{const r=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,evidence})});const d=await r.json() as Data&{error:string;message?:string;progress?:{current:number;required:number}};if(!r.ok)throw Error(d.error);setFeedback(f=>({...f,[id]:d.message?d.message+(d.progress?` (${d.progress.current}/${d.progress.required})`:''):'Saved. Your submission is awaiting review.'}));await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}},[load]);
 // One bounded pass on opening the mission board; no background polling or provider spam.
 useEffect(()=>{if(!data||automatic.current)return;automatic.current=true;const eligible=data.campaigns.filter(c=>['game_level','tutorial'].includes(c.verification)&&c.status==='active'&&c.starts_at<=Date.now()&&c.ends_at>Date.now()&&!data.submissions.some(s=>s.campaign_id===c.id&&s.status==='approved')).slice(0,5);let cancelled=false;void(async()=>{for(const c of eligible){if(cancelled)break;await act('verify',c.id);}})();return()=>{cancelled=true;};},[!!data,act]);
 async function discord(id:string){setBusy(id);setError('');try{const r=await fetch('/api/social/discord',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json() as {url:string;error:string};if(!r.ok)throw Error(d.error);location.assign(d.url);}catch(e){setError((e as Error).message);setBusy('');}}
 const approved=data?.submissions.filter(s=>s.status==='approved').length??0,pending=data?.submissions.filter(s=>s.status==='pending').length??0;
 return <><Header/><main className={`subpage ${styles.board}`}><div className="eyebrow lime-text">COMMUNITY MISSIONS / TRASH PANDA UNITED</div><h1>MAKE YOUR <em>MARK.</em></h1><p>Build your reputation through verified missions. Community points are separate from capped season points and do not guarantee tokens or payments.</p><a href="/program" className="text-link">SEASON RULES & FOUNDER PROGRAM →</a>
 <div className={styles.stats}><div><strong>{data?.points.total??'—'}</strong><span>COMMUNITY POINTS</span></div><div><strong>{approved}</strong><span>COMPLETED</span></div><div><strong>{pending}</strong><span>IN REVIEW</span></div></div>
 {notice&&<p className={styles.notice} role="status">{notice}</p>}{error&&<div className="error" role="alert">{error}<button disabled={!!busy} onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>RETRY</button><a href="/register">MY ACCOUNT</a></div>}
 <div className={styles.connection}><span>DISCORD</span><strong>{data?.accounts.find(a=>a.provider==='discord')?.display_name??'Not connected'}</strong><small>Connect through a Discord mission to confirm membership. One Discord account per player.</small></div>
 <div className={styles.toolbar}><label>SEARCH MISSIONS<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find your next mission…"/></label><label>SHOW<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All missions</option><option value="open">Available</option><option value="approved">Completed</option><option value="pending">In review</option><option value="airdrop">Test ETH allocations</option></select></label></div>
 {!data&&!error&&<p role="status">Loading missions…</p>}
 <div className={styles.grid}>{data?.campaigns.filter(c=>{const s=data.submissions.find(s=>s.campaign_id===c.id),open=c.status==='active'&&clock>=c.starts_at&&clock<c.ends_at;return (c.title+' '+c.description).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='open'&&open&&s?.status!=='approved'||filter===s?.status||filter==='airdrop'&&c.kind==='airdrop');}).map(c=>{const s=data.submissions.find(s=>s.campaign_id===c.id),a=data.allocations.find(a=>a.campaign_id===c.id),open=c.status==='active'&&clock>=c.starts_at&&clock<c.ends_at,done=s?.status==='approved',isDiscord=c.verification.startsWith('discord_');return <article className={styles.card} key={c.id}>
 <div className={styles.cardTop}><span className="tag">{c.kind==='social'?modes[c.verification]??'PROOF REVIEW':'BASE SEPOLIA'}</span><strong>{c.kind==='social'?`+${c.points} PTS`:`${formatEther(BigInt(c.amount_wei))} test ETH`}</strong></div>
 <h2>{c.title}</h2><p>{c.description}</p><span className={styles.status}>{done?'✓ COMPLETED':s?.status==='pending'?'◷ IN REVIEW':!open?(clock<c.starts_at&&c.status==='active'?'UPCOMING':'CLOSED'):s?.status==='rejected'?'CHANGES REQUESTED':'AVAILABLE'}</span>
 <small>{new Date(c.starts_at).toLocaleString()} — {new Date(c.ends_at).toLocaleString()}</small>
 {c.url&&<a className="btn outline" href={c.url} target="_blank" rel="noopener noreferrer">OPEN TASK ↗</a>}
 {s?.note&&<p className={styles.note}>{s.note}</p>}{feedback[c.id]&&<p className={styles.note} role="status">{feedback[c.id]}</p>}
 {c.kind==='social'&&open&&!done&&(c.verification==='manual'?s?.status!=='pending'&&<form onSubmit={e=>{e.preventDefault();act('submit',c.id,String(new FormData(e.currentTarget).get('evidence')));}}><label>PROOF LINK OR DESCRIPTION<textarea name="evidence" required minLength={8} maxLength={1000} placeholder="Include a public link and explain how it meets the mission requirements."/></label><button disabled={!!busy} className="btn lime">{busy===c.id?'SUBMITTING…':'SUBMIT PROOF'}</button><small>A moderator checks this task. Rejected proof can be corrected and resubmitted.</small></form>:isDiscord?<><button className="btn lime" disabled={!!busy||!data.discordReady} onClick={()=>discord(c.id)}>{busy===c.id?'CONNECTING…':'CONNECT & VERIFY DISCORD'}</button><small>{data.discordReady?'Join the server first. Discord will ask permission to confirm your membership and role.':'Discord verification is awaiting activation by the team.'}</small></>:<button className="btn lime" disabled={!!busy} onClick={()=>act('verify',c.id)}>{busy===c.id?'CHECKING…':'CHECK GAME PROGRESS'}</button>)}
 {c.kind==='airdrop'&&<><p className="small-note">Snapshot eligibility: {c.min_points} community points. Claiming requests the reserved payment; an administrator signs it separately.</p>{!a?<p>No allocation in this snapshot.</p>:<><p>{a.status.toUpperCase()} · {a.wallet.slice(0,8)}…{a.wallet.slice(-6)}</p>{a.status==='eligible'&&open&&<button disabled={!!busy} className="btn lime" onClick={()=>act('claim',c.id)}>CLAIM ALLOCATION</button>}{a.tx_hash&&<a href={`https://sepolia.basescan.org/tx/${a.tx_hash}`} target="_blank" rel="noopener noreferrer">VIEW TRANSACTION ↗</a>}</>}</>}
 </article>;})}</div>{data&&!data.campaigns.length&&<p className="empty-state">Your next mission is on its way. Check back soon.</p>}
 </main></>;
}
