'use client';
import {useEffect,useState} from 'react';
import {formatUnits,parseUnits} from 'viem';
import {type Registry} from '@/packages/blockchain/config';
import {decorAbi} from '@/packages/blockchain/decorations';
import {execute,approval,type TxRequest} from '@/packages/blockchain/transactions';
import {walletError} from '@/lib/wallet-client';
import type {Decoration} from '@/lib/decorations';
import {useAuth} from './auth-provider';
type Item=Decoration&{owned:boolean;open:boolean;price:string;currency:`0x${string}`};
export default function DecorationShop({admin=false,onSelect}:{admin?:boolean;onSelect?:(item:Item)=>void}){
 const a=useAuth();const [items,setItems]=useState<Item[]>([]),[config,setConfig]=useState<Registry|null>(null),[page,setPage]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[hash,setHash]=useState(''),[price,setPrice]=useState('100');
 const [form,setForm]=useState({name:'Neon decoration',description:'A collectible decoration for your parcel.',image:'/assets/decorations/bench.png',rarity:'common',width:2,height:1});
 async function load(){const r=await fetch(admin?'/api/admin/decorations':`/api/decorations?page=${page}`);const d=await r.json() as {error:string;items:Item[];config:Registry;hasMore?:boolean};if(!r.ok)throw Error(d.error);setItems(d.items);setConfig(d.config);setMore(d.hasMore??false)}
 useEffect(()=>{setItems([]);load().catch(e=>setError(walletError(e)))},[page,admin,a.account]);
 async function post(body:unknown){const r=await fetch('/api/admin/decorations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);await load()}
 async function act(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');setHash('');try{await fn()}catch(e){setError(walletError(e))}finally{setBusy(false)}}
 function purchase(i:Item):TxRequest{return {address:i.contract,abi:decorAbi,functionName:'buy',args:[BigInt(i.id),i.currency,BigInt(i.price)],currency:i.currency,amount:BigInt(i.price)}}
 return <section><h2>{admin?'DECORATION STUDIO':'DECORATIONS & MY NFTS'}</h2><p>Each decoration is a separate NFT. It stays in your wallet when land is sold. One NFT can be placed on one parcel at a time.</p>{!config?.decorations&&<p className="notice">The decoration collection has not been connected yet.</p>}{admin&&<form onSubmit={e=>{e.preventDefault();act(()=>post({action:'create',...form}))}} className="profile-card"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Image URL<input value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/></label><p>Bundled art: /assets/decorations/bench.png, planter.png, barrel.png. You can also use an HTTPS image or an uploaded NFT artwork URL.</p><label>Rarity<select value={form.rarity} onChange={e=>setForm({...form,rarity:e.target.value})}>{['common','uncommon','rare','epic','legendary','mythic'].map(v=><option key={v}>{v}</option>)}</select></label><label>Width (tiles)<input type="number" min="1" max="4" value={form.width} onChange={e=>setForm({...form,width:Number(e.target.value)})}/></label><label>Height (tiles)<input type="number" min="1" max="4" value={form.height} onChange={e=>setForm({...form,height:Number(e.target.value)})}/></label><button disabled={busy||!config?.decorations} className="btn lime">CREATE DRAFT</button><p>Each draft is one unique NFT. Published definitions are immutable. Create another draft for another copy.</p></form>}{admin&&<label>Sale price ({config?.tokens[0]?.symbol??'token'})<input type="number" min="0.000001" value={price} onChange={e=>setPrice(e.target.value)}/></label>}
 {error&&<p className="error" role="alert">{error}</p>}{status&&<p role="status">{status}</p>}{hash&&config&&<a href={`${config.explorer}/tx/${hash}`} target="_blank" rel="noreferrer">VIEW TRANSACTION</a>}
 <div className="decor-cards">{items.map(i=><article className="profile-card" key={i.id}><img src={i.image} alt={i.name} style={{width:120,height:110,objectFit:'contain',imageRendering:'pixelated'}}/><h3>{i.name} #{i.id}</h3><p>{i.rarity} · {i.width} × {i.height} tiles</p>{admin?<><p>{i.status}</p>{i.status==='draft'&&<><button disabled={busy||!config?.tokens.length} className="btn outline" onClick={()=>act(async()=>{const t=config!.tokens[0];const amount=parseUnits(price,t.decimals);if(amount<=0n)throw Error('Enter a positive price.');await execute(config!,{address:i.contract,abi:decorAbi,functionName:'configureSale',args:[BigInt(i.id),t.address,amount,true]},setStatus,setHash)})}>1. CONFIGURE SALE IN WALLET</button><button disabled={busy} className="btn lime" onClick={()=>act(()=>post({action:'publish',id:i.id}))}>2. PUBLISH</button></>}</>:i.owned?<><strong>OWNED</strong>{onSelect&&<button disabled={busy} className="btn lime" onClick={()=>onSelect(i)}>PLACE ON THIS PARCEL</button>}</>:i.open?<><p>{formatUnits(BigInt(i.price),config?.tokens.find(t=>t.address.toLowerCase()===i.currency.toLowerCase())?.decimals??18)} {config?.tokens.find(t=>t.address.toLowerCase()===i.currency.toLowerCase())?.symbol??i.currency}</p><button className="btn outline" disabled={busy||!a.authenticated||a.mismatch} onClick={()=>act(()=>execute(config!,approval(purchase(i)),setStatus,setHash))}>1. APPROVE EXACT AMOUNT</button><button className="btn lime" disabled={busy||!a.authenticated||a.mismatch} onClick={()=>act(async()=>{await execute(config!,purchase(i),setStatus,setHash);await load()})}>2. BUY NFT</button></>:<span>OWNED BY ANOTHER WALLET</span>}</article>)}</div>
 {!items.length&&config?.decorations&&<p>No decorations on this page. Publish a decoration in the admin studio to open the first sale.</p>}<button className="btn outline" disabled={busy} onClick={()=>act(load)}>REFRESH OWNERSHIP</button>{!admin&&<><button disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}>PREVIOUS</button><span> Page {page+1} </span><button disabled={!more||busy} onClick={()=>setPage(p=>p+1)}>NEXT</button></>}</section>;
}
