'use client';
import {useCallback,useEffect,useState} from 'react';
import Game from './game';
import TutorialPanel from './tutorial-panel';
import ParcelWorld from './parcel-world';
import Wallet from './wallet';
import {GameWindow} from './game-window';
import DecorationShop from './decoration-shop';
import {useAuth} from './auth-provider';
type Plot={id:number;width:number;height:number;rarity:string;owner:string|null};
export default function GameSession(){
 const a=useAuth();const [visits,setVisits]=useState<{parcel:number}[]>([]);const [scene,setScene]=useState<'town'|number|null>(null),[menu,setMenu]=useState<'travel'|'decorations'|'tutorial'|null>('travel'),[plots,setPlots]=useState<Plot[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/land');const d=await r.json() as {parcels:Plot[];error:string};if(!r.ok)throw Error(d.error);setPlots((d.parcels??[]).filter(p=>p.owner?.toLowerCase()===a.user?.wallet.address.toLowerCase()))}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[a.user?.wallet.address]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),id=Number(params.get('parcel'));if(Number.isInteger(id)&&id>0&&id<=100){setScene(id);setMenu(null)}else if(params.get('menu')==='decorations')setMenu('decorations');const listener=(e:Event)=>setMenu((e as CustomEvent).detail==='decorations'?'decorations':'travel');window.addEventListener('tpu-game-menu',listener);return()=>window.removeEventListener('tpu-game-menu',listener)},[]);
 useEffect(()=>{if(menu==='travel'){refresh();fetch('/api/homestead').then(async r=>{if(!r.ok)return;const d=await r.json() as {parcels:{parcel:number}[]};setVisits(d.parcels)}).catch(()=>{})}},[menu,refresh]);
 async function enter(id:number,owned=true){setLoading(true);setError('');try{const r=await fetch(`/api/parcel?id=${id}`);const d=await r.json() as {canEdit:boolean;error:string};if(!r.ok)throw Error(d.error);if(owned&&!d.canEdit)throw Error('This wallet no longer owns that parcel. Refresh your land list.');setScene(id);setMenu(null);window.history.replaceState(null,'','/game')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 const close=(v:boolean)=>{if(!v&&scene!==null)setMenu(null)};
 return <>{scene==='town'?<Game suspended={menu!==null} onTravel={()=>setMenu('travel')}/>:typeof scene==='number'?<ParcelWorld key={scene} id={scene} suspended={menu!==null} onTravel={()=>setMenu('travel')} onTown={()=>{setScene('town');setMenu(null);window.history.replaceState(null,'','/game')}}/>:<div className="game-app game-entry"><header className="game-header"><a className="game-back" href="/">TRASH PANDA <b>UNITED</b></a><Wallet/></header></div>}
 <button className="game-tutorial-trigger" onClick={()=>setMenu('tutorial')}>GETTING STARTED</button><TutorialPanel open={menu==='tutorial'} onClose={()=>setMenu(scene===null?'travel':null)}/>
 <GameWindow open={menu==='travel'} onOpenChange={close} title="CHOOSE YOUR DESTINATION" description="Start in Trash Town or enter your own parcel."><button className="destination-town" onClick={()=>{setScene('town');setMenu(null);window.history.replaceState(null,'','/game')}}><span>TRASH TOWN</span><small>Quests, combat and the town square</small></button><h3 className="destination-label">MY LAND</h3>{loading&&<p role="status">Checking your parcels…</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="destination-grid">{plots.map(p=><button className="destination-card" disabled={loading} key={p.id} onClick={()=>enter(p.id)}><img src={`/assets/land-nft/${p.id}.png`} alt=""/><strong>PARCEL #{p.id}</strong><small>{p.width} × {p.height} · {p.rarity}</small></button>)}</div>{!loading&&!error&&!plots.length&&<p>You do not own a parcel yet. You can enter Trash Town now.</p>}<button className="text-link" disabled={loading} onClick={refresh}>REFRESH MY LAND</button><a className="text-link" href="/land">BROWSE LAND SALES</a><h3 className="destination-label">VISIT OTHER PARCELS</h3><p>Public parcels and invitations. Access is checked when you enter.</p><div className="destination-grid">{visits.filter(v=>!plots.some(p=>p.id===v.parcel)).map(v=><button className="destination-card" disabled={loading} key={v.parcel} onClick={()=>enter(v.parcel,false)}>VISIT PARCEL #{v.parcel}</button>)}</div>{!visits.length&&<p>No parcels are open for visits yet.</p>}</GameWindow>
 <GameWindow open={menu==='decorations'} onOpenChange={v=>{if(!v)setMenu(scene===null?'travel':null)}} title="DECORATION NFTS" description="Buy decorations and manage the NFTs in your wallet."><DecorationShop/></GameWindow></>;
}
