'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {defaultLanding} from '@/lib/community-config';
import {Announcements} from './announcements';
import {ArrowRight,ArrowUpRight, Crosshair, Hammer, MapPin, Shield, Swords, ChevronRight, Volume2, VolumeX} from 'lucide-react';
import Header from './header';
import {LandingArtwork} from './landing-artwork';
import {REGIONS} from '@/packages/game-core/world';
export default function Landing(){const [content,setContent]=useState(defaultLanding);useEffect(()=>{fetch('/api/content').then(r=>r.json() as Promise<{landing:typeof defaultLanding}>).then(d=>{if(d.landing)setContent(d.landing)}).catch(()=>{})},[]);const [region,setRegion]=useState(0);const [motion,setMotion]=useState(true);return <><Header/><main><Announcements/>
<section className={`hero ${!motion?'still':''}`}><div className="hero-art"/><div className="hero-shade"/><div className="scanlines"/><div className="hero-content"><div className="eyebrow"><span className="pink-square"/> {content.eyebrow}</div><h1>{content.title}<br/><span>{content.accent}</span></h1><p>{content.description}</p><div className="hero-buttons"><a className="btn lime" href="/game">{content.cta} <ArrowRight size={19}/></a><a className="btn outline" href="#world">EXPLORE WORLD</a></div><div className="hero-meta"><span>FREE TO PLAY</span><b>+</b><span>PLAYER-OWNED WORLD</span><b>+</b><span>BUILT ON BASE</span></div></div><div className="hero-location"><MapPin size={14}/><span>NEON DISTRICT<br/><b>SECTOR 04 // AFTER DARK</b></span></div><div className="hero-bottom"><span>01 / THE WASTELAND AWAITS</span><a href="#game">SCROLL TO SCAVENGE ↓</a><button aria-label="Toggle background animation" onClick={()=>setMotion(!motion)}>{motion?<Volume2 size={15}/>:<VolumeX size={15}/>} {motion?'MOTION ON':'MOTION OFF'}</button></div></section>
<div className="ticker"><span>{content.ticker}</span></div>
<section className="section game-intro" id="game"><div className="section-heading"><div><div className="eyebrow muted">{"// 01 \u2014 THIS IS YOUR WORLD"}</div><h2>SMALL PANDA.<br/>BIG <em>OPPORTUNITIES.</em></h2></div><p>{content.gameIntro}</p></div><div className="feature-grid">{[{n:'01',title:'SCAVENGE & SURVIVE',desc:'Venture beyond the neon. Battle mutants, collect scrap, and bring something useful home.',icon:<Swords size={19}/>,sheet:1,x:12,y:202,w:120,h:158,href:'/game'},{n:'02',title:'BUILD YOUR CORNER',desc:'Claim a parcel. Make a home, a workshop, or the next gathering place in Trash Town.',icon:<Hammer size={19}/>,sheet:4,x:8,y:240,w:280,h:201,href:'/land'},{n:'03',title:'OWN YOUR STORY',desc:'Your land. Your choices. Explore a player economy with ownership recorded on Base.',icon:<Shield size={19}/>,sheet:5,x:38,y:1038,w:242,h:194,href:'/marketplace'}].map(f=><a href={f.href} className="feature" key={f.n}><div className="feature-top"><span>{f.n} /</span>{f.icon}</div><div className="feature-art"><LandingArtwork sheet={f.sheet} x={f.x} y={f.y} w={f.w} h={f.h} label={f.title}/></div><h3>{f.title}<ArrowUpRight size={18}/></h3><p>{f.desc}</p></a>)}</div></section>
{content.showWorld&&<section className="world-section section" id="world"><div className="section-heading"><div><div className="eyebrow muted">{"// 02 \u2014 KNOW YOUR TERRITORY"}</div><h2>BEYOND THE <em>NEON.</em></h2></div><span className="tag">9 REGIONS. ONE BROKEN WORLD.</span></div><div className="world-layout"><div className="world-map" role="group" aria-label="World regions"><div className="map-terrain"/><div className="map-grid"/><svg className="map-routes" viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"><path d="M430 248 L150 130 M430 248 L180 368 M430 248 L470 72 M430 248 L700 181 M430 248 L630 368 M430 248 L430 436 M630 368 L760 436 M700 181 L800 72"/><path className="route-secondary" d="M150 130 L470 72 L800 72 L700 181 M180 368 L430 436 L760 436"/></svg><span className="map-zone zone-west">SALVAGE WILDS</span><span className="map-zone zone-east">QUARANTINE BELT</span>{REGIONS.map((r,i)=><button key={r.name} className={`region-node region-${i} ${i===region?'selected':''}`} onClick={()=>setRegion(i)} aria-pressed={i===region}><span className="region-signal"><Crosshair size={18}/><b>{String(i+1).padStart(2,'0')}</b></span><span>{r.name}</span><small>{i===0?'OPEN':'LOCKED'}</small></button>)}<div className="map-caption"><span>WASTELAND CARTOGRAPHY // GRID 009</span><span className="map-scale">0&nbsp;&nbsp;25&nbsp;&nbsp;50 KM</span></div></div><article className="region-info"><div className="eyebrow pink">SECTOR 0{region+1}</div><h3>{REGIONS[region].name.toUpperCase()}</h3><p>{REGIONS[region].description}</p><dl><div><dt>RECOMMENDED LEVEL</dt><dd>{REGIONS[region].level}</dd></div><div><dt>RESOURCES</dt><dd>{REGIONS[region].resources}</dd></div><div><dt>FACTION</dt><dd>{REGIONS[region].faction}</dd></div><div><dt>ACCESS</dt><dd>{region===0?'PLAYABLE':'EXPEDITION PLANNED'}</dd></div></dl><a href={region===0?'/game':'/land'} className="text-link">{region===0?'ENTER TRASH TOWN':'EXPLORE LAND'} <ArrowRight size={17}/></a></article></div></section>}
{content.showLand&&<section className="land-callout section" id="land"><div className="land-art"><LandingArtwork sheet={4} x={302} y={102} w={309} h={340} label="Complete scrap house with roof, entrance and neon details"/><span className="land-cross c1">+</span><span className="land-cross c2">+</span><span className="land-coord">PARCEL NETWORK // BASE SEPOLIA</span></div><div><div className="eyebrow lime-text">{"// NOT JUST A PLACE ON THE MAP"}</div><h2>A LITTLE LAND.<br/>A LOT OF <em>POSSIBILITY.</em></h2><p>{content.landDescription}</p><a className="btn lime" href="/land">EXPLORE LAND <ArrowUpRight size={18}/></a><span className="small-note">Testnet world · No real-money land sale</span></div></section>}
{content.showEconomy&&<section className="section economy" id="economy"><div className="section-heading"><div><div className="eyebrow muted">{"// 03 \u2014 NOTHING GOES TO WASTE"}</div><h2>SCRAP IS JUST<br/>THE <em>BEGINNING.</em></h2></div><p>Play to progress. Craft to create.<br/>A world worth owning starts with a game worth playing.</p></div><div className="economy-grid"><article><span className="icon-box">⚙</span><h3>SCRAP</h3><p>Earn it through quests and combat. Spend it on crafting, healing, and a home.</p><span className="tag">IN-GAME CURRENCY</span></article><article><Shield/><h3>LAND & COLLECTIBLES</h3><p>Land is the ownership anchor. Buildings remain attached to their parcel.</p><span className="tag">BASE · ERC-721</span></article><article><ArrowRight/><h3>PLAYER MARKET</h3><p>List a parcel, choose a currency, and trade directly with another player.</p><a href="/marketplace" className="text-link">OPEN MARKET <ArrowUpRight size={15}/></a></article></div></section>}
{content.showRoadmap&&<section className="section roadmap" id="roadmap"><div className="eyebrow muted">{"// 04 \u2014 BUILDING THE AFTERMATH"}</div><h2>ONE SCRAP <em>AT A TIME.</em></h2><div className="roadmap-grid">{[['01','FIRST FOOTSTEPS','IN DEVELOPMENT','Trash Town • combat • quests • crafting'],['02','PUT DOWN ROOTS','NEXT','Testnet land • housing • player trading'],['03','BETTER TOGETHER','PLANNED','Parties • guilds • shared expeditions'],['04','OPEN THE GATES','PLANNED','Security review • mainnet • new regions']].map(r=><article key={r[0]}><span className="road-number">{r[0]}</span><span className="tag">{r[2]}</span><h3>{r[1]}</h3><p>{r[3]}</p></article>)}</div></section>}
<section className="join section" id="community"><div><div className="eyebrow">FOR THE MISFITS. THE MAKERS. THE SCAVENGERS.</div><h2>{content.communityTitle}</h2></div><a href="/community" className="btn lime">MEET THE COMMUNITY <ChevronRight size={19}/></a></section>
</main><footer><Link className="brand" href="/home"><span>TRASH PANDA<strong>UNITED ///</strong></span></Link><p>A broken world. A fresh start.<br/><span>© {new Date().getFullYear()} Trash Panda United</span></p><a href="/litepaper">LITEPAPER <ArrowUpRight size={14}/></a><a href="/profile">YOUR PROFILE <ArrowUpRight size={14}/></a><span className="network-badge">BASE SEPOLIA / ALPHA</span></footer></>}
