'use client';
import {useEffect,useState} from 'react';
import ReferralPanel from './referral-panel';
import FounderOffer from './founder-offer';
import Header from './header';
import {Sprite} from './sprite';
import {useAuth} from './auth-provider';
type Season={title:string;status:string;ends_at:number;rules:{minDays:number;minPoints:number;daily:{points:number;cap:number};explore:{points:number;cap:number};dungeon:{points:number;cap:number};social:{points:number;cap:number};referral?:{points:number;cap:number}}};
export default function Program(){const auth=useAuth();const [season,setSeason]=useState<Season|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[preference,setPreference]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;fetch('/api/leaderboard').then(async r=>{if(!r.ok)throw Error('Season information is unavailable. Please reload.');return await r.json() as {season:Season|null}}).then(d=>{if(alive){setSeason(d.season);setLoaded(true)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 useEffect(()=>{let alive=true;if(auth.user)fetch('/api/program').then(async r=>{if(!r.ok)return;const d=await r.json() as {interest:{preference:string}|null};if(alive)setPreference(d.interest?.preference??'')}).catch(()=>{});return()=>{alive=false}},[auth.user]);
 async function join(value:string){setBusy(true);setError('');try{const r=await fetch('/api/program',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preference:value})});const d=await r.json() as {interest:{preference:string}|null;error:string};if(!r.ok)throw Error(d.error);setPreference(d.interest?.preference??'')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const open=season?.status==='active'&&season.ends_at>Date.now();
 return <><Header/><main className="subpage program-page"><section className="program-hero"><div><div className="eyebrow lime-text">BASE SEPOLIA · COMMUNITY TESTNET</div><h1>BUILD YOUR<br/><em>PLACE IN TOWN.</em></h1><p>Play, help other scavengers and share your adventures. Earn season points through verified achievements and original community content.</p><div className="admin-actions"><a className="btn lime" href="/game">PLAY THE TESTNET</a><a className="btn outline" href="/leaderboard">VIEW LEADERBOARD</a></div></div><Sprite width={150}/></section>
 {error&&<p className="error" role="alert">{error}</p>}
 <section className="profile-card"><span className="tag">{!loaded?'CHECKING SEASON':open?'SCORING OPEN':season?'SCORING CLOSED':'SEASON NOT STARTED'}</span><h2>{season?.title??'Your first season starts here'}</h2><p>{open?`Scoring closes ${new Date(season!.ends_at).toLocaleString()}.`:'Explore the game now. Check the leaderboard for published season dates and rules.'}</p>{season&&<><p>Qualification: {season.rules.minPoints} points across at least {season.rules.minDays} scoring days. Buying an NFT or land does not add leaderboard points.</p><div className="program-rules">{([['daily','Daily quests'],['explore','Salvage exploration'],['dungeon','Dungeon clears'],['social','Approved social quests'],['referral','Qualified referrals']] as const).filter(([key])=>season.rules[key]).map(([key,label])=><article key={key}><h3>{label}</h3><strong>{season.rules[key]!.points} points</strong><p>Up to {season.rules[key]!.cap} per UTC day</p></article>)}</div></>}</section>
 <div className="program-rules"><section className="profile-card"><h2>PLAY & RETURN</h2><p>Complete quests, explore caches and defeat the Garbage King. Points come from server-verified achievements, with daily caps. Repeated logins alone do not earn points.</p><a className="text-link" href="/game">ENTER TRASH TOWN →</a></section><section className="profile-card"><h2>CREATE & SHARE</h2><p>Publish original gameplay, beginner guides or a boss strategy. Include a link to the game and disclose rewarded participation. Submit evidence for review; copied content and spam are rejected.</p><a className="text-link" href="/campaigns">OPEN COMMUNITY QUESTS →</a></section></div>
 <ReferralPanel/><FounderOffer/><section className="profile-card" id="founders"><span className="tag">FOUNDER PROGRAM · INTEREST LIST ONLY</span><h2>HELP SHAPE WHAT COMES NEXT.</h2><p>We are exploring Founder cosmetics, titles and player-owned land. Tell us what interests you. This list is free and does not reserve an NFT, a plot, priority access or an airdrop allocation.</p><p>No paid Founder offer is open here. Prices, supply, delivered benefits and mainnet migration terms will be published before any sale.</p>{auth.user?<><div className="admin-actions">{(['nft','land','both'] as const).map(v=><button className="btn outline" disabled={busy} key={v} aria-pressed={preference===v} onClick={()=>join(v)}>{v==='nft'?'FOUNDER NFT':v==='land'?'LAND':'BOTH'}{preference===v?' · SAVED':''}</button>)}</div>{preference&&<p role="status">Interest saved to your account. <button disabled={busy} onClick={()=>join('withdraw')}>REMOVE MY INTEREST</button></p>}</>:<a className="btn outline" href="/register">REGISTER & CONNECT WALLET</a>}</section>
 <section className="profile-card"><h2>POINTS, REWARDS & MAINNET</h2><p>Testnet ETH has no monetary value. Season points are not tokens. Mainnet token distribution is planned, but its launch, allocation, token value and timing are not guaranteed. Qualification or a leaderboard share is not a funded payment promise.</p><p>There is no purchase requirement for earning season points. Reports of duplicate accounts or manipulated submissions are reviewed; excluded players can contact support. Qualified referrals can earn points only in seasons whose published rules include them, after administrator review.</p><a className="text-link" href="/support">QUEST REVIEW OR ACCOUNT APPEAL →</a></section></main></>;
}
