'use client';
import {useState} from 'react';
export const QUEST_METHODS={manual:'Review · X, videos and original content',tutorial:'Game · complete tutorial',game_level:'Game · reach a level',game_kills:'Game · defeat monsters',quest_complete:'Game · complete first story quest',dungeon_clear:'Game · clear Toxic Sewers',discord_member:'Discord · join server',discord_role:'Discord · obtain role',wallet_verified:'Web3 · verified wallet',native_balance:'Web3 · hold ETH',erc20_balance:'Web3 · hold ERC-20 tokens',erc721_balance:'Web3 · hold ERC-721 NFTs',erc1155_balance:'Web3 · hold ERC-1155 item'};
type Value={verification:string;target:string;role_id:string;threshold:number;chain_id?:number;requirement_amount?:string;token_id?:string};
export default function QuestConfigFields({value}:{value?:Value|null}){
 const [mode,setMode]=useState(value?.verification??'tutorial');const discord=mode.startsWith('discord_'),web3=['wallet_verified','native_balance','erc20_balance','erc721_balance','erc1155_balance'].includes(mode),contract=mode.startsWith('erc'),quantity=mode.endsWith('_balance');
 return <><label>HOW TO VERIFY<select name="verification" value={mode} onChange={e=>setMode(e.target.value)}>{Object.entries(QUEST_METHODS).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
 {(discord||contract)?<label>{discord?'DISCORD SERVER ID':'CONTRACT ADDRESS'}<input key={mode} name="target" required maxLength={42} placeholder={discord?'Server ID from Discord developer mode':'0x…'} defaultValue={value?.target??''}/></label>:<input type="hidden" name="target" value=""/>}
 {mode==='discord_role'?<label>REQUIRED DISCORD ROLE ID<input name="roleId" required defaultValue={value?.role_id??''}/></label>:<input type="hidden" name="roleId" value=""/>}
 {['game_level','game_kills'].includes(mode)?<label>{mode==='game_level'?'LEVEL REQUIRED':'MONSTERS DEFEATED'}<input name="threshold" type="number" min={1} max={1000} required defaultValue={value?.threshold??5}/></label>:<input type="hidden" name="threshold" value="1"/>}
 {web3?<label>NETWORK<select name="chainId" defaultValue={value?.chain_id??84532}><option value="84532">Base Sepolia · testnet</option><option value="8453">Base · mainnet</option></select></label>:<input type="hidden" name="chainId" value="84532"/>}
 {quantity?<label>MINIMUM BALANCE (WHOLE TOKEN UNITS)<input name="requirementAmount" required inputMode="decimal" placeholder="e.g. 0.001 or 10" defaultValue={value?.requirement_amount??'1'}/></label>:<input type="hidden" name="requirementAmount" value="1"/>}
 {mode==='erc1155_balance'?<label>ERC-1155 TOKEN ID<input name="tokenId" required inputMode="numeric" defaultValue={value?.token_id??'0'}/></label>:<input type="hidden" name="tokenId" value="0"/>}
 <p className="small-note">{mode==='manual'?'Original content needs human review. Opening a task link never proves completion.':discord?'First connect uses Discord OAuth. Add the server bot for subsequent automatic checks.':web3?'Read-only checks against the player’s verified wallet at a finalized block. No signature, transfer or spending approval is requested by verification.':'Progress is checked from the saved game on the server. Points are credited once.'}</p></>;
}
